### ISSUE TITLE
resources merging when using resourceOverlayDirectory parameter

### ISSUE THREAD

**Issue by marchelo** [simpligility/android-maven-plugin#345]
I've met an issue with "resourceOverlayDirectory" parameter on a project site:
https://code.google.com/p/maven-android-plugin/issues/detail?id=384

And it can be still reproduced on a latest revision.
I've checked sources of a android-maven-plugin, and seems that there is no functionality for merging such resources, like: string.xml, color.xml etc. Correct me if I'm wrong.

But it is critical for proper behavior of a "resourceOverlayDirectory" parameter.

Does it suppose to be implemented in future?

P.S: maybe some android.tools.* libraries have such functionality?

**Comment by mosabua** [comment]
From what I understand this is fixed..
