### ISSUE TITLE
Adding support for multiple dex filex

### ISSUE THREAD

**Issue by kkocel** [simpligility/android-maven-plugin#356]
What steps will reproduce the problem?
1. build a DEX file with a lots of jars as dependencies

The problem is described here:
https://code.google.com/p/android/issues/detail?id=7147
in short, DX only supports 65536 methods and will fail on large projects.

The workaround is described here:
http://android-developers.blogspot.com/2011/07/custom-class-loading-in-dalvik.html

The workaround is to simply generate multiple dex files and then load them in runtime. Therefore, it would be great if android-maven-plugin could be configured to generate multiple dex files. The configuration can be made very simple, such as:
<secondarydexes>
  <dex><name>jetty</name><includes><include>org.mortbay.jetty</includes></dex>
  <dex>...</dex>
</secondarydexes>
The plugin would then:
1. generate all secondary dexes, with all classes in given package and subpackages, and put them named as $NAME.dx into the assets/ directory.
2. generate primary dx file, without classes which went to a secondary dex file.
3. package

Thanks!

**Comment by robertoandrade** [comment]
Was the [documentation](http://simpligility.github.io/android-maven-plugin/apk-mojo.html) ever updated to reflect this change?  How does one enable the multidex option?
