### ISSUE TITLE
4.0.0-SNAPSHOT generates DEX multi-def errors, 3.8.2 does not

### ISSUE THREAD

**Issue by KarlCHansen** [simpligility/android-maven-plugin#383]
Identical settings, simply changed POM to reference 4.0.0-SNAPSHOT (30May @ noon) instead of 3.8.2 for plugin version.

Android Studio debug for app is configured to run "Gradle-aware Make" prior to launch.

"mvn clean install" works fine for both 3.8.2 and 4.0.0-SNAPSHOT.

Launching debug for app from Android Studio works after APK created by 3.8.2, but generates DEX multi-def errors after APK created by 4.0.0-SNAPSHOT.

**Comment by mosabua** [comment]
Closing since this is refactored. If you test and find this problem still exists.. please file a new issue.
