### ISSUE TITLE
If AAR dependency is project, classes.jar is empty and extract fails at unzipping

### ISSUE THREAD

**Issue by osbolab** [simpligility/android-maven-plugin#394]
Plugin version: Current 4.0.0-SNAPSHOT
Goal: compile

In a simple project where an `apk` module depends on an `aar` module, source generation fails because of the following:

```
[INFO] --- android-maven-plugin:3.9.0-rc.2:generate-sources (default-generate-sources) @ android-app ---
[INFO] Extracting libs
[INFO] Extracting apklib android-push...
[WARNING] The apklib artifact points to 'C:\Users\msbarnar\Projects\videohelper\android-parent\android-push\target\classes' which is a directory; skipping unpacking it.
[INFO] Extracting aar play-services...
[INFO] Getting manifests of dependent apklibs
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: android-push is missing AndroidManifest.xml
  at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.mergeManifests(GenerateSourcesMojo.java:923)
  at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:274)
```

This is reproduced for me by the sample project `TicTacToe - Parent`. It happens because the `classes.jar` that ends up in `target/unpacked-libs` of the `apk` module (e.g. `tictactoe-app/target/unpacked-libs/csat_tictactoe-library`) is empty. 

This is handled in [`GenerateSourcesMojo#extractAarLib()`](https://github.com/jayway/maven-android-plugin/blob/9deacf/src/main/java/com/jayway/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java#L476) where the warning about the `aar` being a directory [is generated](https://github.com/jayway/maven-android-plugin/blob/9deacf/src/main/java/com/jayway/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java#L478). It ignores that warning and [tries to unzip the classes jar anyway](https://github.com/jayway/maven-android-plugin/blob/9deacf/src/main/java/com/jayway/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java#L496), resulting in the above unzip exception.

**Comment by takarabt** [comment]
Hello,
I get this error during the build
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: ArchiverException while extracting MyBuildJob/target/unpacked-libs/cgag_play-services/classes.jar. Message: The source file MyBuiljob/target/unpacked-libs/cgag_play-services/classes.jar doesn't exist.
	at com.jayway.maven.plugins.android.common.ZipExtractor.extract(ZipExtractor.java:59)

I think that it's the same problem as above cause me too i have an empty aar archive

My question, in which version of android-maven-plugin the fix is provided. I use the android-maven-plugin:3.9.0-rc.3

Thanks

**Comment by mosabua** [comment]
Well... you are using an release candidate version - no wonder its not working. Upgrade to the latest version.

**Comment by takarabt** [comment]
I use the 4.0.0-rc.2 and i still getting this error /target/unpacked-libs/cgag_play-services/classes.jar (No such file or directory) i have tried with 4.3.0 version too,!
