### ISSUE TITLE
Instrumentation run failed due to 'java.lang.IllegalAccessError'

### ISSUE THREAD

**Issue by teoincontatto** [simpligility/android-maven-plugin#398]
Hello,

When running instrumentation tests I get the error:

```
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation 
```

There seems to be an issue with compilation or classloader somewhere that depends on the code touched by the test.

To reproduce on morseflash sample project:

Add this line in the onCreate method of ConfigureMorseActivity:

```
long[] morseCode = MorseCodeConverter.pattern('A');
```

Run the morseflash-instrumentation project.

Reproduced with 3.8.2, 3.9.0-rc.2 and master (51f16d553df717bbc3b0416402e9ad473a3b6ed4)

I found that closed issue #369 should have solved this. Maybe I did something wrong or this is a duplicate of #369.

**Comment by cameocoder** [comment]
Hit this same error when upgrading our android-maven-plugin from 3.8.2 to 4.1.1 (4.0.0 produced the same error). The workaround was to exclude aar dependencies from the provided apk dependency.  This was the same as the workaround proposed by @malachid in #369.

It seems issue #369 is not a complete fix for this issue.

**Comment by mosabua** [comment]
What is different in your project setup as compared to the example projects?

**Comment by cameocoder** [comment]
It is a large enterprise project and consumes 3 thirdparty aar files as well as many other dependencies.  The platform sdk is 16. We use RoboGuice for injection in the apk whose binding phase was involved in the stack trace.  We have not restructured our source so we are setting androidManifestFile, resourceDirectory, assetsDirectory and aidlSourceDirectory (needed in 4.1.1).

Before hitting this issue we also hit #548 and had to provide a value for testCoverageFile.

dependency:tree was showing the aar files as being top level dependencies of the integration test project when they should have only part of the apk.  The integration test project only had a few dependencies including the apk, robotium, junit and android.  Everything has provided scope except robotium.

**Comment by mosabua** [comment]
Closing old issue as cleanup
