### ISSUE TITLE
Version 3.9.0-rc3 requires certain packaging for android:deploy

### ISSUE THREAD

**Issue by jtulach** [simpligility/android-maven-plugin#427]
My project was using 3.7.0 which worked fine (except issue with pull #409). When the pull was merged,
I tried to switch to most recent version of the plugin (e.g. 3.9.0-rc3) in my project and build seems to be fine, but I have a problem with deployment. The plugin refuses to perform android:deploy and android:run complaining about wrong packaging:

```
--- maven-install-plugin:2.5.1:install-file (install-apk) @ minesweeper ---
pom.xml not found in minesweeper-2.4.apk
Installing //html~demo/minesweeper/target/minesweeper-2.4.apk to /.m2/repository/org/apidesign/demo/minesweeper/2.4/minesweeper-2.4.apk

--- android-maven-plugin:3.9.0-rc.3:deploy (default-cli) @ minesweeper ---
Project packaging is not apk, skipping deployment.

--- android-maven-plugin:3.9.0-rc.3:run (default-cli) @ minesweeper ---
Project packaging is not apk, skipping run action.
```

This is a regression compared to version 3.7.0 which was able to deploy without issues. Could the "apk packaging restriction" be removed? My pom.xml is multi-profile one:
http://source.apidesign.org/hg/html~demo/file/6227a7cc4bf8/minesweeper/pom.xml
and cannot specify apk packaging, as that would not work in the other profiles.

**Comment by mosabua** [comment]
Closing. Feel free to reopen or create new ticket.

**Comment by jtulach** [comment]
OK. I'll do my best to switch to apk packaging.
