### ISSUE TITLE
INSTALL_FAILED_DEXOPT on multidexing ..Any ideas?

### ISSUE THREAD

**Issue by vikky49** [simpligility/android-maven-plugin#430]
With android plugin version 4.0.0-SNAPSHOT

I was able to multi dex successfully

but after installing running into "Failure [INSTALL_FAILED_DEXOPT]" issues

Here is the log i gathered.

D/dalvikvm(17017): [Heap setting] startSize = 2 MB, maximumSize = 16 MB, growthlimit = 16 MB
E/dalvikvm(17017): ERROR: unrecognized magic number (50 4b 03 04)
E/dalvikvm(17017): ERROR: Byte swap + verify failed
E/dalvikvm(17017): Optimization failed
W/installd( 388): DexInv: --- END '/data/app/com.vcast.mediamanager-1.apk' --- status=0xff00, process failed
E/installd( 388): dexopt in='/data/app/com.vcast.mediamanager-1.apk' out='/data/dalvik-cache/data@app@com.vcast.mediamanager-1.apk@classes.dex' res=65280
W/PackageManager( 996): Couldn't delete native library directory /data/app-lib/com.vcast.mediamanager
V/PackageManager( 996): File /data/app/vmdl-1515185058.tmp changed: 40
V/PackageManager( 996): Ignoring change of non-package file: /data/app/vmdl-1515185058.tmp
V/PackageManager( 996): File /data/app/com.vcast.mediamanager-1.apk changed: 80
V/PackageManager( 996): ignoreCodePath
W/PackageManager( 996): Package couldn't be installed in /data/app/com.vcast.mediamanager-1.apk
V/WallpaperService( 996): WallpaperObserver onEvent ev=8 path=package-restrictions.xml
D/WallpaperService( 996): changedFile=/data/system/users/0/package-restrictions.xml
V/PackageManager( 996): File /data/app/com.vcast.mediamanager-1.apk changed: 200
V/PackageManager( 996): ignoreCodePath
V/WallpaperService( 996): WallpaperObserver onEvent ev=512 path=package-restrictions-backup.xml
D/WallpaperService( 996): changedFile=/data/system/users/0/package-restrictions-backup.xml
V/PackageManager( 996): + starting restore round-trip 48
V/PackageManager( 996): No restore - queue post-install for 48
I/PackageManager( 996): Trying to unbind DefaultContainerService
V/Perf (16243): com.android.defcontainer.DefaultContainerService@41a8c00 onUnBind, 0ms
V/Perf (16243): com.android.defcontainer.DefaultContainerService@41a8c00 onDestroy, 0ms
V/PackageManager( 996): Handling post-install for 48
I/PackageManager( 996): mcs_unbind
I/PackageManager( 996): calling disconnectService()
V/ActivityManager( 996): unbindService: conn=442b5ff8 pid=996
D/dalvikvm( 996): GC_EXPLICIT freed 6265K, 27% free 45349K/61284K, paused 8ms+31ms, total 239ms
D/IPCThreadState(16966): **** STOPPING PROCESS
D/AndroidRuntime(16966): Shutting down VM

**Comment by mosabua** [comment]
I assume this can be closed
