### ISSUE TITLE
Android NDK r10 toolchains not listed in AndroidNdk

### ISSUE THREAD

**Issue by dlew** [simpligility/android-maven-plugin#431]
The version is now -4.9, which causes the plugin to blowup because it can't find it.

The legacy downloads have disappeared as well.

**Comment by dss91** [comment]
Android NDK: Please use one of the following values:
 aarch64-linux-android-4.9 
aarch64-linux-android-clang3.4 
arm-linux-androideabi-4.6
 arm-linux-androideabi-4.8 
arm-linux-androideabi-4.9 
arm-linux-androideabi-clang3.3 
arm-linux-androideabi-clang3.4 
mips64el-linux-android-4.9 
mips64el-linux-android-clang3.4 
mipsel-linux-android-4.6 
mipsel-linux-android-4.8 
mipsel-linux-android-4.9 
mipsel-linux-android-clang3.3 
mipsel-linux-android-clang3.4
 x86-4.6 
x86-4.8 
x86-4.9 
x86-clang3.3 
x86-clang3.4 
x86_64-4.9 
x86_64-clang3.4
build/core/init.mk:588: *** Android NDK: Aborting    .  Stop.

I am still facing this issue how can i over come, any changes to be done to make script ?

**Comment by johanlindquist** [comment]
@dss91 Could you give the new NDK plugin a spin?  We are hoping to migrate to this (although it is taking some time).  Let me know if you have any questions about it.

Also, which NDK are you using etc?
