### ISSUE TITLE
Add support for skipping library artifacts in Proguard phase

### ISSUE THREAD

**Issue by antionio** [simpligility/android-maven-plugin#447]
Currently there doesn't seem to be a way to skip a library jar altogether from the Proguard phase. I have a problem with already Proguarded library jar that gives an error when the phase starts processing it. I see in the plugin code commons-logging is skipped with skipArtifact-method but there's no way to specify another jar/jars in XML configuration.

**Comment by william-ferguson-au** [comment]
Closing due to lack of interest.
