### ISSUE TITLE
Integration test build pulls in classes in AAR dependencies of main project

### ISSUE THREAD

**Issue by muzzah** [simpligility/android-maven-plugin#474]
Hey,

I have been looking to upgrade a project to 4.0 rc1. Our current project has the integration tests as a separate module. When running on the current stable release of the plugin everything works fine. When upgrading to 4.0, the integration test apk contains the class files from all the AARs in the main project that it specifies as a dependency. This result in an pre verified class error.

Looking at the [wiki](https://code.google.com/p/maven-android-plugin/wiki/AutomateAndroidTestProject) it say that along with specifying the main app as a provided scoped dependency, we should also do the same for any libraries. Though this seems like a regression from the current stable version of the plugin.

Should I add the aar's as provided scope (which seems counter intuitive) or is this indeed a regression in the current release candidate?

**Comment by mosabua** [comment]
Closing old issue as cleanup
