### ISSUE TITLE
Emma in multi modules maven project

### ISSUE THREAD

**Issue by Michenux** [simpligility/android-maven-plugin#475]
Hi,

My project has the following structure:
root
- app (android)
- common (standard java library)
- test (integration test)

Emma works fine but the report does not include the classes of the common module.

I have tried something like this to include the classes of the common modules but it doesnot work:

```
<plugin>
     <groupId>com.jayway.maven.plugins.android.generation2</groupId>
    <artifactId>android-maven-plugin</artifactId>
    <configuration>
                            <emma>
                                <enable>true</enable>
                                <classFolders>${project.basedir}/target/classes/,
                                        ${project.basedir}/../common/target/classes</classFolders>
                                <outputMetaFile>${project.basedir}/target/coverage.em </outputMetaFile>
                            </emma>
```

I use android-maven-plugin 3.7.0

What do i have to to instrument the classes of common module and what do i have to do so that they are included in the report ?

Best regards
Laurent

**Comment by mosabua** [comment]
Closing old issue as cleanup
