### ISSUE TITLE
Lint failure with 4.0.0-rc.1

### ISSUE THREAD

**Issue by hameno** [simpligility/android-maven-plugin#476]
As requested in https://groups.google.com/forum/#!topic/maven-android-developers/9MbL4DTQeeA I'm creating this issue. All information can be found in the linked thread.

Edit:

```
LintError: Lint Failure
src\main: No .class files were found in project "main", so none of the classfile based checks could be run. Does the project need to be built first?
Priority: 10 / 10
Category: Lint
Severity: Error
Explanation: Issues related to running lint itself, such as failure to read files, etc.
This issue type represents a problem running lint itself. Examples include failure to find bytecode for source files (which means certain detectors could not be run), parsing errors in lint configuration files, etc.
These errors are not errors in your own code, but they are shown to make it clear that some checks were not completed.

More info:

To suppress this error, use the issue id "LintError" as explained in the Suppressing Warnings and Errors section.
```

I pushed the branch to github (https://github.com/PSDev/LicensesDialog/tree/maven_plugin_400) and it can be reproduced by simply calling "mvn clean package".

**Comment by hameno** [comment]
This is still not working with 4.1.1

**Comment by Shusshu** [comment]
You can put a new flag.  I forgot which one but you can check the source
code.  I think it's legacy something.
It will enable the lint library from maven central to be used instead of
the cmd line from the android sdk.

**Comment by mosabua** [comment]
Its http://simpligility.github.io/android-maven-plugin/lint-mojo.html#legacy
