### ISSUE TITLE
Emma instrumentation does not work when Proguard is enabled

### ISSUE THREAD

**Issue by deadmoto** [simpligility/android-maven-plugin#489]
The problem is in lifecycle bindings themselves.
Proguard is bind to **process classes** phase but Emma is bind to **prepare package** phase.
When both Emma and Proguard are enabled, plugin builds project in the following order:

> 1. Compile classes and put into target/classes
> 2. Run Proguard and put obfuscated/optimized classes into something_obfuscated.jar (depends on plugin version).
> 3. Instrument classes in target/classes with Emma instrumentation
> 4. Pack something_obfuscated.jar into DEX file

This way instrumented classes just won't get into DEX and you will get 37 bytes coverage.ec file which basically means it is empty.

To fix the problem it is possible to re-bind **emma** goal to **process classes** phase:

```
<executions>
    <execution>
        <id>default-emma</id>
        <phase>process-classes</phase>
    </execution>
</executions>
```

Problem exists in android-maven-plugin for a long time and I observed it in 3.6.0 and 3.9.0-rc.2.

**Comment by mosabua** [comment]
Where did this go?

**Comment by mosabua** [comment]
Closing old issue as cleanup
