### ISSUE TITLE
Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:4.0.0-rc.2:generate-source AAR Lib

### ISSUE THREAD

**Issue by skauss** [simpligility/android-maven-plugin#494]
Hi,
I try the android-maven-plugin:4.0.0-rc.X to build our project.
I try to build a aar lib, I run into this Problem (checked with android-maven-plugin:4.0.0-rc.1, android-maven-plugin:4.0.0-rc.2 and android-maven-plugin:4.0.0-rc.3).

With 3.9.0-rc.2 I am able to build our App.

See see my mvn install -X 

ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:4.0.0-rc.2:generate-sources (default-generate-sources) on project GooglePlayService:
[ERROR] 
[ERROR] Found files or folders in non-standard locations in the project!
[ERROR] ....This might be a side-effect of a migration to Android Maven Plugin 4+.
[ERROR] ....Please observe the warnings for specific files and folders above.
[ERROR] ....Ideally you should restructure your project.
[ERROR] ....Alternatively add explicit configuration overrides for files or folders.
[ERROR] ....Finally you could set failOnNonStandardStructure to false, potentially resulting in other failures.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:4.0.0-rc.2:generate-sources (default-generate-sources) on project GooglePlayService: 

Found files or folders in non-standard locations in the project!
....This might be a side-effect of a migration to Android Maven Plugin 4+.
....Please observe the warnings for specific files and folders above.
....Ideally you should restructure your project.
....Alternatively add explicit configuration overrides for files or folders.
....Finally you could set failOnNonStandardStructure to false, potentially resulting in other failures.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)

I you need some additional Information please let me know.
Mac OS 10.10
Java version: 1.6.0_65
mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)

My library POM

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

```
<modelVersion>4.0.0</modelVersion>

<parent>
    <artifactId>AndroidApp</artifactId>
    <groupId>mobile.app.Android</groupId>
    <version>2.6.0-SNAPSHOT</version>
</parent>

<artifactId>GooglePlayService</artifactId>
<version>4.4.52-SNAPSHOT</version>
<packaging>aar</packaging>
<name>Android Google Play Services Extra</name>

<dependencies>
    <dependency>
        <groupId>com.google.android.gms</groupId>
        <artifactId>play-services</artifactId>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>com.jayway.maven.plugins.android.generation2</groupId>
            <artifactId>android-maven-plugin</artifactId>
        </plugin>
    </plugins>
    <sourceDirectory>src</sourceDirectory>
</build>
```

</project>
Regards
Stephan

**Comment by 4ntoine** [comment]
what are default locations?

**Comment by william-ferguson-au** [comment]
Standard Maven location.
* src/main/java
* src/main/res
* src/main/resources

**Comment by 4ntoine** [comment]
native libraries?

**Comment by mosabua** [comment]
Native libraries are declared as dependencies just like any other libraries.
