### ISSUE TITLE
classifier issue

### ISSUE THREAD

**Issue by dimgit** [simpligility/android-maven-plugin#510]
Hi,
I have a multi-module project that uses classifiers.
With previous versions of the android-maven-plugin the project was building Ok.
Now I upgraded to 4.0.0-rc.2 and I am getting build errors due to missing dependency Jar.
Attached is a simple project that demonstrates the problem.
Executing "mvn clean package" gives error:
...
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: Could not copy APK classes jar...
at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.extractApkClassesJar(GenerateSourcesMojo.java:618)
...

Sample code is here:
https://github.com/dimgit/android-maven-plugin-classifier

The version of Maven I use is 3.2.3

DG

**Comment by WonderCsabo** [comment]
@mosabua i wonder maybe this is due to #460 and co.?

**Comment by mosabua** [comment]
Closing old issue as cleanup
