### ISSUE TITLE
manifest-update messes up line-endings

### ISSUE THREAD

**Issue by mstevens83** [simpligility/android-maven-plugin#511]
I have noticed that `manifest-update` produces an `AndroidManifest.xml` file with _changed_ and _inconsistent_ line-endings.
In a nutshell: my source file has only `CRLF` endings but the one produced by `android:manifest-update` has a mixture of both `CRLF` and `LF` line-endings, which really can't be right if you ask me.

**Relevant `pom.xml` snippet**

```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <version>1.9.1</version>
    <executions>
        <execution>
            <id>parse-version</id>
            <goals>
                <goal>parse-version</goal>
            </goals>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>com.jayway.maven.plugins.android.generation2</groupId>
    <artifactId>android-maven-plugin</artifactId>
    <version>4.0.0-rc.2</version>
    <configuration>
        <sdk>
            <platform>19</platform>
        </sdk>
        <androidManifestFile>${project.basedir}/AndroidManifest.xml</androidManifestFile>
        <mergeManifests>true</mergeManifests>
        <assetsDirectory>${project.basedir}/assets</assetsDirectory>
        <resourceDirectory>${project.basedir}/res</resourceDirectory>
        <release>false</release>
        <classifier>debug</classifier>
        <sign>
            <debug>true</debug>
        </sign>
    </configuration>
    <extensions>true</extensions>
    <executions>
        <execution>
            <id>default-cli</id>
            <!-- the "default-cli" id is needed for the configuration below to be used when android:manifest-update is called directly from the command line -->
            <phase>process-resources</phase>
            <goals>
                <goal>manifest-update</goal>
            </goals>
            <configuration>
                <updatedManifestFile>${project.basedir}/AndroidManifest.xml</updatedManifestFile>
                <manifest>
                    <versionName>${project.version}</versionName>
                    <versionCode>${parsedVersion.majorVersion}${parsedVersion.minorVersion}${parsedVersion.incrementalVersion}</versionCode>
                </manifest>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Result**
Please have a careful look at before-after comparison in the screenshot below.
The parts with changed line-endings are highlighted in red. The change seems to affect only multi-line XML comments. As you can see `CRLF` becomes `LF` in those. All other lines retain their `CRLF` ending.
In addition, also highlighted in red, the multi-line comment on top also entirely _loses_ the line-ending following `-->`.
Just to be clear the only thing I wanted to achieve by running `android:manifest-update` was to change the `android:versionName` (highlighted in green). Any other changes, especially this line-endings business simply shouldn't happen...

![androidmanifest xml_before-after](https://cloud.githubusercontent.com/assets/2787305/5095023/bc9cf6c0-6f5d-11e4-9e9e-8d3584e60df3.png)

**My platform**

```
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T21:58:10+01:00)
Maven home: C:\dev\Java\Maven\bin\..
Java version: 1.8.0_20, vendor: Oracle Corporation
Java home: C:\dev\Java\JDK\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"
```

**Comment by mstevens83** [comment]
Will automatic use of this MMv2 be in the next AMP release? (i.e. v4.1.0 ?)

**Comment by mstevens83** [comment]
Also, is there a way to use this Manifest Merger in AMP v4.0.0? I want to verify if it really resolves the line endings problem.

**Comment by mosabua** [comment]
It will not be automatic .. and I will release 4.1.0 soon

**Comment by mstevens83** [comment]
I have tested the new manifest-merger mojo (as released with AMP v4.1.0) but unfortunately it exhibits the same fault behaviour with respect to line endings in multi-line xml comments.
So please reopen this issue...

**Comment by mstevens83** [comment]
I'm working on a patch.

**Comment by Shusshu** [comment]
I can confirm this happens on the manifest merger v2 I would say it's the fault on the builder library maintained by google as we do not manipulate the file anymore with the manifest-merger v2

**Comment by Shusshu** [comment]
I can confirm it also happens on a gradle project.

**Comment by mosabua** [comment]
Jeez... should file a bug for the gradle build as well then I guess.

**Comment by mstevens83** [comment]
I have a patch (will post a pull request in a few minutes) which works around the issue with some custom code in the AMP ManifestMergerMojo -- *but* I totally agree that the real problem is with the builder library, so do go ahead an file a bug report with Google.

**Comment by Shusshu** [comment]
@mstevens83 could you file a bug? I will star it and follow it.

**Comment by mstevens83** [comment]
@Shusshu sure, but I've never submitted build system bugs to Google, so can you point me to the appropriate place? Thanks.

**Comment by Shusshu** [comment]
https://code.google.com/p/android/issues/entry

**Comment by mstevens83** [comment]
Ah, so the same place a general Android bugs, Sorry. I should have googled ;-).
Thanks.

**Comment by mstevens83** [comment]
Bug filed here: https://code.google.com/p/android/issues/detail?id=96992

**Comment by mstevens83** [comment]
Commit 28e880c effectively fixes the issue as originally reported (i.e. pertaining to the ManifestUpdateMojo).
