### ISSUE TITLE
Remove NDK compile & other related mojos

### ISSUE THREAD

**Issue by johanlindquist** [simpligility/android-maven-plugin#516]
With the migration to the Android NDK maven plugin, the NDK mojos should be removed.  This should probably be done post 4.x?  Or would people rather have it done before?

**Comment by johanlindquist** [comment]
I think we should release (officially) the NDK plugin at this point.  I can then work on removing it from the SDK plugin.  Are you the man to go to for release processes or will you simply cook a release up?

**Comment by johanlindquist** [comment]
Guess we should tackle https://github.com/simpligility/android-ndk-maven-plugin/issues/5 before we do this though

**Comment by mosabua** [comment]
Agreed.. once we are okay with the codebase in terms of user facing API (=config parameters in pom and command line) we can release a 1.0 version imho. I can do that when you think its ready. We can also do an earlier version..

**Comment by mosabua** [comment]
What do you think about killing the tests and mojo after the release I am cutting now @johanlindquist

**Comment by johanlindquist** [comment]
Sure, makes sense.  Now that the NDK plugin itself is also stable, it should be alright

**Comment by johanlindquist** [comment]
One thing to consider - how should the plugin "find" native libraries?  Currently it is using a mix of dependencies, attached artifacts and actual files on disk (trying its best to locate them).

I would say that the first two are the two which should be used & support for this auto-location "stuff" should be dropped.

Thoughts?

**Comment by mosabua** [comment]
Totally agree with the removal of magic lookup stuff wherever possible.

**Comment by mosabua** [comment]
@johanlindquist I removed the two mojos, the IT test and the samples and the travis install of the NDK now from master. This effectively removed NDK building support. I am not sure how much more we can remove but we can do that piecemeal.  Feel free to send smaller cleanup/removal PRs. 

cc @simpligility/android-maven-plugins-core-committers
