### ISSUE TITLE
AAR Mojo does not always include all mandatory AAR files - eg /res folder and R.txt file

### ISSUE THREAD

**Issue by ViZak** [simpligility/android-maven-plugin#521]
http://tools.android.com/tech-docs/new-build-system/aar-format
1. Create simple aar (test-aar-library)
2. Remove R.txt from aar
3. Repack library
4. Create apk module
5. Add dependency on "test-aar-library" to apk module
6. Compile
7. The project is compiled without errors.

How R.class is generated? 

Note: The same is for "res" folder. It's also mandatory item within aar

**Comment by william-ferguson-au** [comment]
We actually need to rework the AAR Mojo to include a res folder and R.txt to conform to the AAR file structure. https://developer.android.com/studio/projects/android-library.html#aar-contents

There are tools starting to appear that check/rely upon conformance.
See https://github.com/ACRA/acra/issues/538

See also
See https://github.com/simpligility/android-maven-plugin/pull/308/files#r95049142
