### ISSUE TITLE
Android Annotations + APKLIB + APKLIB dependency

### ISSUE THREAD

**Issue by KleinerHacker** [simpligility/android-maven-plugin#522]
Hi,

if I have an APKLIB module that depends on an other APKLIB module and both uses Android Annotations it is not be able to build this module cause the R file for the dependent APKLIB has non static ids and all annotations from dependent module refers to non constant values now (not allowed).
In case of an APK with a dependent APKLIB the generated R file contains final ids. Here it works fine.

Please fix this failure cause Android Annotations never usable if an APKLIB depends on an other APKLIB.

**Comment by mosabua** [comment]
Closing old issue as cleanup
