### ISSUE TITLE
Too long command line with Windows

### ISSUE THREAD

**Issue by KleinerHacker** [simpligility/android-maven-plugin#523]
Hi,

if I have a lot of external and internal project dependencies for an Android App the command line cam be longer than 8000 characters. In this case Windows CMD cannot run Dexer process cause the command line is too long. 
But the Dexer program allows to define a folder contains all the JAR files to Dexing. In this case the command line is not too long.

Please add a configuration property to define an optional folder to copy all dependencies in it and than call Dexer with this folder name to Dexing all files in it to solve this problem.

**Comment by songwk** [comment]
Hi All
  I am using android-maven-plugin 4.3.0, I didn't find parameters for it. Is there a workaround for this problem on windows?

Best regards

**Comment by mosabua** [comment]
Closing old issue as cleanup
