### ISSUE TITLE
Releasing a multi-module project w/ aar submodules, requires -DignoreSnapshots=true

### ISSUE THREAD

**Issue by MartinMReed** [simpligility/android-maven-plugin#529]
When performing the release of a multi-module project that has aar submodules, using `-DignoreSnapshots=true` is required when it should not be.

    mvn clean release:prepare release:perform --batch-mode -DdryRun=true

If you run the above, in the log when it executes release:prepare and it says it is checking the versions, it prints this in the error:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:prepare (default-cli) on project android-core: Can't release project due to non released dependencies :
    [ERROR] com.my.company:my-app-android_extracted:jar:1.0.0-SNAPSHOT:system

The correct full name should be `com.my.company:my-app-android:aar:1.0.0-SNAPSHOT`
The artifact and packaging changed to the `_extracted:jar`.

The release plugin is only supposed to care about external dependencies:
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.maven.release/maven-release-manager/2.5/org/apache/maven/shared/release/phase/CheckDependencySnapshotsPhase.java#311

    315        // We are only looking at dependencies external to the project - ignore anything found in the reactor as
    316        // it's version will be updated

So when its validating the versions it should ignore submodules because they are part of the reactor. But its finding the `_extracted:jar`, so it fails. The workaround is to add `-DignoreSnapshots=true`, however this should not be required.

android-maven-plugin version 4.0.0
maven-release-plugin version 2.3.2, 2.5.1

**Comment by mosabua** [comment]
Can this be closed?

**Comment by william-ferguson-au** [comment]
I believe so.
This appears to be one of the the issue fixed by #565
