### ISSUE TITLE
Support Jack & Jill

### ISSUE THREAD

**Issue by Shusshu** [simpligility/android-maven-plugin#536]
We can support Jack & Jill in the future when it becomes a bit more stable

http://tools.android.com/tech-docs/jackandjill

**Comment by adorokhine** [comment]
Any plans to prioritize this? Targeting JDK 8 on Android seems to require jack:
https://developer.android.com/preview/j8-jack.html

**Comment by Shusshu** [comment]
Hi,

Please feel free to have a go at it.

**Comment by malachid** [comment]
You can target JDK8 with the existing toolset.  If you want to use the new
language features (lambdas and functional interfaces), that's what requires
Jack.

**Comment by secondsun** [comment]
We (RedHat mobile) are willing to take this on.

**Comment by mosabua** [comment]
That would be amazing! I am able to work on PR merges and releases as usual.

**Comment by secondsun** [comment]
OK so quick update time : 

We finally got a chance to start on this.  You can follow our JIRA for the feature here : https://issues.jboss.org/browse/FH-2743
and my working branch is here : 
https://github.com/secondsun/maven-android-plugin/tree/jack_support

So far I can hand off to the Jack compiler (though actually getting it to compile is a work in progress...) using the compilerId property of the maven compiler plugin, and I have created a configuration object "Jack".  

Right now the Jack configuration object only has an enabled property.  This property is currently is used by the Dex Mojo to tell it that it doesn't need to do any work.  

You can see an example pom here : https://github.com/secondsun/maven-android-plugin/blob/jack_support/src/test/projects/helloflashlight_jack/pom.xml

I was wondering, is there some way to combine the jack.enabled flag and the jack compilerId?  It seems silly to specify the same intent in two places.  Either I would have to at the start of a build inject a property not in the pom into the compiler mojo or I would have to have the Jack config object pull a property from the compiler plugin.  Or maybe there is a third option I have missed?

**Comment by mosabua** [comment]
Thats amazing @secondsun ! 

I asked about tips on the Maven dev list. Worst case I think you can set the jack compilerId in the compiler plugin and figure out if its set from the Android Maven Plugin ..

**Comment by mosabua** [comment]
The other thing you could do is to make it a requirement to have jack defined via a property and access that property in the pom and in the android maven plugin from code. E.g you could use android.compilerId or something like that.

**Comment by mosabua** [comment]
Actually I think if you configure the compilerId as a user property in the Jack or Dex Mojo and use that property in the pom for the compiler plugin I think there is nothing you have to write in terms of code.  Let me know if you want me to make an example pom and Mojo code snippet

**Comment by mosabua** [comment]
@secondsun .. on the maven dev list it was suggested that the standard approach that other compiler related plugins share as well is to use the user property maven.compiler.compilerId

See https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#compilerId

on the jack (and dex or whatever) mojo. Then the compiler plugin will do the right thing automatically and you will automatically have the value injected and from checking the value to be "jack" can determine the correct course of action. This is the standard way also used by e.g. c compilation in the native plugin and others. Ping me if you have questions or want some code snippet or PR on your progress..

**Comment by mosabua** [comment]
Here is the exact text from the mailing list from @rfscholte (Thanks!!)

There are several plugins which need to use the same value of the javac's  
target argument.
This plugins should not be aware of each other, we solved this by sharing  
the maven.compiler.target property.

In your case, ask your users to specify
<properties>
   <maven.compiler.compilerId>jack</maven.compiler.compilerId>
</properties>
the maven-compiler-plugin will already pick this up, let the android maven  
plugin do the same.

Robert

**Comment by secondsun** [comment]
Woo I have executing code now!

https://www.youtube.com/watch?v=0b3wGdVulIs&feature=youtu.be

Would it be possible to create a jack feature branch here so we can start discussing the code as a work in progress?

**Comment by mosabua** [comment]
Totally... either a feature branch ... or even just merge it into master (flagged as experimental or so) and iterate on it there...

**Comment by mosabua** [comment]
If you @secondsun send a PR .. I can merge .. or I can pull from whatever branch/repo you indicate to me. I can do that tonight..

**Comment by mosabua** [comment]
Also once its merged we should announce on the mailing list with a link to the video ;-)

**Comment by andyp1per** [comment]
It's very important to support jill as well as jack. Most folk will be using the android-maven-plugin to integrate existing libararies IMO and Jill is the only way to do this. I can't see this being that hard - Jill is effectively a replacement for the aar step - you would then just need to use Jack at the end. 
Has anyone yet worked on Jill support? Happy to start looking if no-one has kicked this off.

**Comment by natami** [comment]
Any news on this?

**Comment by secondsun** [comment]
So my patch made the plugin work for my team's purposes and we have moved on.

For the most part, Jack is only used for building applications and the plugin seems to handle my use cases correctly.  Building libraries with Jack isn't supported by the Gradle Android plugins last time I checked so there isn't a reference implementation to try out.

However, if you build an aar with Java 8 and and this plugin then you get code that you can consume correctly in both the Gradle plugin and this plugin (last time I checked.  I don't have automated tests watching this).

As far as Jill goes, the plugin passes dependencies to Jack correctly and it seems like Jill gets invoked by the Jack compiler.

I suggest you build the plugin from source and give it a spin on your own projects and report problems back here so we have more data points than my feeble memory :).

**Comment by natami** [comment]
May i suggest someone does a snapshot release to sonatype snapshot repository?

- That my make it easier for others to test it out and report any problems?

**Comment by ILadis** [comment]
Hello everyone!

Since I'm also interested in having Jack compiler support in this plugin, I spent some time of the weekend to look into the Jack compiler component written by @secondsun. I'm also new to Maven Plugin development, so it took me some time to understand how everything get's glued together.

After all I was able to work on the code @secondsun had already written. Hopefully I could make some improvements to the Jack compiler component. I would be really greatful if you could look into my changes and give me feedback. I forked this repository to [ILadis/android-maven-plugin](https://github.com/ILadis/android-maven-plugin) and committed my changes to the [jack_support](https://github.com/ILadis/android-maven-plugin/commits/jack_support) branch.

I'm also unsure if it's a good approach to write a new compiler component. When someone's now using the Jack compiler with `<compilerId>jack</compilerId>` the output would be a single `classes.dex` file. 
This could be an issue if one has for example unit tests that require compiled `.class` files.
You surely can workaround this issue, when both configuring the Jack and Java compiler in your POM (see example below).
I'd rather extend the existing dex phase, and leave the compiler configuration as it was before. The `DexMojo` could be rewritten to use the Jack compiler to produce the `classes.dex` file.

What do you think?

Example plugin configuration to produce `classes.dex` as well as `.class` files:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.6.0</version>
  <dependencies>
    <dependency>
      <groupId>com.simpligility.maven.plugins</groupId>
      <artifactId>android-maven-plugin</artifactId>
      <version>4.4.4-SNAPSHOT</version>
    </dependency>
  </dependencies>
  <executions>
    <execution>
      <id>default-compile</id>
      <phase>compile</phase>
      <goals><goal>compile</goal></goals>
      <configuration>
        <source>1.8</source>
        <target>1.8</target>
        <compilerId>jack</compilerId>
      </configuration>
    </execution>
    <execution>
      <id>default-javac</id>
      <phase>compile</phase>
      <goals><goal>compile</goal></goals>
      <configuration>
        <source>1.8</source>
        <target>1.8</target>
        <compilerId>javac</compilerId>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by andyp1per** [comment]
Do folk use dexmaker with this? That's what we are doing, but I wonder if this step is still necessary.

I still believe that integrating jack is only part of the solution - you need to do jill as well to get correct linking behaviour with standard java8 jar files.

**Comment by secondsun** [comment]
I propose we close this issue, Google is deprecating Jack

https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html

**Comment by mosabua** [comment]
Agreed.
