### ISSUE TITLE
With <failOnNonStandardStructure>false</failOnNonStandardStructure>, the AndroidManifest.xml file is not altered properly.

### ISSUE THREAD

**Issue by derekbrameyer** [simpligility/android-maven-plugin#547]
Flags in my AndroidManifest.xml file like debuggable, versionCode, and versionName are not changed properly when using the "old" style project structure.

The changes appear to be made, but then the AndroidManifest.xml file is copied to src/main/ and then not used when creating the .apk file.

**Comment by mosabua** [comment]
So can we close this?
