### ISSUE TITLE
java.lang.IllegalArgumentException: name or value arguments cannot be null when running tests

### ISSUE THREAD

**Issue by yanchenko** [simpligility/android-maven-plugin#548]
I've migrated DroidParts (https://github.com/yanchenko/droidparts/tree/develop) to 4.0 and the issue I've got is that tests don't run now.
The .apk gets uploaded but then I see

```
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ droidparts-test ---
java.lang.IllegalArgumentException: name or value arguments cannot be null
    at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.addInstrumentationArg(RemoteAndroidTestRunner.java:147)
    at com.jayway.maven.plugins.android.AbstractInstrumentationMojo$1.doWithDevice(AbstractInstrumentationMojo.java:379)
    at com.jayway.maven.plugins.android.ScreenshotServiceWrapper.doWithDevice(ScreenshotServiceWrapper.java:56)
    at com.jayway.maven.plugins.android.AbstractAndroidMojo$2.runDo(AbstractAndroidMojo.java:806)
    at com.jayway.maven.plugins.android.AbstractAndroidMojo$DoThread.run(AbstractAndroidMojo.java:1304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

How to fix it?
Maybe provide a better message?
Project build doesn't fail after this, guess it should.

**Comment by nadnavillus** [comment]
I just ran into this bug as well, no emma coverage, using just Junit.  It appears that the work-around does work.  First I added a property to the maven pom.  This did not work.  On the second attempt I added the testCoverageFile property to the android-maven-plugin.

<build>
  <plugins>
    <plugin>
         <groupid>com.simpligility.maven.plugins</groupid>
         <artifactId>android-maven-plugin</artifactId>

**Comment by nadnavillus** [comment]
I just ran into the same bug..... no emma coverage just straight junt.  Addint the property to the pom at the global level had not effect but adding it directly to the build/plugin/configuration did do the trick.

I believe this is caused by missing null check missing @ AbstractInstrumentationMojo line 351:

                if ( ! "".equals( parsedCoverageFile ) )
                {
                    remoteAndroidTestRunner.addInstrumentationArg( "coverageFile", parsedCoverageFile );
                }

At this point with no code coverage set up the parsedCoverageFile is null.  The test passes and the underlying call to addInstrumentationArg throws an IllegalArgumentException as the value is null.

Not sure if simply wrapping this in the if statement would be enough.

**Comment by andyp1per** [comment]
This happens in libraryprojects in the actual plugin samples. Pretty bad IMO that the samples you ship do not actually work. In a related note the failure does not fail the test! Crazy that this has been opened for more than 6 months.

**Comment by andyp1per** [comment]
If I add:

          <configuration>
              <testCoverageFile>foobar</testCoverageFile>
          </configuration>

to libraryprojects/libraryprojects-tests then the tests start, but I get 4 errors. At least the build fails at that point.

**Comment by william-ferguson-au** [comment]
Great Andy, looking forward to your pull request. This IS a community
project.
