### ISSUE TITLE
Does android-maven-plugin plan to support generate main-dex-list file automatically?

### ISSUE THREAD

**Issue by xiaojiaqiao** [simpligility/android-maven-plugin#549]
I found static main-dex-list file for multidexing is out of sync during the development. If update this file manually everytime is terrible..so will this great feature be come true?

**Comment by mosabua** [comment]
@psorobka wdyt .. can we close this with the recent merge?

**Comment by xiaojiaqiao** [comment]
It's seems be solve by this pull request. https://github.com/simpligility/android-maven-plugin/pull/526.
so it can be close.

**Comment by mosabua** [comment]
@xiaojiaqiao Thanks... if you have any improvements or other stuff to contribute we all look forward to it ;-)
