### ISSUE TITLE
Multi Dex example

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-maven-plugin#552]
Port project from https://github.com/lsuski/maven-multidex-sample over to IT test

**Comment by mosabua** [comment]
Had a bit of a look at the example. Problem are the dependencies needed to run the project. None of them are in Central so we have to either add a manual install in the the local repo or somehow else get them to be available. 

Maybe we should have this provision goal in the android maven plugin that replaces the Maven Android SDK Deployer after all. Maybe I can even pull in some code from the Maven Repo Tools project to make it happen. Will have to think about this a bit..

**Comment by william-ferguson-au** [comment]
Yeah, it's painful having those deps not generally available.
Was bitten by the Android SDK Manager yesterday :
http://design-counts.blogspot.com.au/2015/01/be-wary-of-android-sdk-updates.html


  [image: photo]
*William Ferguson*
Founder and CEO, XandarMob
 m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>
  ᐧ

**Comment by Shusshu** [comment]
Yep, share your thought whenever you want I'm interested in this too :) (alternative could be to setup a github repo as a maven repo with the dependencies we need... not sure if this would be legal)

**Comment by mosabua** [comment]
I think it would be fairly easy to write a "provision" mojo that takes the two Maven repositories from the SDK and installs all artifacts into the local Maven repo. I kind of have a tool that does something similar already although that ones is not really finished or good enough for production usage yet. https://github.com/simpligility/maven-repository-tools

**Comment by mosabua** [comment]
And btw hosting the Android SDK repos anywhere violates the EULA. If that would be possible I would have pushed it to central ages ago ;-)

**Comment by mosabua** [comment]
Closing old issue as cleanup
