### ISSUE TITLE
aar BuildConfig values not generated in release

### ISSUE THREAD

**Issue by kkalisz** [simpligility/android-maven-plugin#553]
When we use aar libraries, in most cases they have BuildConfig.DEBUG == true (logs etc), 
If we build release apk, BuildConfig files for libraries are not generated (they exists and generation is skipped).
As result all BuildConfig files except application BuildConfig have DEBUG value set to true, now
statement if( BuildConfig.DEBUG ){} have only sense in application projects.
I think that expected behaviour would be generating new BuildConfig files for all artifacts in release build. Am I right !?

<pre>
Old Way ( ant, apklibs )
DEV
LibA BuildConfig.DEBUG = true
LibB BuildConfig.DEBUG = true
MyApplication BuildConfig.DEBUG = true

RELEASE
LibA BuildConfig.DEBUG = false
LibB BuildConfig.DEBUG = false
MyApplication BuildConfig.DEBUG = false

New Way ( aar )
DEV
LibA BuildConfig.DEBUG = true
LibB BuildConfig.DEBUG = true
MyApplication BuildConfig.DEBUG = true

RELEASE
LibA BuildConfig.DEBUG = true
LibB BuildConfig.DEBUG = true
MyApplication BuildConfig.DEBUG = false
</pre>

**Comment by Shusshu** [comment]
No I don't think so, the BuildConfig must be generated by the library since you can put specific variable in there.

That's what I understood from google android tools team. (Can't remember where I read that)

**Comment by kkalisz** [comment]
there is ticket for gradle  https://code.google.com/p/android/issues/detail?id=52962

BuildConfig was always generated for all libraries during apk build time, It was it's main functionality.
If it wouldn't be generated It dont't make a lat of sense to use it.

I can publish release version of my libs with BuildConfig.DEBUG=false, but what If I wan't for example see logs or show some debug options when I develop my application !? I should have few different "release" versions ?

**Comment by william-ferguson-au** [comment]
No. If you want to use DEBUG=true then you use a non-release (ie dev) library version.
When you are ready to release you create a release version with DEBUG=false
