### ISSUE TITLE
aidlSourceDirectory uses old default location

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#555]
This property still uses `project.build.sourceDirectory` as its default value, however aidl files are placed in *src/main/aidl* in the new project structure.

**Comment by mosabua** [comment]
Should we fix this @simpligility/android-maven-plugins-core-committers here or in the NDK plugin or both?

**Comment by WonderCsabo** [comment]
Why NDK? AIDL is used in plain Android apps, too. For example for in app purchases.

**Comment by mosabua** [comment]
Oh.. sorry. My bad. I guess we have to fix it.
