### ISSUE TITLE
Android library project (AAR) and proguard usage

### ISSUE THREAD

**Issue by dpsm** [simpligility/android-maven-plugin#558]
It seems that when proguard is enabled on a maven project of packaging type AAR a XX_obfuscated.jar is generated. However the obfuscated jar file is not used while building the AAR.

Is that the expected behaviour? It seems wrong given I might want to legitimately obfuscate some of my AAR classes to distribute it. In that use case all maven dependencies should be treated as library jars while using proguard so that the dependency resolution still works when someone consuming my AAR builds an APK.

I have a local fork with changes that basically looks at the project type and if it's an AAR package type will use the obfuscated jar instead of generating one from the class folder. If this is something that makes sense for the general community, I'd be happy to contribute!

**Comment by william-ferguson-au** [comment]
So are all dependencies also obfuscated and included in your AAR?

I can understand wanting to obfuscate your own classes that you distribute
within your AAR.
But including dependencies packaged into your AAR is not good practice.




  [image: photo]
*William Ferguson*
Founder and CEO, XandarMob
 m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>
  ᐧ

**Comment by dpsm** [comment]
@william-ferguson-au you are correct, the dependencies are not added to the classes.jar within the AAR and the references to them are not obfuscated. Only the code from your project (depending on your proguard config) will.

That way, when someone uses your AAR it will allow the dependency resolution in the final APK project and everything works as much as it does with the current code base.

**Comment by william-ferguson-au** [comment]
In that case it sounds like a great addition!


  [image: photo]
*William Ferguson*
Founder and CEO, XandarMob
 m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>
  ᐧ

**Comment by dpsm** [comment]
Awesome. I'll send a pull request soon!

**Comment by dpsm** [comment]
Pull request => https://github.com/simpligility/android-maven-plugin/pull/559

**Comment by mosabua** [comment]
I assume this can be closed since the pull request is merged. Reopen if I am wrong.

**Comment by william-ferguson-au** [comment]
My bad - sorry @mosabua

**Comment by mosabua** [comment]
no problem @william-ferguson-au ... just checking things out to get 4.2.0 out sooner rather than later..
