### ISSUE TITLE
Ability to generate AIDL files in non-apk projects

### ISSUE THREAD

**Issue by balbusm** [simpligility/android-maven-plugin#561]
In a project configured for .jar (standard) packaging, I still like to be able to generate the AIDL files and include them in the jar.

I tried "mvn clean android:generate-sources". It picks up the goal but does nothing.

If I change the packaging to apk the above command generates the AIDL files as expected (to target/generated-sources/aidl). However, the project is no apk project.

(Note that in my final build, I plan to bind the generate-sources goal to the generate-sources lifecycle phase.)

My environment:
Maven version: 3.0.4 (Ubuntu package)
maven-android-plugin version: 3.9.0
Ubuntu 14.04

**Comment by mosabua** [comment]
Try with 4.1.0 of the plugin. Also we do not really support the plugin for non-Android packaging types .. e.g. jar like the suggeted usage.

**Comment by royiby** [comment]
I have a similar problem but with an aar project.
Should i open a new issue or add more information here?

**Comment by william-ferguson-au** [comment]
Hey @royiby create a new issue, add in the details I suggested.
