### ISSUE TITLE
Can you help to give a demo about how to build multi-dex apk?

### ISSUE THREAD

**Issue by Gankerzzl** [simpligility/android-maven-plugin#562]
I found that the plugin had support multi-dex in changelogs, but I don't know how to take advantage of this feature. Can any one give me an example? I googled all the internet but found no useful tutorials for me. Thank you very much.

**Comment by Shusshu** [comment]
You can check in https://github.com/simpligility/android-maven-plugin/issues/552 it is talking about an example currently located outside the project: https://github.com/lsuski/maven-multidex-sample

**Comment by Gankerzzl** [comment]
Hi shusshu, Thanks for your reply! I modified my app according to that demo, but the builded apk still contains one dex. I did the following:

1. Modify MyApplication.java, add the method:
        @Override
	protected void attachBaseContext(Context base) {
		super.attachBaseContext(base);
		MultiDex.install(this);
	} 

2. Modify the pom.xml, add the following tags:
        <multi-dex>true</multi-dex>
	<minimal-main-dex>true</minimal-main-dex>
	<dex-arguments>--set-max-idx-number=65536</dex-arguments>
	<main-dex-list>${project.basedir}/MainDexList.txt</main-dex-list>
   The MainDexList.txt's content:
         android/support/multidex/MultiDex.class
         android/support/multidex/MultiDex$V4.class
         android/support/multidex/MultiDex$V14.class
         android/support/multidex/MultiDex$V19.class
         android/support/multidex/MultiDexApplication.class
         android/support/multidex/MultiDexExtractor.class
         android/support/multidex/MultiDexExtractor$1.class
         android/support/multidex/ZipUtil.class
         android/support/multidex/ZipUtil$CentralDirectory.class
         com/yy/iheima/MyApplication.class

Is there still something that I didn't do? Or I made mistake about the above modification? Thanks again.

**Comment by Shusshu** [comment]
Maybe you are not reaching the method limit count.....

**Comment by Gankerzzl** [comment]
Yeah, exactly. Our app has only 56000+ methods, but I changed the tag --set-max-idx-number to 45536, the built apk still only contains one dex. In normal situation, will multiple dex be produced after take above modification?

**Comment by Gankerzzl** [comment]
The reason I want to multi dex is our app encounter this bug in Android 2.3 whose root cause is similar with 64k methods limit.
https://code.google.com/p/android/issues/detail?id=22586

**Comment by Gankerzzl** [comment]
Finally I still can not build multi dex apk by android studio with maven. But I built it succesfully by maven command line.

All of what I did is following:
Modify MyApplication.java, add the method:
@Override
protected void attachBaseContext(Context base) {
super.attachBaseContext(base);
MultiDex.install(this);
}

Modify the pom.xml, add the following tags:
< multi-dex >true< /multi-dex >
< minimal-main-dex >true< /minimal-main-dex >
< dex-arguments >--set-max-idx-number=65536< /dex-arguments >

If you can not build by AS, try maven command line.

**Comment by alexleech** [comment]
Hi Gankerzzl
Would you please release your full script of pom.xml?
I'm using the maven with android-maven-plugin 3.7.0. (cannot upgrade to newer version cuz it's a team project)
Thank you!
