### ISSUE TITLE
Provision Mojo

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-maven-plugin#566]
It would be good to be able to replace the Maven Android SDK Deployer with a provision mojo. Initially it would be good enough to copy the repositories that are in the SDK and be able to install them to the local repo. 

Later it could do deploy as well and also cover more components.

This class can be used to turn a path to a GAV. https://github.com/apache/maven-indexer/blob/master/indexer-core/src/main/java/org/apache/maven/index/artifact/M2GavCalculator.java

And some of the aehter related code in https://github.com/simpligility/maven-repository-tools can do more. It might actually be best to have the directory to repo install or deploy code in that project and then just use it here.

**Comment by william-ferguson-au** [comment]
If you are a repo manager (like Nexus) you don't need to copy the 2 Android
repos anywhere. You just need to setup 2 hosted Nexus repos that point to
each folder.

Where we do need the SDk deployer is in creating and installing the jars
for the versions of Android.
ᐧ

**Comment by william-ferguson-au** [comment]
.. that should have read :
If you are using a repo manager (like Nexus) ..
ᐧ

**Comment by mosabua** [comment]
That only works if the repo manager file system is available to the machine that has the SDK and relies on the Maven repo being a Maven repo in the filesystem as well. This is currently the case for Nexus and Archiva. It is NOT the case for Artifactory. The safer and better way is still a deployment to a repo manager via the usual mechanism.

**Comment by mosabua** [comment]
And yes... the deployment of the Android jars that way would be good too.. sort of step 2 ..

**Comment by william-ferguson-au** [comment]
Good point.
ᐧ

**Comment by mosabua** [comment]
not going to worry about this
