### ISSUE TITLE
android-maven-plugin not working with APP_ABI set to arm64-v8a

### ISSUE THREAD

**Issue by arnaud-soulard** [simpligility/android-maven-plugin#571]
I made a patch I would like to attach to this issue.

**Comment by mosabua** [comment]
Please send a pull request and more importantly also send a pull request to the android-ndk-maven-plugin

**Comment by johanlindquist** [comment]
For what it is worth, the android-ndk-maven-plugin should support this already - could you raise the same ticket there if it is not working?
