### ISSUE TITLE
ndk-build not debuggable

### ISSUE THREAD

**Issue by himamis** [simpligility/android-maven-plugin#572]
When debugging native c source, the ndk-build command needs an argument called NDK_DEBUG=1 (as seen in https://software.intel.com/en-us/android/articles/how-to-test-and-debug-ndk-based-android-applications).
This will add two additional files: gdbserver and gdb.setup
But since the plugin always adds the name at the end (either target or the artifact id), the NDK_DEBUG parameter is ignored, and the files are not installed, hence the app is not debuggable.

**Comment by himamis** [comment]
The files are also intalled if the AndroidManifest contains android:debuggable="true". But adding the target again ignores this. Maybe this is a bug of the ndk-build command...

**Comment by johanlindquist** [comment]
Hi,

Have you tried setting the ndkBuildAdditionalCommandline configuration parameter?

Also, the NDK plugin was split out from the SDK plugin as a separate plugin entirely - have you tried to use this yet?

Thanks,

Johan

**Comment by himamis** [comment]
Hi Johan,

Yes, I've tried using that, but the last parameter of the ndk-build command is always the target
```
configureAdditionalCommands( commands );

// If a build target is specified, tag that onto the command line as the very last of the parameters
if ( target != null )
{
    commands.add( target );
}
else /*if ( Const.ArtifactType.NATIVE_IMPLEMENTATION_ARCHIVE.equals( project.getPackaging() ) )*/
{
    commands.add( project.getArtifactId() );
}
```
I've seen the separate plugin, but it seemed to be abandoned.

Maybe adding the parameter -C before the target will solve this issuse, as seen in the [docs](http://brian.io/android-ndk-r10c-docs/Programmers_Guide/html/md_3__key__topics__building__chapter_1-section_8_ndk-build.html), under the Options section.

Cheers,
 Balázs

**Comment by johanlindquist** [comment]
Not abandoned, merely sleeping a little :) The intention is to remove all NDK related code (compilation) from this plugin. 

I don't see an immediate issue with the target being the last parameter - are you saying that ndk-build needs  NDK_DEBUG=1 to be last on the command line? 

Thanks,

Johan

**Comment by himamis** [comment]
What I meant is, that according to the docs mentioned above, the target option of the ndk-build command is specified with `-C`.
And also my experience shows that if I add the parameter `NDK_DEBUG=1` and after that specify the target without `-C`, the build will be a "normal" build, instead of a "debug" build.

**Comment by himamis** [comment]
I can test this behaviour, fix the issue, and do a pull request on the ndk plugin later this week, maybe next, if it fits you. :)

**Comment by johanlindquist** [comment]
But the `-C` parameter should be used for specifying a project directory, not the Makefile target if I am not mistaken?  E.g. execute the build in the directory specified by the -C parameter?

**Comment by himamis** [comment]
Yes, I see. You're probably right. But then there's no argument specified in the docs for the build target. So the code specified in the previous comment is not needed. (?)

**Comment by johanlindquist** [comment]
If you try `ndk-build -help` you'll see a better overview of the command line parameters.

is essentially:   `ndk-build [options] [target]`

So, the last command is indeed the target in the Makefile.  I will check why the `NDK_DEBUG=1` is not biting but if you could do the same, that would be great.

**Comment by himamis** [comment]
Alright, sounds good. :+1:

**Comment by johanlindquist** [comment]
So, it seems that running ndk-build NDK_DEBUG=1 V=1 is working fine - when you say "are not installed" above, do you mean they are not used in the APK?

**Comment by himamis** [comment]
Yes

**Comment by himamis** [comment]
Try issuing ndk-build NDK_DEBUG=1 V=1 <target> command.

**Comment by johanlindquist** [comment]
So, thinking out loud - i guess the NDK plugin would have to (potentially) wrap those two files up and install them in the repo - then when the APK Mojo runs, look for them and include them in the APK.  But, only if the APK mojo is building a debug APK.  Convoluted to say the least :)

**Comment by himamis** [comment]
Well, thinking in code, the NDK plugin just needs to be fixed, so that the ndk-build command actually copies the files `gdbserver` and `gdb.setup` to libs/armeabi(x86). The APK Mojo should include in the APK the .so files, and the two files mentioned above, iff available.

**Comment by johanlindquist** [comment]
Ok, the problem stems from always adding the target to the command line - the ndk-build command will not install anything when you do that.  Will have to have a think about this.

In the mean time, please give the android-ndk-maven-plugin another spin - all NDK compile functionality will soon be removed from the android-maven-plugin.

**Comment by himamis** [comment]
Okay, thanks!

**Comment by mosabua** [comment]
Closing since NDK mojo was removed from this plugin
