### ISSUE TITLE
Wrong string resource generation when using resourceOverlayDirectory with strings.xml

### ISSUE THREAD

**Issue by j3nsm4n** [simpligility/android-maven-plugin#573]
Encountered some strange behaviour with the maven-android-plugin v4.1.0 and string resources generation.
We have defined a resourceOverlayDirectory to override some resources in the applications original 'res' folder. The resourceOverlayDirectory contains a strings.xml file in the values directory. When we've build our apk with maven, the generated string resources file seems to point to the wrong string values, because wrong string values are placed on the views. 
Is there something known what could cause this issue?

**Comment by Shusshu** [comment]
Maybe @xcolwell can say something about it even though he hasn't worked on AMP 4.x

Maybe related: https://github.com/simpligility/android-maven-plugin/issues/417

@j3nsm4n could you look deeper into the code and see if any adjustments needs to be made?

**Comment by xcolwell** [comment]
@shusshu I suggest trying the latest 3.x version if possible and seeing if the unwanted behavior happens there. I believe 4.x introduced a different behavior than 3.x with resource overlays.

**Comment by mosabua** [comment]
Fixed with linked PR
