### ISSUE TITLE
mvn clean source:jar and javadoc:jar doesn't work with AAR library

### ISSUE THREAD

**Issue by tprochazka** [simpligility/android-maven-plugin#577]
AAR is unpacked during generate-sources, so possible workaround is:
**mvn generate-sources source:jar**

But **mvn clean generate-sources source:jar javadoc:jar deploy** doesn't work because generated R.java is included in pah for javadoc create and R.java contain many javadoc errors.

So only possible workaround which I found is split building to two commands:

```
mvn clean package
mvn source:jar javadoc:jar deploy
```

Related discussion:
https://groups.google.com/forum/#!searchin/maven-android-developers/javadoc$3Ajar%7Csort:relevance/maven-android-developers/F2VpHuTjOBM/0wFmkDsk5lcJ

**Comment by mosabua** [comment]
Closing old issue as cleanup
