### ISSUE TITLE
Perform 4.1.1 release

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-maven-plugin#579]
Release done fy @simpligility/android-maven-plugins-core-committers 

Sync to central should be done shortly. 

Site deployment ongoing now.

Release announcement will be sent tomorrow.

**Comment by william-ferguson-au** [comment]
+1 good stuff
ᐧ

**Comment by mosabua** [comment]
Site is live now at http://simpligility.github.io/android-maven-plugin/

**Comment by Shusshu** [comment]
great!

**Comment by mosabua** [comment]
Email to Android Maven Dev List, Maven users and Maven dev list done. G+ post as well.
