### ISSUE TITLE
Confusing documentation of "destinationAndroidManifest"

### ISSUE THREAD

**Issue by mstevens83** [simpligility/android-maven-plugin#581]
Does anyone agree with me that this is rather confusing?
> **destinationManifestFile**:
> Source AndroidManifest.xml file to copy into the destinationManifestFile location.

If you ask me it is kind of a cyclical definition...
Shouldn't it be something like this instead?:
> **destinationManifestFile**:
> Location to which the source AndroidManifest.xml file (as specified by the **androidManifestFile** parameter) will be copied.

Perhaps I'm misinterpreting things though...
But if you guys agree I'll submit a PR with amended javadoc.

The definition in question appears here: http://simpligility.github.io/android-maven-plugin/apk-mojo.html#destinationManifestFile
Javadoc src: https://github.com/simpligility/android-maven-plugin/blob/master/src/main/java/com/jayway/maven/plugins/android/AbstractAndroidMojo.java#L227

**Comment by Shusshu** [comment]
Yes you are right.
A PR is welcome.

Thanks for spotting it!
