### ISSUE TITLE
support-v4:21.0.3 causes Proguard warnings due to dependencies on its internal-lib

### ISSUE THREAD

**Issue by william-ferguson-au** [simpligility/android-maven-plugin#583]
com.android.support:support-v4:21.0.3 (and I suspect others) contains classes that have dependencies on classes in it's *internal* library (libs\internal_impl-21.0.3.jar

This causes Proguard to be unable to find those references generating **lots** of warnings like:

`Warning: android.support.v4.widget.SearchViewCompat$SearchViewCompatHoneycombImpl: can't find referenced class android.support.v4.widget.SearchViewCompatHoneycomb`

I *think* that using `dontwarn com.android.support.v4.**` is safe, and if so then we need to include some doco noting that this is a requirement to work around the insanity.

Alternatively we need to add the internal libs to the Proguard library path. Not sure how much work is involved.

WDYT?

**Comment by Shusshu** [comment]
oh god!......

**Comment by Shusshu** [comment]
We have to thank google for that .....

I think it's safe also to use dontwarn and +1 for the doc.

**Comment by william-ferguson-au** [comment]
Yes, 'dontwarn' is safe.

But it means that Proguard won't be abel to trim away or obfuscate any
internal lib classes. So it will be up to dex to do any trimming.
ᐧ

On Thu, Feb 12, 2015 at 6:54 AM, Benoit Billington <notifications@github.com

**Comment by william-ferguson-au** [comment]
Sorry, this is not an issue.
You just need to configure AMP with `<includeLibsJarsFromAar>true</includeLibsJarsFromAar>`

**Comment by Shusshu** [comment]
Should "includeLibsJarsFromAar" be set to true by default?

**Comment by william-ferguson-au** [comment]
With the way that the environment is evolving then perhaps so.

What are the downsides?

**Comment by Shusshu** [comment]
downside: follow a bad practice ;) but in order to keep it simple for android maven users it would be better as true I guess

**Comment by william-ferguson-au** [comment]
That's what I'm thinking too.
You want to make the change?

ᐧ

**Comment by Shusshu** [comment]
I can do it yep or you can but since I'm back now and I have some time I'll just do it :)
