### ISSUE TITLE
Android Studio does not properly import project using plugin version 4.0.0+

### ISSUE THREAD

**Issue by cameocoder** [simpligility/android-maven-plugin#587]
I'm not sure if this is an Android Studio problem or an android-maven-plugin problem.

First of all I will say that I can build, deploy and run from the command line just fine with all versions of android-maven-plugin up to and including 4.1.1.  The problem is that as soon as I use version 4.0.0, Android Studio does not properly import my project. 

I can build with versions up to com.jayway.maven.plugins.android.generation2:4.0.0-rc.2 and import into Android Studio.  As soon as I change the packaging to com.simpligility.maven.plugins:4.0.0 then Android Studio fails to auto-configure the project  and does not correctly configure paths, facets or create modules for apklibs.

I have a multi-module project which contains modules for application, Robotium tests and UIAutomator tests.  The application has dependencies on 3 apklibs.

When importing into Android Studio using com.jayway.maven.plugins.android.generation2 plugin versions, the modules are automatically created. Android Facets are added and paths are configured.  Dependency apklibs are also detected and automatically added as modules with dependencies added in the application.  Basically the project import "just works"

When I use com.simpligility.maven.plugins:4.0.0. The project import only creates the highest level modules.  The Facets are not created, paths are not configured properly and the apklibs have to be manually created as modules with manual dependencies added.  It is very difficult to manually configure and get the build working.

**Comment by william-ferguson-au** [comment]
Sorry. I can't comment on this as I don't use Android Studio (I use
Intellij-14) and I have long since switched from using apklib to aar.
ᐧ

**Comment by mosabua** [comment]
If it works on the commandline I would suggest to contact the AndroidStudio team and create a bug and get it fixed. You can also try IntellIJ .. it might fix it, if it has better Maven support.

**Comment by cameocoder** [comment]
We can build our product from command line with aar files as well but android studio still does not configure the project properly with plugin 4.0.0+ and we have a lot of problems building.  We downgraded the android-maven-plugin version and switched back to apklibs because that was a setup where everything worked smoothly.

**Comment by william-ferguson-au** [comment]
As Manfred said, you need to take this up with the Android Studio team.
ᐧ

**Comment by cameocoder** [comment]
This is fixed in IDEA but not in Android Studio yet:
https://youtrack.jetbrains.com/issue/IDEA-132893

I believe a sync with Intellij is on the roadmap for Android Studio 1.2

**Comment by mosabua** [comment]
Hahah.. one more reason to just use IntelliJ and not bother with studio.

**Comment by william-ferguson-au** [comment]
+1 ;-)

ᐧ

**Comment by mvysny** [comment]
Bad news: I was dicussing this bug: https://youtrack.jetbrains.com/issue/IDEA-139209 when I received information from Intellij's Serge Baranov, quote: "I can recommend you to convert your Android projects from Maven to Gradle, as we are not actively maintaining Maven/Android integration at the moment and fixing these issues may take a lot of time. You will also benefit in long term perspective as Gradle/Android is actively supported by Google and you will get new features and bug fixes sooner."
So, if I understand correctly, Google will not fix Maven Simpliginity integration in Studio; Intellij's Vladislav Soroka will fix them, but with low priority.

**Comment by william-ferguson-au** [comment]
Is that quote from Serge public?

If that's true then for for first time in 4 years I won't bother renewing
my IntelliJ licence.


[image: photo]
*William Ferguson*
Founder and CEO, XandarMob
m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>

**Comment by mvysny** [comment]
It is not yet public, we were just discussing stuff and this came up. I will ask Serge for permission, please wait.

**Comment by mvysny** [comment]
Okay, Serge allowed me to go public. He also added: "We'll try to address Maven integration specific issues in IDEA. Issues that are not specific to Maven integration and also occur in Gradle projects should be reported to Google (especially if they are also reproducible in Android Studio)."

**Comment by mosabua** [comment]
To be honest I am not that surprised ...

**Comment by william-ferguson-au** [comment]
:-( me either.

If I thought Gradle was going to easily be able to do my builds I'd
considering switching. But Gradle feels like a step back towards Ant and
complicated build config that requires an ever increasing maintenance
budget.

But it kid of feels we are out here on our own now.
Are we just pissing into the wind?

**Comment by mosabua** [comment]
I don't think so. Maven is still by far the most widely used build system in the JVM ecosystem and as such also in  large enterprises. That is a HUGE user base of Android developers or developers that do Android as well as other stuff.

The Andmore project and many, many enterprise users are proof that there is a need. For what its worth even Google is using the Android Maven Plugin internally for various projects. 

I don't think that Jetbrains will ultimately be able to afford to drop Maven support .. it just takes one or two large customers to be demanding better support. So if you work in one of those enterprises or in general if you have a IntelliJ license.. tell them about your concerns.

**Comment by mvysny** [comment]
Actually Gradle is not *that* bad as Ant - they employ the convention-over-configuration principle, so it's kinda halfway between Maven and Ant, with interesting features. For example, I'm using this lovely configuration:

    releaseCompile 'org.slf4j:slf4j-android:1.7.12'
    debugCompile 'org.slf4j:slf4j-android:1.6.1-RC1'

Which uses SLF4j 1.6.1-RC1 for development (when the app is run from Android Studio), which logs debug messages; SLF4j 1.7.12 is used for release APK which does not log debug messages (when buit with ./gradlew clean build)
I have also configured gradle to use the same sign key for debug and release - no more stupid "key changed, you need to reinstall" messages when I move to develop on another computer, with different debug key.
I know it's weird to promote Gradle here, and I apologize - I just wanted to share my experience.

**Comment by spyhunter99** [comment]
damn.

For me, there's a HUGE performance benefit to running maven+android over
gradle. It literally is a 50% time reduction using maven vs gradle, clean
install/clean build. Half!


10+ years of well supported plugins for everything under the sun for maven
and the site plugin is killer. I'm all for newer, better'er things, but..if
it's not broke.

**Comment by spyhunter99** [comment]
And i'm not endorsing (nor is my employer) either build tool (nor
intellij/android studio). Everything has their pro's and con's. I just
don't like before forced to use something in order to be somewhat
productive. I'd much rather it be an active, fair and balance choice
amongst alternatives.

**Comment by mosabua** [comment]
I agree @spyhunter99  ... all we can do it keep improving Maven and the Android Maven Plugin and work with all other communities including Google, Jetbrains, Eclipse and so on. And I intend to do that for a long while yet and continue to make it rock. There are still a LOT of things we can improve and its mostly a lack of time to get it all done ;-)

**Comment by mvysny** [comment]
Yes, Gradle is slow. However, I learned to enable the Gradle daemon, which eats 1 gig of RAM but it speeds up things quite a bit. And, for me, IDEA's Maven support is kind of broken: every time I modify poms, IDEA reverts the project to point to android.jar with no sources, which is really annoying. Right now a new Gradle plugin is out, which auto-converts vector drawables into all kinds of PNGs, for backward compatibility - this is great (of course it is buggy: Android fails to render SVGs with numbers in scientific notation. Android is one big ball of bug). Yet, I imagine that this will not appear in IDEA's support for maven plugin for quite some time.
I agree that this is IDEA's fault. Yet, I am tired of banging my head against a wall, I will not purchase IDEA anymore but I will move to Gradle, simply because it's less PITA :(

**Comment by Shusshu** [comment]
It could be trivial to bring svg to png support if it's in the android library
