### ISSUE TITLE
release:prepare and release:perform

### ISSUE THREAD

**Issue by tprochazka** [simpligility/android-maven-plugin#590]
I tested 4.1.0 with the library release plugin and I found one weird think.
If you have -SNAPSHOT dependencies in the project release plugin will allow you change the dependencies interactively . But from the 4.x version with the AAR support it double every AAR dependency. It ask me first time for regular dependency and then repeat it with _extracted suffix.
It looks like plugin modified original dependencies from the project

Then release:perform doesn't work because of javadoc, but it is different problem.

**Comment by william-ferguson-au** [comment]
This is fixed in 4.1.1 which removed the _extracted dependency.
