### ISSUE TITLE
Add JavaDoc to PublishApkMojo and co.

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#591]
These mojos lack JavaDoc, hence the [documentation](http://simpligility.github.io/android-maven-plugin/publish-apk-mojo.html) is also incomplete.

**Comment by Shusshu** [comment]
Could also add the link to the site documentation
http://simpligility.github.io/android-maven-plugin/playstore-publisher.html
and google publisher doc: https://developers.google.com/android-publisher/

**Comment by mosabua** [comment]
Closing old issue since it wont be worked on at this stage anyway.
