### ISSUE TITLE
Plugin execution not covered by lifecycle configuration: 

### ISSUE THREAD

**Issue by elioth010** [simpligility/android-maven-plugin#592]
Maven lauch this error on add the plugin 
Plugin execution not covered by lifecycle configuration: com.simpligility.maven.plugins:android-maven-plugin:4.0.0:emma (execution: default-emma, phase: process-classes)
my pom have this:

```
<build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.simpligility.maven.plugins</groupId>

                    <artifactId>android-maven-plugin</artifactId>
                    <version>${it-plugin.version}</version>
                    <extensions>true</extensions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>

                <artifactId>android-maven-plugin</artifactId>
                <configuration>
                    <sdk>
                        <platform>19</platform>
                    </sdk>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

I'm trying to add the appcompat source library using de maven-android-sdk-deployer but i've had not luck.

Thanks for your help.

**Comment by WonderCsabo** [comment]
Not Maven, but the Maven Eclipse plugin (m2e) shows you this error. If you are not using emma, you can just ignore the execution by using the quick fix.

**Comment by mosabua** [comment]
Closing old issue since it wont be worked on at this stage anyway.
