### ISSUE TITLE
Switch default proguard config file to `proguard-project.txt`

### ISSUE THREAD

**Issue by guersam** [simpligility/android-maven-plugin#595]
Since ADT 17, the default project proguard config file has changed from `proguard.cfg` to `proguard-project.txt`. [1] As it's been almost 3 years, it would be ok to change the default filename in this plugin. Can it be done in a backward-compatible way?

[1] http://tools.android.com/recent/proguardimprovements

**Comment by mosabua** [comment]
You could provide a pull request that changes the default value, but also does a check for the old value and logs a warning and maybe even proceeds to pull the old one in if there is none found in the new location. And maybe fails if there is a file in both paths.

**Comment by mosabua** [comment]
Closing old issue since it wont be worked on at this stage anyway.
