### ISSUE TITLE
Problems when trying to import the test-jar into my instrumentation module

### ISSUE THREAD

**Issue by athkalia** [simpligility/android-maven-plugin#596]
Hello,

I have a separate instrumentation (using espresso) module and in my instrumentation pom.xml i have a dependency on the application I am testing like this :

```
 <dependency>
        <groupId>com.test<groupId>
        <artifactId>application</artifactId>
        <scope>provided</scope>
        <type>apk</type>
    </dependency>
```

(can you please confirm that I no longer need to add anything else in like the .jar dependency before i carry on - thank you)

Now, the problem arises when I try to add a dependency on the test-jar of the application created by the maven jar plugin:

```
<plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>2.5</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>test-jar</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
```

The dependency looks like this: 

```
   <dependency>
        <groupId>com.test<groupId>
        <artifactId>application</artifactId>
        <type>test-jar</type>
    </dependency>
```

When I try this I initially get an error message looking like this:

```
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.1.1:generate-sources (default-generate-sources) on project espresso: AndroidManifest.xml file wasn't found in next place: C:\Users\use\Desktop\intelliJ projects\test\espresso\target\unpacked-libs\cgag_google-play-services_22.0.0 -> [Help 1]
```

which is weird, just adding that test-jar dependency made it search for the manifest and fail.
(if i remove that test-jar dependency it works ok)

After a bit of searching, I tried excluding that google play service artifact from the dependency like this 

```
 <dependency>
        <groupId>com.test</groupId>
        <artifactId>application</artifactId>
        <type>test-jar</type>
        <exclusions>
            <exclusion>
                <groupId>com.google.android.gms</groupId>
                <artifactId>google-play-services</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
```

and then I started seeing exceptions like the following one:

```
    java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
```

Is this supposed to work? The reason I am doing this is because I want to reuse in my instrumentation tests all the utility classes that sit in the application module src/test/ folder that are at the moment only used by Robolectric.

**Comment by mosabua** [comment]
Closing old issue since it wont be worked on at this stage anyway.
