### ISSUE TITLE
Warn/exclude Android incompatible dependencies

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#597]
There are some dependencies which are provided by the Android platform at runtime, and cause really nasty problems if the user wants new versions as dependencies, since Android will use the platform-provided old ones. This is described in detail [here](http://simpligility.github.io/android-maven-plugin/shaded-commons-codec.html).

I think we can help the user like the [Gradle plugin does](https://android.googlesource.com/platform/tools/base/+/master/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/dependency/DependencyChecker.java), and warn about these dependencies, or even exclude them from the tree and force shading. Personally i would go with just the warning.

**Comment by Shusshu** [comment]
Sounds like a good idea to me.
Would you like to do a pull request with this warning ?

**Comment by WonderCsabo** [comment]
Yeah, but i am unsure about the implementation:

* how can i bind to a lifecycle phase (and which one), so it gets automatically executed
* how can i get the dependency tree
* others?

I am pretty sure both of these have examples in this plugin, can you point me to those?

**Comment by Shusshu** [comment]
When do you want to display the warning? It could be done either in the LifeCycleParticipant which is the first thing to get called or during the Compile phase...

You can check the GenerateSourceMojo or others to see how to get the dependency tree, there is a helper class to help you select what you want.

**Comment by WonderCsabo** [comment]
Thanks! I am totally clueless where we should show this warning. What is the `LifeCycleParticipant`? I searched for it in the codebase but i only found a JavaDoc comment.

**Comment by WonderCsabo** [comment]
@Shusshu can you add more detail?

**Comment by WonderCsabo** [comment]
@mosabua maybe you know much more about those then me? :)

**Comment by Shusshu** [comment]
Sorry I forgot to answer.

You can check this class: https://github.com/simpligility/android-maven-plugin/blob/master/src/main/java/com/jayway/maven/plugins/android/phase_prebuild/ClasspathModifierLifecycleParticipant.java

**Comment by WonderCsabo** [comment]
Thanks. The `afterProjectsRead` method is the interesting part, am i right? 
There are some classloader changes in that code, why that is needed?

**Comment by Shusshu** [comment]
Yes that's the method but I wouldn't know about the classloader changes as I haven't looked at it.

**Comment by mosabua** [comment]
This stuff ensures that aar packages and their transitive dependencies are found on the classpath by other plugins (e.g. the compiler plugin).

**Comment by WonderCsabo** [comment]
Thanks for the answers guys, i think start to understand. I will implement this soon, but i will ask for a patient review because

![i-have-no-idea-what-im-doing-1 1](https://cloud.githubusercontent.com/assets/480485/6755120/3d02d4a6-cf21-11e4-83fe-7c7d1ec254c0.jpg)

:smile:

**Comment by mosabua** [comment]
None of us do ;-)
