### ISSUE TITLE
 "unpacked-libs" always in "target"

### ISSUE THREAD

**Issue by barisinanc** [simpligility/android-maven-plugin#599]
Issue #439 is up again in 4.1.0. 

 project.build.directory is modified in profile but unpacked-libs folder always created in target folder.

I found a workaround by setting plugin configuration in profile is like below:

```
                <plugin>
                                    <groupId>com.simpligility.maven.plugins</groupId>
                                    <artifactId>android-maven-plugin</artifactId>
                                    <version>4.1.0</version>
                                    <extensions>true</extensions>
                                    <configuration>
                                            <unpackedLibsFolder>${project.build.directory}</unpackedLibsFolder>
                                    </configuration>
                </plugin>
```

**Comment by mosabua** [comment]
Configuring it different in a profile seem to be an invalid approach. Does it work if you configure it in the project itself?

**Comment by barisinanc** [comment]
Sorry for late answer. It is working when I configure this from project itself. It is only seen when configuration done in profile.

**Comment by mosabua** [comment]
This might have to do with the UnpackedLibHelper class or the default parameter and usage in ClasspathModifierLifecycleParticipant and AbstractAndroidMojo. Can you try to debug this and send a pull request?

**Comment by william-ferguson-au** [comment]
How are you modifying the project.build.directory in your profile?
And (just curious) why?

ᐧ

**Comment by mosabua** [comment]
Closing old issue since it wont be worked on at this stage anyway.
