### ISSUE TITLE
publish-listing uses default encoding when reading text files

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#601]
I have listing text files stored with UTF-8 encoding. However, it seems the [mojo uses the platform default encoding](https://github.com/simpligility/android-maven-plugin/blob/b007065ff73f9d3147b396e21d5d82f6b2c876cc/src/main/java/com/jayway/maven/plugins/android/AbstractPublisherMojo.java#L71) (which is not UTF-8 on Windows) when reading those files. This results in badly interpreted characters get uploaded to the play store.

I think we should either use a configurable property for this, or just hardcode the defacto standard UTF-8.

What do you guys think?

**Comment by mosabua** [comment]
The mojo should probably use the soruce encoding configured in the pom. Want to send a pull request?

**Comment by WonderCsabo** [comment]
Already on it. `project.build.sourceEncoding` ?

**Comment by mosabua** [comment]
I would think so

**Comment by mosabua** [comment]
I would consider the listing a source file .. right?

**Comment by mosabua** [comment]
Just like src/main/resources and others.

**Comment by WonderCsabo** [comment]
Actually i wanted to write that in the OP, i agree with you.

**Comment by WonderCsabo** [comment]
Implemented.
