### ISSUE TITLE
Remove RedundantThrows check

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#609]
I constantly get Exceptions in Eclipse:

> cannot initialize module TreeWalker - Unable to instantiate RedundantThrows

It [seems](http://stackoverflow.com/a/27919636/747412) this check was removed from Checkstyle, that is why the Eclipse Checkstyle plugin always complaining about it. I think we should get rid of this check.

**Comment by mosabua** [comment]
https://github.com/simpligility/android-maven-plugin/commit/715090f2d83d54c8f053e3ad69acc76ca8d1fdfc

**Comment by WonderCsabo** [comment]
@mosabua we should also upgrade to the latest Checkstyle, so the it will be consistent with the Eclipse one.
