### ISSUE TITLE
Proguard config from aar library (consumerProguardFiles)

### ISSUE THREAD

**Issue by hameno** [simpligility/android-maven-plugin#611]
I just read https://plus.google.com/+IanLake/posts/1HfDuFFkMXG and asked myself, if the android-maven-plugin supports this. Did not find any evidence, so I'm creating this issue / feature request.

**Comment by mosabua** [comment]
We are already consuming AAR packages and all their contents. This feature request would require us to pull the proguard config and somehow merge it with the project one. I am not sure how Gradle does that but I would think it probably is just a simple append and not some clever merge. Probably causes issues in many cases but is a interesting idea. 

I would love to have a look at a pull request from you that implements this @hameno

**Comment by hameno** [comment]
I'm not sure how to do this. I looked at ProguardMojo, but don't know how to get all the aar dependencies and look for the proguard files.

**Comment by hameno** [comment]
BTW your codestyle is very strange, is there a config file for IntelliJ anywhere?

**Comment by hameno** [comment]
I've implemented the consume part of this feature.

**Comment by hameno** [comment]
This should now be resolved
