### ISSUE TITLE
manifestProviderAuthorities not working

### ISSUE THREAD

**Issue by athkalia** [simpligility/android-maven-plugin#613]
Hello, 

you have deprecated the manifest-update goal, and replaced it with the new manifest-merger goal.
However, I can't find the manifestProviderAuthorities functionality  to rename authorities in the new goal. If I use the old one, it doesn't work as you seem to have removed that goal from binding automatically to the "process-resources" maven phase. If I add it on my own with 

                <executions>
                        <execution>
                            <id>run manifest update</id>
                            <goals>
                                <goal>manifest-update</goal>
                            </goals>
                            <phase>process-resources</phase>
                        </execution>
                    </executions>

then the manifestProviderAuthorities  works just fine. So it there a way to do this with the new manifest-merger goal? If not can you keep the old manifest-update goal to run on it's own till you completely migrate this functionality ?

**Comment by Shusshu** [comment]
To my knowledge the Manifest update mojo was never triggered automatically without specifying an execution...
The manifest update mojo will not be removed soon so you can continue using it.

You can check the official doc of the manifest merger from google:
http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger#TOC-Generic-description-of-merging-strategies

Maybe there is a way to achieve what you want. 
If it does require modification to the ManifestMergerMojo feel free to make a pull request and I will include it.

**Comment by athkalia** [comment]
Okay, no worries. I just saw that in the goal description of the update (http://simpligility.github.io/android-maven-plugin/manifest-update-mojo.html) it says: 
"Binds by default to the lifecycle phase: process-resources."

For now I'll stick with the deprecated goal, it works just fine. Thanks for the input.

**Comment by Shusshu** [comment]
Maybe that works:
http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger#TOC-Placeholder-support

**Comment by Shusshu** [comment]
Would you care telling us what's your use case ?

**Comment by athkalia** [comment]
My use case it to rename the authorities of my app so that I can install the same application on the same phone more than once (e.g. dev application, beta app and live app). The old update works just fine for now. Once I get some time I may start investigating to see if there's a way to do the same thing with the manifest-merger goal.
Thanks
