### ISSUE TITLE
Release 4.2.0

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-maven-plugin#615]

**Comment by mosabua** [comment]
I would like to get this going as well https://github.com/simpligility/android-maven-plugin/tree/sdk-upgrade but havent figured out the new constructor usage in the ManifestMergerMojo... so currently it doesnt compile.

**Comment by mosabua** [comment]
Maybe we can release 4.2.0 and then worry about the SDK upgrade..

**Comment by Shusshu** [comment]
I'm looking into the SDK changes...
The android tools team is always nice......... https://android.googlesource.com/platform/tools/base/+/abd4373927b84ee2a4f48c78b3dd048702daa634

**Comment by Shusshu** [comment]
There we go it is working (tested on only 1 case so please have a go at it)

https://github.com/simpligility/android-maven-plugin/tree/sdk-upgrade

**Comment by Shusshu** [comment]
You might want to move the new classes around a bit.. Didn't think of a place to put them...
