### ISSUE TITLE
Migrate rest of Google code site 

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-maven-plugin#616]
Google Code is going to be switched off. We need to migrate whatever we want to keep off it somehow. I think this only is a few more wiki pages and the old changelog/release notes. 

All of that should go into a various asciidoc documents that are part of the site.

**Comment by Shusshu** [comment]
Well done @mosabua

**Comment by mosabua** [comment]
Thanks. I guess I can close this now ;-)
