### ISSUE TITLE
FileNotFound when no classes.jar inside aar

### ISSUE THREAD

**Issue by michalwos** [simpligility/android-maven-plugin#618]
[ERROR] Error generating BuildConfig 
java.io.FileNotFoundException: .../target/unpacked-libs/cgag_play-services_7.0.0/classes.jar (No such file or directory)

**Comment by mosabua** [comment]
This is not enough information to tell what you are trying to report. Please see http://simpligility.github.io/android-maven-plugin/report-issue.html and reopen with more details, if applicable.
