### ISSUE TITLE
can't build library jar that depends on support-v4 aar

### ISSUE THREAD

**Issue by adennie** [simpligility/android-maven-plugin#620]
I have a maven project that produces a JAR artifact and depends on the support-v4 library.

I've tried the following dependency

    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>support-v4</artifactId>
      <version>22.0.0</version>
      <type>aar</type>
    </dependency>

which was installed from the SDK's embedded repo to my .m2 repo by maven-android-sdk-deployer.

However, when I try to build from the command line, I get errors like "package android.support.v4.app does not exist".

I cloned android-maven-plugin and modified the support4demos test project to use this same dependency, and it builds.  Notably, it is an APK project, not a JAR project.  But I also noticed that during the build, it performed:

[INFO] --- android-maven-plugin:4.0.0:generate-sources (default-generate-sources) @ support4demos ---
[INFO] Extracting libs
[INFO] Extracting aar support-v4...
[INFO] Generating R file for com.android.support:support4demos:apk:1.0.0-SNAPSHOT
[INFO] Adding R gen folder to compile classpath: C:\Users\Andy\Dev\tools\android-maven-plugin\src\test\projects\support4demos\target\generated-sources\r
[INFO] Skip BuildConfig.java generation for com.android.support support-v4
[INFO] Adding AIDL gen folder to compile classpath: C:\Users\Andy\Dev\tools\android-maven-plugin\src\test\projects\support4demos\target\generated-sources\aidl

When I try to build my JAR project, I don't see any step like that.  I tried manually running "mvn android:generate-sources" but it still didn't process the support-v4 jar.

Any advice?

**Comment by william-ferguson-au** [comment]
It sounds like the ClasspathModifierLifecyclePaticipany is not being
involved for a non APK project.

**Comment by mosabua** [comment]
Imho it should not be invoked either. The Android Maven Plugin is not supposed to be used to created JAR artifacts. Use a packaging we support (aar, apk) instead. Jar packaging is done by the Maven Jar Plugin..

**Comment by adennie** [comment]
Just commenting for others who may come here later... indeed, changing my artifact type to aar resolved the issue.  It hadn't occurred to me to make it an aar since it contains no resources.
