### ISSUE TITLE
Support the Testing Support Library

### ISSUE THREAD

**Issue by secondsun** [simpligility/android-maven-plugin#623]
So we (humanity) now have Google official JUnit4 support for Android! (see Testing Support Library).  Unfortunately AndroidTestFinder does not look for classes annotated with the Test Support annotations.  Instead it looks for descendants of the old testing classes.  It doesn't find any (because they are annotation based) and thus poops out.

I propose (and volunteer to) enhance the AndroidTestFinder class to check for annotations if the instrumentationTestRunner is set to "android.support.test.runner.AndroidJUnitRunner".

Thoughts?

**Comment by mosabua** [comment]
I would love that! Ideally with an example project as well. Wdyt @simpligility/android-maven-plugins-core-committers

**Comment by Shusshu** [comment]
Yes we have to support it!

**Comment by secondsun** [comment]
A very initial hack https://github.com/secondsun/maven-android-plugin/tree/Junit4TestRunner
Will add automated tests later, but here is a sample project using it : https://github.com/secondsun/aerogear-android-pipe/tree/Junit4
