### ISSUE TITLE
cant use the com.android.support library in the project

### ISSUE THREAD

**Issue by mohsenht** [simpligility/android-maven-plugin#624]
hi everybody

I add below dependency in my project and it wont copy to the unpack_lib directory of my project and get this error "error: error reading C:\Users\htaheri\Desktop\dialog material design\gs-maven-android-master\complete\target\unpacked-libs\cas_recyclerview-v7_21.0.3\classes.jar; error in opening zip file"

    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>recyclerview-v7</artifactId>
      <version>21.0.3</version>
      <type>aar</type>
      <scope>runtime</scope>
    </dependency>

could anyone help me plz?

**Comment by william-ferguson-au** [comment]
Yes you can. Proof or it didn't happen

**Comment by mohsenht** [comment]
when i set the scope of dependency to runtime maven plugin will produce the error.

**Comment by mohsenht** [comment]
This is my sample pom to proof ;)

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.hello</groupId>
    <artifactId>gs-maven-android</artifactId>
    <version>0.1.0</version>
    <packaging>apk</packaging>

    <properties>
        
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.android</groupId>
            <artifactId>android</artifactId>
            <version>4.1.1.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.3</version>
        </dependency>
        <dependency>
            <groupId>com.android.support</groupId>
            <artifactId>recyclerview-v7</artifactId>
            <version>21.0.3</version>
            <type>aar</type>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.simpligility.maven.plugins</groupId>

                    <artifactId>android-maven-plugin</artifactId>
                    <version>4.2.0</version>
                    <extensions>true</extensions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <configuration>
                    <sdk>
                        <platform>21</platform>
                    </sdk>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by william-ferguson-au** [comment]
Produce what error?
If it is a compilation error that would be because you marked the
dependency as 'runtime' instead of 'compile'

ᐧ

**Comment by mohsenht** [comment]
the instruction i used is:
mvn package

**Comment by william-ferguson-au** [comment]
Post the output from your build.

**Comment by mohsenht** [comment]
"C:\Program Files\Java\jdk1.7.0_45\bin\java" "-Dmaven.home=C:\Program Files\Apache Software Foundation\apache-maven-3.2.3" "-Dclassworlds.conf=C:\Program Files\Apache Software Foundation\apache-maven-3.2.3\bin\m2.conf" -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Apache Software Foundation\apache-maven-3.2.3\boot\plexus-classworlds-2.5.1.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.0 package
[INFO] Scanning for projects...
[WARNING] The following dependencies may conflict with the internal versions provided by the Android platform:
[org.khronos:opengl-api:jar:gl1.1-android-2.1_r1:provided, org.json:json:jar:20080701:provided, xerces:xmlParserAPIs:jar:2.6.2:provided, xpp3:xpp3:jar:1.1.4c:provided, org.apache.httpcomponents:httpclient:jar:4.0.1:provided, commons-logging:commons-logging:jar:1.1.1:provided]
It is recommended to shade these artifacts. You can read more about this here: http://simpligility.github.io/android-maven-plugin/shaded-commons-codec.html.
Alternatively, you can disable this warning with the'disableConflictingDependenciesWarning' parameter.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gs-maven-android 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- android-maven-plugin:4.2.0:generate-sources (default-generate-sources) @ gs-maven-android ---
[INFO] Manifest copied from C:\Users\htaheri\Desktop\gs-maven-android-master\complete\src\main\AndroidManifest.xml to C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\AndroidManifest.xml
[INFO] Extracting libs
[INFO] Generating R file for org.hello:gs-maven-android:apk:0.1.0
[INFO] Adding R gen folder to compile classpath: C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\generated-sources\r
[INFO] Adding AIDL gen folder to compile classpath: C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\generated-sources\aidl
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ gs-maven-android ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\htaheri\Desktop\gs-maven-android-master\complete\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ gs-maven-android ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\classes
[ERROR] error reading C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\unpacked-libs\cas_recyclerview-v7_21.0.3\classes.jar; zip file is empty
[ERROR] error reading C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\unpacked-libs\cas_recyclerview-v7_21.0.3\classes.jar; zip file is empty
[INFO] 
[INFO] --- android-maven-plugin:4.2.0:emma (default-emma) @ gs-maven-android ---
[INFO] 
[INFO] --- android-maven-plugin:4.2.0:proguard (default-proguard) @ gs-maven-android ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ gs-maven-android ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\htaheri\Desktop\gs-maven-android-master\complete\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ gs-maven-android ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ gs-maven-android ---
[INFO] No tests to run.
[INFO] 
[INFO] --- android-maven-plugin:4.2.0:dex (default-dex) @ gs-maven-android ---
[INFO] Convert classes to Dex : C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\classes.dex
[INFO] 
[INFO] UNEXPECTED TOP-LEVEL EXCEPTION:
[INFO] java.util.zip.ZipException: zip file is empty
[INFO] 	at java.util.zip.ZipFile.open(Native Method)
[INFO] 	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
[INFO] 	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
[INFO] 	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
[INFO] 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
[INFO] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[INFO] 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[INFO] 	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[INFO] 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[INFO] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[INFO] 	at com.android.dx.command.dexer.Main.run(Main.java:246)
[INFO] 	at com.android.dx.command.dexer.Main.main(Main.java:215)
[INFO] 	at com.android.dx.command.Main.main(Main.java:106)
[INFO] 1 error; aborting
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.147 s
[INFO] Finished at: 2015-04-28T17:04:19+04:30
[INFO] Final Memory: 26M/267M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.2.0:dex (default-dex) on project gs-maven-android: MojoExecutionException: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C ""C:\Program Files\Java\jdk1.7.0_45\jre\bin\java" -Xmx1024M -jar E:\Android\sdk\build-tools\21.1.2\lib\dx.jar --dex --output=C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\classes.dex C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\unpacked-libs\cas_recyclerview-v7_21.0.3\classes.jar C:\Users\htaheri\.m2\repository\joda-time\joda-time\2.3\joda-time-2.3.jar C:\Users\htaheri\Desktop\gs-maven-android-master\complete\target\classes", Result = 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by mohsenht** [comment]
if change the scope from runtime to compile it will be ok.

**Comment by mosabua** [comment]
The scope has to be compile since the library has to be embedded in the application.
