### ISSUE TITLE
How to package Android private libraries to classes.dex or apk

### ISSUE THREAD

**Issue by songwk** [simpligility/android-maven-plugin#628]
Hello All,
   I have a problem about how to use android-maven-plugin to package apk file. There are about 30 Android private libraries under "src\main\libs" in my project, I can build the project in Eclipse successfully, then find those jar files in decompiled classes.dex. However, if I use "mvn clean install" to create apk file, those jar files are not packaged to apk file, only source are included.

My question is how to use configurations of android-maven-plugin to include Android private libraries? 

Must I add them as dependencies to pom file?

**Comment by william-ferguson-au** [comment]
Yes. Your project dependencies need to be defined in your POM file.


ᐧ

**Comment by Shusshu** [comment]
You can add them to a "company" repository which would then be private to your company if you don't want to share them.
Or you can try finding those libs on maven central

**Comment by taojiangireland** [comment]
one way is add as a dependency.
Another way is unpacking all the jar files to the /target/classes folder(maven-dependency-plugin:unpack). And all the classes would be packed into classes.dex

**Comment by songwk** [comment]
Thank you all!
