### ISSUE TITLE
Regression : generated AIDL classes no longer passed to compiler

### ISSUE THREAD

**Issue by william-ferguson-au** [simpligility/android-maven-plugin#629]
In 4.0.1 classes generated from AIDL were passed to the compiler.
In 4.2.1 this doesn't happen so that the build breaks at compile time.

**Comment by william-ferguson-au** [comment]
It looks like this was introduced with #555 

Essentially what happens is that if your AIDL classes are in the old default location (ie src/main/java) then the AIDL is translated into Java classes and placed in target\generated-sources\aidl (just like before)

But those generated classes are no longer provided to the maven-compiler-plugin, so compilation fails with missing AIDL classes.

If you move the AIDL to src/main/aidl then compilation succeeds ans the classes are provided.

In both cases the AIDL classes are being generated to target\generates-sources\aidl.
And in both cases the AIDL gen folder ins being added to the compile classpath.

**Comment by mosabua** [comment]
So is there anything to do apart from documenting the correct setup?

**Comment by mosabua** [comment]
Do we need to get this into 4.2.1? I was gonna cut a release in the next few hours..

**Comment by william-ferguson-au** [comment]
It definitely needs to be documented because otherwise anyone migrating up
to 4.1.1 and beyond that has AIDL will spends hours scratching their heads
before telling us it is broken.

I'd like to know how the generated AIDL classes are being provided to the
compiler plugin. I couldn't find that anywhere. They don't seem to getting
picked up from the compiler source path. I would have expected that any
classes generated to target\generated-sources\aidl (where
target\generated-sources\aidl is one of the compiler source paths) would
get provided to the compiler plugin. But this is not happening and I can't
see why.
ᐧ

**Comment by william-ferguson-au** [comment]
So document but find out and fix why classes in compiler source path are
not being compiled.
ᐧ

**Comment by mosabua** [comment]
I cut 4.2.1 .. now we have time to figure this out and fix it and get 4.2.2 out the door after ;-)

**Comment by william-ferguson-au** [comment]
NP :-)
ᐧ

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
