### ISSUE TITLE
How does the dex consume the dependencies compiled by Java7

### ISSUE THREAD

**Issue by songwk** [simpligility/android-maven-plugin#630]
Hello All,

When I execute "mvn clean install" to make APK, I find there are some classes in jar files excluded by dex tool, this will cause a ClassNotFound exception in runtime. 

One article indicates that Android's dx tool, which converts Java classfiles to their Android equivalent, silently excludes classes that target Java 7 (their classfiles have a major version number of 51 and a minor version number of 0) from the generated classes.dex file.

So I tried to use maven3.1.1 and Maven 3.2.1 with both JDK 1.6 and 1.7 to test it in my local maven build environment, however, none of them include those classes.

My question is how can I use android-maven-plugin to solve such problem?
BTW, I touched android maven plugin recently, I did not find out the difference between "com.jayway.maven.plugins.android.generation2:android-maven-plugin" and "com.simpligility.maven.plugins:android-maven-plugin". If possible can you explain more?

Information in POM:
==========================================
    <properties>
        <android.api.version>19</android.api.version>
        <android.jar.version>4.4.2</android.jar.version>
        <android.zip.version>19_r02</android.zip.version>
        <android.sdk.tools.version>r21</android.sdk.tools.version>
        <android.maven.version>4.0.0-rc.2</android.maven.version>
        <android.sdk.path>${project.build.directory}/android-sdk-windows</android.sdk.path>
    </properties>

        <plugin>
          <groupId>com.jayway.maven.plugins.android.generation2</groupId>
          <artifactId>android-maven-plugin</artifactId>
          <version>4.0.0-rc.2</version>
          <extensions>true</extensions>
          <configuration>
            <sign>
              <debug>true</debug>
            </sign>
            <sdk>
              <path>C:\Users\wsong\git\com.mobile.platform.tool.companionappandroid\target/android-sdk-windows</path>
              <platform>19</platform>
            </sdk>
            <deleteConflictingFiles>true</deleteConflictingFiles>
            <undeployBeforeDeploy>true</undeployBeforeDeploy>
          </configuration>
        </plugin>

 		<dependency>
 			<groupId>com.google.zxing</groupId>
 			<artifactId>core</artifactId>
 			<version>3.0.0</version>
 			<type>jar</type>
 		</dependency>

The description is like this:
======================================================================
[INFO] --- android-maven-plugin:4.0.0-rc.2:dex (default-dex) @ WebIdeCompanion ---
[INFO] Convert classes to Dex : C:\Users\wsong\git\com.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\classes.dex
[INFO] 
[INFO] trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/google/zxing/aztec/AztecDetectorResult.class
[INFO] ...while processing com/google/zxing/aztec/AztecDetectorResult.class
[INFO] 
[INFO] trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/google/zxing/aztec/AztecReader.class
[INFO] ...while processing com/google/zxing/aztec/AztecReader.class
....

**Comment by mosabua** [comment]
Please upgrade to the 4.2.1 release of the simpligility version of the plugin first. We migrated off the jayway groupId.

**Comment by mosabua** [comment]
Beyond that you should be fine, I have used zxing like that in the past using older versions.

**Comment by songwk** [comment]
Hi
I have upgraded to 4.2.1 of the simpligility, but problem still exists.

This is part of my debug log for dex part:
===========================================
[INFO] --- android-maven-plugin:4.2.1:dex (default-dex) @ WebIdeCompanion ---
[DEBUG] Configuring mojo com.simpligility.maven.plugins:android-maven-plugin:4.2.1:dex from plugin realm ClassRealm[plugin>com.simpligility.maven.plugins:android-maven-plugin:4.2.1, parent: sun.misc.Launcher$AppClassLoader@43be2d65]
[DEBUG] Configuring mojo 'com.simpligility.maven.plugins:android-maven-plugin:4.2.1:dex' with basic configurator -->
[DEBUG]   (f) aaptExtraArgs = []
[DEBUG]   (f) adbConnectionTimeout = 5000
[DEBUG]   (f) androidManifestFile = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\src\main\AndroidManifest.xml
[DEBUG]   (f) assetsDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\src\main\assets
[DEBUG]   (f) attachJar = true
[DEBUG]   (f) attachSources = false
[DEBUG]   (f) combinedAssets = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\generated-sources\combined-assets
[DEBUG]   (f) destinationManifestFile = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\AndroidManifest.xml
[DEBUG]   (f) devices = []
[DEBUG]   (f) dexCoreLibrary = false
[DEBUG]   (f) dexForceJumbo = false
[DEBUG]   (f) dexIncremental = false
[DEBUG]   (f) dexJvmArguments = [-Xmx1024M]
[DEBUG]   (f) dexMinimalMainDex = false
[DEBUG]   (f) dexMultiDex = false
[DEBUG]   (f) dexNoLocals = false
[DEBUG]   (f) dexOptimize = true
[DEBUG]   (f) dexPreDex = false
[DEBUG]   (f) dexPreDexLibLocation = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\dexedLibs
[DEBUG]   (f) disableConflictingDependenciesWarning = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\false
[DEBUG]   (f) envAndroidHome = D:\androidsdk
[DEBUG]   (f) extractedDependenciesDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\generated-sources\extracted-dependencies
[DEBUG]   (f) extractedDependenciesJavaResources = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\generated-sources\extracted-dependencies\src\main\resources
[DEBUG]   (f) extractedDependenciesJavaSources = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\generated-sources\extracted-dependencies\src\main\java
[DEBUG]   (f) finalName = WebIdeCompanion
[DEBUG]   (f) genDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\generated-sources\r
[DEBUG]   (f) generateApk = true
[DEBUG]   (f) includeLibsJarsFromAar = true
[DEBUG]   (f) includeLibsJarsFromApklib = false
[DEBUG]   (f) ips = []
[DEBUG]   (f) nativeLibrariesDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\src\main\libs
[DEBUG]   (f) ndkOutputDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\ndk-libs
[DEBUG]   (f) projectOutputDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\classes
[DEBUG]   (f) release = false
[DEBUG]   (f) resourceDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\src\main\res
[DEBUG]   (f) resourceOverlayDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\res-overlay
[DEBUG]   (f) resources = [Resource {targetPath: null, filtering: false, FileSet {directory: C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\src\main\resources, PatternSet [includes: {}, excludes: {}]}}]
[DEBUG]   (f) path = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\android-sdk-windows
[DEBUG]   (f) platform = 19
[DEBUG]   (f) sdk = com.simpligility.maven.plugins.android.configuration.Sdk@50360733
[DEBUG]   (f) sdkPath = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\android-sdk-windows
[DEBUG]   (f) sourceDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\src
[DEBUG]   (f) sourceEncoding = UTF-8
[DEBUG]   (f) targetDirectory = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target
[DEBUG]   (f) undeployBeforeDeploy = true
[DEBUG]   (f) unpackedLibsFolder = C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\unpacked-libs
[DEBUG]   (f) execution = com.simpligility.maven.plugins:android-maven-plugin:4.2.1:dex {execution: default-dex}
[DEBUG]   (f) project = MavenProject: com.sap.mobile.platform.tool.webidecompanion:WebIdeCompanion:0.0.1-SNAPSHOT @ C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@48b524aa
[DEBUG] -- end configuration --
[DEBUG] Adding jvm argument -Xmx1024M
[DEBUG] Using non-obfuscated input
[DEBUG] Adding dex input : C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\classes
[DEBUG] Adding dex input : C:\Users\I062769\.m2\repository\com\sap\performance\android\perflib\1.2.0\perflib-1.2.0.jar
[DEBUG] Adding dex input : C:\Users\I062769\.m2\repository\com\sap\mobile\maf\tools\android\maflogoncore\1.207.0\maflogoncore-1.207.0.jar

.....

[DEBUG] C:\Program Files\Java\jdk1.6.0_45\jre\bin\java [-Xmx1024M, -jar, C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\android-sdk-windows\platform-tools\dx.jar, --dex, --output=C:\Users\I062769\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\classes.dex, C:\Users\I062769\.m2\repository\com\sap\smp\client\android\ClientLog\3.7.0\ClientLog-3.7.0.jar, C:\Users\I062769\.m2\repository\com\google\zxing\core\3.0.0\core-3.0.0.jar, C:\Users\I062769\.m2\repository\com\google\download\android\gcm-client\1.0.2\gcm-client-1.0.2.jar
......

[INFO] 
[INFO] trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/google/zxing/aztec/AztecDetectorResult.class
[INFO] ...while processing com/google/zxing/aztec/AztecDetectorResult.class

....

**Comment by mosabua** [comment]
Have you checked if there are some config options for dex that might help?  http://simpligility.github.io/android-maven-plugin/dex-mojo.html#dex

We might have to update the plugin to be able to pass another specific parameter in. If you can figure out what command line call works we can create a way to pass the parameter in via the plugin.

**Comment by songwk** [comment]
I think it's not plugin's problem, you can close this message. Thanks for your help!

It seems that I need use dx 1.8, not 1.7.  So I replaced the dx.jar with the version 1.8, remove "clean" phase to run "mvn install". All classes are converted to class.dex, though I use so ugly solution.

                            <execution>
                                <id>copy_dx_jar</id>
                                <phase>compile</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
				                   <target name="copy dx jar file">
				                       <copy file="${project.basedir}/src/main/pdx/dx.jar" 
				                       		tofile="${project.build.directory}/android-sdk-windows/platform-tools/dx.jar" />
				                    </target>
					              </configuration>
                            </execution>

Before I set the "android.platform.tools.version" to 19.0.1, but got an error:

Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.2.1:generate-sources (default-generate-sources) on project WebIdeCompanion: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.2.1:generate-sources failed: Invalid SDK: Build-tools not found. Check the content of 'C:\Users\wsong\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\android-sdk-windows\build-tools', or run 'C:\Users\wsong\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\android-sdk-windows\tools\android sdk' to install them -> [Help 1]

    <properties>
        <android.api.version>19</android.api.version>
        <android.jar.version>4.4.2</android.jar.version>
        <android.zip.version>19_r02</android.zip.version>
        <android.sdk.tools.version>24.1.2</android.sdk.tools.version>
        <android.platform.tools.version>19.0.1</android.platform.tools.version>
        <android.maven.version>4.2.1</android.maven.version>
        <android.sdk.path>${project.build.directory}/android-sdk-windows</android.sdk.path>
    </properties>

I will continue to check how to use the new version of Android.platform.tools.version. Thanks again!

**Comment by mosabua** [comment]
So if you use the latest Android SDK you still have that problem? It should pick up that latest dx .. if not we should fix that in the plugin.

**Comment by songwk** [comment]
I think there are something wrong about the dx.jar file, since I touched the Android development recently, I am not sure whether it is a bug, maybe I just need adjust my maven configuration, which I don't know. 

Those are my testing result, I hope it could help.

All SDK version information is listed here:
<properties>
    <android.api.version>19</android.api.version>
    <android.jar.version>4.4.2</android.jar.version>
    <android.zip.version>19_r02</android.zip.version>
    <android.sdk.tools.version>24.1.2</android.sdk.tools.version>
    <android.platform.tools.version></android.platform.tools.version>
    <android.maven.version>4.2.1</android.maven.version>
    <android.sdk.path>${project.build.directory}/android-sdk-windows</android.sdk.path>
</properties>

1. When I set <android.platform.tools.version>16.0.2</android.platform.tools.version>
I will get an exception, maven build would like to locate the dx.jar file under "target\android-sdk-windows\platform-tools\dx.jar", actually it is under "target\android-sdk-windows\platform-tools\lib\dx.jar"

[INFO] --- android-maven-plugin:4.2.1:dex (default-dex) @ WebIdeCompanion ---
[INFO] Convert classes to Dex : D:\workspace\ParentWindow\WebIdeCompanion\target\classes.dex
[INFO] Error: Unable to access jarfile D:\workspace\ParentWindow\WebIdeCompanion\target\android-sdk-windows\platform-tools\dx.jar
...
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.2.1:dex (default-dex) on project WebIdeCompanion: MojoExecutionException: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C ""C:\Program Files\Java\jdk1.7.0_21\jre\bin\java" -Xmx1024M -jar D:\workspace\ParentWindow\WebIdeCompanion\target\android-sdk-windows\platform-tools\dx.jar --dex --output=D:\workspace\ParentWindow\WebIdeCompanion\target\classes.dex D:\workspace\ParentWindow\WebIdeCompanion\target\classes C:\Users\I062769\.m2\repository\com\google\zxing\core\3.0.0\core-3.0.0.jar C:\Users\I062769\.m2\repository\com\sap\org\apache\download\cordova\cordova-android\3.6.4\cordova-android-3.6.4.jar", Result = 1 -> [Help 1]


2. When I set <android.platform.tools.version>19.0.1</android.platform.tools.version>

Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.2.1:generate-sources (default-generate-sources) on project WebIdeCompanion: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.2.1:generate-sources failed: Invalid SDK: Build-tools not found. Check the content of 'C:\Users\wsong\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\android-sdk-windows\build-tools', or run 'C:\Users\wsong\git\com.sap.mobile.platform.tool.companionappandroid\WebIdeCompanion\target\android-sdk-windows\tools\android sdk' to install them -> [Help 1]

So I use so ugly solution, just provide a dx.jar file.

**Comment by mosabua** [comment]
When I debug a run of the HelloFlashLightSampleIt I get a path of /Volumes/lin-data/tools/android-sdk-mac_86/build-tools/22.0.0/lib/dx.jar for the dx jar that is used for the execution. See DexMojo line 482 .. what are you getting there?

**Comment by songwk** [comment]
I tried helloflashlight also, did not get problem. I think you may use local sdk. 

In my pom maven-dependency-plugin is used to install and unpack sdk.  I suspect that there is something wrong with the unpacked "build-tools" in some version.

Thanks for your patient.

**Comment by songwk** [comment]
Please close this message, I checked my pom and provide unpacked "build-tools", dx could be located.

<artifactItem>
	<groupId>com.google.download.android</groupId>
	<artifactId>build-tools-windows</artifactId>
	<version>${android.build.tools.version}</version>
	<type>zip</type>
	<overWrite>false</overWrite>
	<outputDirectory>${project.build.directory}/android-sdk-windows/build-tools</outputDirectory>
	<includes>**/*</includes>
</artifactItem>
