### ISSUE TITLE
maven android dependency failed on goal simpligility

### ISSUE THREAD

**Issue by patience2015** [simpligility/android-maven-plugin#633]
problem when  build android project with maven  :

[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.2.1:generate-sources (default-generate-sources) on project RoamingTest-Mobile: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.2.1:generate-sources failed: Error reading C:\var\lib\jenkins\lib\android-sdk-linux\tools\source.properties -> [Help 1]
this is the pom of the project:

xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
4.0.0
roaming.test
Test-Mobile
RoamingTest-Mobile
0.0.1-SNAPSHOT
apk

<properties>
    <bluecove.version>2.1.1-beta1</bluecove.version>
    <log4j.version>2.1</log4j.version>
    <ion.version>1.1.7</ion.version>
    <android-support-v4.version>r6</android-support-v4.version>
    <gson.version>2.2.4</gson.version>
    <klinker-logger.version>1.0.0</klinker-logger.version>
    <android-smsmms.version>0.1.0-patched</android-smsmms.version>
    <android.version>4.4.2_r1</android.version>
    <controlsfx.version>8.20.8</controlsfx.version>
    <platform.version>4.0.3</platform.version>

    
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    
    <maven-assembly-plugin.version>2.4</maven-assembly-plugin.version>
    <maven-dependency-plugin.version>2.8</maven-dependency-plugin.version>
    <maven-jar-plugin.version>2.4</maven-jar-plugin.version>
    <maven-compiler-plugin.version>3.2</maven-compiler-plugin.version>
    <it-plugin.version>4.2.1</it-plugin.version>
    <maven-javadoc-plugin.version>2.9</maven-javadoc-plugin.version>

    
    <nexus.root.url>http:/xx:8081/nexus</nexus.root.url>

    
    <android.sdk.path>/var/lib/jenkins/lib/android-sdk-linux/</android.sdk.path>
</properties>

<dependencies>
    <dependency>
        <groupId>roaming.test</groupId>
        <artifactId>Test-Common</artifactId>
        <version>${project.version}</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>${log4j.version}</version>
    </dependency>
    <dependency>
        <groupId>net.sf.bluecove</groupId>
        <artifactId>bluecove</artifactId>
        <version>${bluecove.version}</version>
    </dependency>
    <dependency>
        <groupId>com.koushikdutta.ion</groupId>
        <artifactId>ion</artifactId>
        <version>${ion.version}</version>
    </dependency>
    <dependency>
        <groupId>com.google.android</groupId>
        <artifactId>support-v4</artifactId>
        <version>${android-support-v4.version}</version>
    </dependency>
    <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>${gson.version}</version>
    </dependency>
    <dependency>
        <groupId>com.klinkerapps</groupId>
        <artifactId>logger</artifactId>
        <version>${klinker-logger.version}</version>
    </dependency>
    <dependency>
        <groupId>com.klinkerapps</groupId>
        <artifactId>android-smsmms</artifactId>
        <version>${android-smsmms.version}</version>
    </dependency>
    <dependency>
        <groupId>com.google.android</groupId>
        <artifactId>android</artifactId>
        <version>${android.version}</version>
        <scope>provided</scope>
    </dependency>
</dependencies>

<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>${it-plugin.version}</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </pluginManagement>

    <plugins>
        <plugin>
            <groupId>com.simpligility.maven.plugins</groupId>
            <artifactId>android-maven-plugin</artifactId>
            <configuration>
                <sdk>
                    <platform>19</platform>
                </sdk>
            </configuration>
        </plugin>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>${maven-compiler-plugin.version}</version>
            <configuration>
                <source>1.7</source>
                <target>1.7</target>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.eclipse.m2e</groupId>
            <artifactId>lifecycle-mapping</artifactId>
            <version>1.0.0</version>
        </plugin>
    </plugins>

</build>

**Comment by mosabua** [comment]
I cant tell what you are asking ... want to fix the format of your question.

**Comment by mosabua** [comment]
Closed since not clear at this stage.
