### ISSUE TITLE
Incremental source generation

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#638]
Currently the plugin always writes new files in the android:generate-sources execution, even if no resource files were changed. We can do sg like the maven-compiler-plugin does, e.g. compute some hash value to check the files have been changed since the last build or not. Or maybe some better logic to actually check the files semantically.

**Comment by Shusshu** [comment]
I'd really love to see incremental builds in AMP to bring it on par with android gradle.

How do you usually run your builds ?

I always use mvn **clean** package or mvn **clean** install 

In the past I had some issues if I did not clean the project, can't remember what exactly so in the end I decided to always clean the project....

What needs to be done to be able to run incremental builds? Let's split it into parts...

* generate sources
* process sources
* generate resources
* process resources
* proguard 
* compile
* aapt
* dex
* package


Which part is fine and which parts needs work?

**Comment by WonderCsabo** [comment]
I rarely use the `clean` goal. I only had problem with when i ran the jar-signer without it. But that is only ran when releasing, and i of course do a clean build for that.

These are the goals which are invoked in a general incremental build (mvn install):

android:generate-sources
android:manifest-merger
compile
android:dex
andrid:apk

AAPT is not a separate mojo, and ProGuard should not be ran in incremental development builds. We have to make incremental:

android:generate-sources, android:manifest-merger, android:dex, android:apk mojos.

I do not use resources in my projects. I am afraid the maven-resources-plugin is not incremental, so that can break our whole idea, if there are resources in the project (i do not use them, but somebody does). This could be solved by using the Takari lifecycle. I did not tried it with Android projects.

**Comment by Shusshu** [comment]
Yes, I wasn't talking about Mojo's.
The aapt is part of the apk mojo and we'll have to see how the android gradle plugin calls aapt in incremental mode

**Comment by WonderCsabo** [comment]
Yeah, we should. Also we could contact the Android team for info on adt-dev.

**Comment by WonderCsabo** [comment]
FYI: i just tried the takari lifecycle. **It works**! :laughing: I am even using annotation processing. I just love incremental compilation! :clap:

**Comment by Shusshu** [comment]
What did you need to do ?



Benoit Billington

**Comment by WonderCsabo** [comment]
I will push an example project later. But not much actually, just disable maven-compiler plugin, and add takari with jdt compiler (javac one breaks with the processor i use). I followed the [book](http://takari.io/book/40-lifecycle.html), and read the code for undocumented features (for example processor parameters).

**Comment by WonderCsabo** [comment]
Created a very basic example [here](https://github.com/WonderCsabo/maven-android-plugin/tree/takariExample/src/test/projects/helloflashlight). Have fun. :)

**Comment by WonderCsabo** [comment]
BTW, this project demonstrates the need of this issue: we always regenerate BuildConfig.java and R.java. That is why the poor takari compiler always has to recompile them. I am not sure why it is doing that BTW, because the contents of those classes are not changed. Interesting. It seems it currently always recompiles the class if the timestamp is changed.

**Comment by WonderCsabo** [comment]
BTW, about takari we should continue the discussion in #639.

**Comment by Shusshu** [comment]
I checked the manifest-merger mojo and on a normal project it is so fast I don't think we need to spend time right now to make it incremental.
A good start would be the generate source as you pointed out.

**Comment by mosabua** [comment]
Some more details on what we need to look at are here: http://www.eclipse.org/community/eclipse_newsletter/2015/may/article3.php?utm_source=Eclipse+Newsletter&utm_campaign=8c09c936a3-Eclipse_Newsletter_May_20155_26_2015&utm_medium=email&utm_term=0_46e57eacf1-8c09c936a3-68674009

**Comment by WonderCsabo** [comment]
I played little bit with this. I think our dex phase is fine: we already can use predex if needed, and use incremental dex. The latter is not used in Gradle by default, and AFAIK considered buggy.

So we really should start with `generate-sources`. Also, a really big benefit would be #639.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
