### ISSUE TITLE
R.class generation of nested Android library modules

### ISSUE THREAD

**Issue by Konsumierer** [simpligility/android-maven-plugin#642]
Hi,

we are trying to modularize our app, extracting common and more robust parts into Android library projects (both apklib and aar tested so far). 

So, we have
- Android application **A**
- Library project **C**
- Library project **M**
- Library project **W**

with the following dependencies:
- **A** -> **C**
- **A** -> **M** -> **C**
- **A** -> **W** -> **M** -> **C**

We are using Maven (3.2.1, 3.3.3), android-maven-plugin (4.3.0, 3.9.0-rc.3) and Robolectric (2.2, 2.4) in all combinations, all with the same output.
When trying to do a full maven build with Robolectric tests, we see errors like the following in the tests for **M** and **W** when trying to use components of **C**, indicating that something is wrong with the R files:

```
android.content.res.Resources$NotFoundException: unknown resource 2130968583
```

or

```
java.lang.IllegalArgumentException: No view found for id 0x7f090001
```

Building the APK without tests works, but the app crashes in some parts.

To get closer to the root cause, I would like to concentrate on the tests first.
I am wondering, when **M** is built with Maven the `M\target\classes\..\C\R.class` of library **C** still looks the same as in `C\target\classes\..\C\R.class`. Is this correct or a bug in android-maven-plugin?
Performing the build with IntelliJ has a different output: `M\idea-classes\..\C\R.class` has all the IDs of `M\R.class` merged. I guess, this is a requirement in order to successfully run the Robolectric tests?

Kind regards

**Comment by Shusshu** [comment]
In your M lib, your classes import which R ? the one from M or from C ?

In your M lib code:
If you need R.class values specific to M then you should import the M R.class
If you need R.class values specific to C then you should import the C R.class

@william-ferguson-au do you remember we had a brief talk about this?

**Comment by william-ferguson-au** [comment]
My recollection was that during the generation of the APK that consumes M
and C the R classes for both needed to be regenerated with a consistent set
of values across the entire app.
ᐧ

On Fri, Jun 19, 2015 at 1:46 AM, Benoit Billington <notifications@github.com

**Comment by Konsumierer** [comment]
@william-ferguson-au that seems to be absolutely right, but what if M needs to be unit tested before the APK is built?

@Shusshu one example:
M uses a View class of C
C uses an ID of C R.class
-> unit test M fails because the ID is mapped to a resource of M

**Comment by william-ferguson-au** [comment]
@Konsumierer my recollection was that there was a pull request that dealt with that exact scenario.

**Comment by Konsumierer** [comment]
@william-ferguson-au do you have any details on this for me?

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.

**Comment by PViswapriya** [comment]
[gf](url)
