### ISSUE TITLE
Proguard does not work with android-maven-plugin:4.3.0 when using java path with brackets

### ISSUE THREAD

**Issue by Vall0n** [simpligility/android-maven-plugin#645]
Hello,

I've a problem with proguard execution since I switched from Version 3.8.2 to 4.3.0. And I Think this could be an issue. I've also reproduced this issue using version 4.0.0 of the Android-maven-plugin. Following exception is thrown every time I running maven with Android-maven-plugin in Version 4.3.0.

```
[INFO] proguard.ParseException: Expecting class path separator ';' before '\Java\jdk1.7.0_21\jre\lib\rt.jar' in line 5 of file 'C:\Users\jdoe\idea_source_wor
kspace\com.jdoe.test.maven-proguard\target\proguard-maven-proguard\temp_config.cfg',
```

Obviously proguard can't  extract the Java path (e. g. C:\program files (x86)\Java\jdk1.7) or the path gets corrupted somehow. 
I didn't test it but I think a workarround would be to use a Java jdk path without any spaces or brackets, but nervertheless it should work with any paths. And it does with version 3.8.2.

Steps to reproduce:
Point the Java Environment variable to an Java Installation which path has spaces and / or  brackets.
Create an "Hello World" Android Application.
Use following pom file.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.jdoe.test</groupId>
    <artifactId>maven-proguard</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>apk</packaging>


    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.android</groupId>
            <artifactId>android</artifactId>
            <version>4.1.1.4</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>


    <build>

        <sourceDirectory>${basedir}/src</sourceDirectory>

        <pluginManagement>
            <plugins>
                <!--
                <plugin>
                    <groupId>com.jayway.maven.plugins.android.generation2</groupId>
                    <artifactId>android-maven-plugin</artifactId>
                    <version>3.8.2</version>
                    <extensions>true</extensions>
                </plugin>
                -->
                <plugin>
                    <groupId>com.simpligility.maven.plugins</groupId>
                    <artifactId>android-maven-plugin</artifactId>
                    <version>4.0.0</version>
                </plugin>

            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>

                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <!--
                <groupId>com.jayway.maven.plugins.android.generation2</groupId>
                <artifactId>android-maven-plugin</artifactId>
                  -->
                <extensions>true</extensions>

                <configuration>

                    <androidManifestFile>${basedir}/AndroidManifest.xml</androidManifestFile>
                    <resourceDirectory>${basedir}/res</resourceDirectory>
                    <assetsDirectory>${basedir}/assets</assetsDirectory>
                    <nativeLibrariesDirectory>${basedir}/libs</nativeLibrariesDirectory>

                    <sdk>
                        <platform>14</platform>
                    </sdk>

                    <proguard>
                        <skip>false</skip>
                        <config>proguard.cfg</config>
                        <outputDirectory>${project.build.directory}/proguard-${project.artifactId}</outputDirectory>
                    </proguard>

                    <sign>
                        <debug>true</debug>
                    </sign>
                    <release>true</release>

                </configuration>



            </plugin>
        </plugins>
    </build>
</project>

```

Use following proguard config:

```
# This is a configuration file for ProGuard.
# http://proguard.sourceforge.net/index.html#manual/usage.html

-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-verbose

# Optimization is turned off by default. Dex does not like code run
# through the ProGuard optimize and preverify steps (and performs some
# of these optimizations on its own).
-dontoptimize
-dontpreverify
# Note that if you want to enable optimization, you cannot just
# include optimization flags in your own project configuration file;
# instead you will need to point to the
# "proguard-android-optimize.txt" file instead of this one from your
# project.properties file.

-keepattributes *Annotation*
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference

# keep constructors of custom views
-keep public class * extends android.view.View {

    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
    public void set*(...);

}
-keep public class com.google.vending.licensing.ILicensingService
-keep public class com.android.vending.licensing.ILicensingService

# For native methods, see http://proguard.sourceforge.net/manual/examples.html#native
-keepclasseswithmembernames class * {
    native <methods>;
}

# keep setters in Views so that animations can still work.
# see http://proguard.sourceforge.net/manual/examples.html#beans
-keepclassmembers public class * extends android.view.View {
   void set*(***);
   *** get*();
}

# We want to keep methods in Activity that could be used in the XML attribute onClick
-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}

# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keepclassmembers class **.R$* {
    public static <fields>;
}

# The support library contains references to newer platform versions.
# Don't warn about those in case this app is linking against an older
# platform version.  We know about them, and they are safe.
-dontwarn android.support.**

# LogCat Ausgaben entfernen
-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int i(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
}

# Zeilennummern behalten -> Wichtig fuer Retrace
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable

```

Running maven clean install from Directory that conatins the pom.xml file

```
mvn clean install
```

This is working with android-maven-plugin version 3.8.2 but don't with 4.0.0 or 4.3.0. 

I've observed, that since version 4.0.0 the goal emma is called before the proguard Goal.
In Version 3.8.2, the proguard Goal is running before emma Goal.

Best regards,

Vall0n

**Comment by william-ferguson-au** [comment]
When you say 'Point the Java Environment variable to an Java Installation which path has spaces and / or brackets.', what do you mean?

What Java Environment variable?
Do you mean JAVA_HOME?

If so, how are you executing 'mvn clean install' as this would break as **it** would not be able to find Java in order to execute Maven in the first place.

**Comment by william-ferguson-au** [comment]
OK, I can't replicate this with Maven 3.3.3, AMP-4.3.0 or AMP-4.3.1-SNAPSHOT, JDK 1.7 on Windows 10. What is your environment?

**Comment by Vall0n** [comment]
Hi,
first of all thanks for the reply!

And this is my environment:

C:\>mvn --version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: C:\Program Files (x86)\apache-maven-3.2.3\bin\..
Java version: 1.7.0_21, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.7.0_21\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 8", version: "6.2", arch: "x86", family: "windows"

AMP-4.0.0 or AMP-4.3.0

**Comment by william-ferguson-au** [comment]
I can't replicate this.
Can you please post a cut down project on Github that shows the problem.

**Comment by Vall0n** [comment]
Hi,

i've attached a zip file with the comlete sample Project to reproduce this issue.

And here is the complete Output:

C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-proguard 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ maven-proguard ---
[INFO] Deleting C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\target
[INFO]
[INFO] --- android-maven-plugin:4.0.0:generate-sources (default-generate-sources) @ maven-proguard ---
[INFO] Extracting libs
[INFO] Generating R file for com.jwoeste.test:maven-proguard:apk:1.0.0-SNAPSHOT
[INFO] Adding R gen folder to compile classpath: C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\target\generated-sources\r
[INFO] Adding AIDL gen folder to compile classpath: C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\target\generated-sources\aid
l
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ maven-proguard ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ maven-proguard ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\target\classes
[INFO]
[INFO] --- android-maven-plugin:4.0.0:emma (default-emma) @ maven-proguard ---
[INFO]
[INFO] --- android-maven-plugin:4.0.0:proguard (default-proguard) @ maven-proguard ---
[INFO] Proguarding output
[INFO] proguard.ParseException: Expecting class path separator ';' before '\Java\jdk1.7.0_21\jre\lib\rt.jar' in line 5 of file 'C:\Users\jwoeste\intellij\idea_s
ource_workspace\com.jwoeste.test.maven-proguard\target\proguard-maven-proguard\temp_config.cfg',
[INFO]   included from argument number 1
[INFO]  at proguard.ConfigurationParser.parseClassPathArgument(ConfigurationParser.java:316)
[INFO]  at proguard.ConfigurationParser.parse(ConfigurationParser.java:130)
[INFO]  at proguard.ProGuard.main(ProGuard.java:484)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.029 s
[INFO] Finished at: 2016-01-08T13:59:56+01:00
[INFO] Final Memory: 15M/37M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.0.0:proguard (default-proguard) on project maven-proguard: MojoExecutionExc
eption: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C ""C:\Program Files (x86)\Java\jdk1.7.0_21\jre\bin\java" -Xmx512M -jar C:\Users\jwoeste\AppDa
ta\Local\Android\sdk\tools\proguard\lib\proguard.jar @"C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\target\proguard-maven-pro
guard\temp_config.cfg"", Result = 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Thanks in advance for anaylzing and tryiing to reproduce!
[com.jwoeste.test.maven-proguard.zip](https://github.com/simpligility/android-maven-plugin/files/82699/com.jwoeste.test.maven-proguard.zip)

**Comment by william-ferguson-au** [comment]
Sorry I can't replicate this. Output below

```
D:\Temp\com.jwoeste.test.maven-proguard>set JAVA
JAVA_HOME=D:\Dev\jdk 1.7.0_45 with spaces

D:\Temp\com.jwoeste.test.maven-proguard>set M2
M2_HOME=D:\Dev\apache-maven-3.3.3 with spaces

D:\Temp\com.jwoeste.test.maven-proguard>set PATH
Path=D:\Dev\apache-maven-3.3.3 with spaces\bin;D:\Dev\jdk 1.7.0_45 with spaces\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

D:\Temp\com.jwoeste.test.maven-proguard>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-proguard 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ maven-proguard ---
[INFO] Deleting D:\Temp\com.jwoeste.test.maven-proguard\target
[INFO]
[INFO] --- android-maven-plugin:4.0.0:generate-sources (default-generate-sources) @ maven-proguard ---
[INFO] Extracting libs
[INFO] Generating R file for com.jwoeste.test:maven-proguard:apk:1.0.0-SNAPSHOT
[INFO] Adding R gen folder to compile classpath: D:\Temp\com.jwoeste.test.maven-proguard\target\generated-sources\r
[INFO] Adding AIDL gen folder to compile classpath: D:\Temp\com.jwoeste.test.maven-proguard\target\generated-sources\aidl
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ maven-proguard ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Temp\com.jwoeste.test.maven-proguard\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ maven-proguard ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to D:\Temp\com.jwoeste.test.maven-proguard\target\classes
[INFO]
[INFO] --- android-maven-plugin:4.0.0:emma (default-emma) @ maven-proguard ---
[INFO]
[INFO] --- android-maven-plugin:4.0.0:proguard (default-proguard) @ maven-proguard ---
[INFO] Proguarding output
[INFO] Note: there were 186 duplicate class definitions.
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ maven-proguard ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Temp\com.jwoeste.test.maven-proguard\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ maven-proguard ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.18:test (default-test) @ maven-proguard ---
[INFO] No tests to run.
[INFO]
[INFO] --- android-maven-plugin:4.0.0:dex (default-dex) @ maven-proguard ---
[INFO] Convert classes to Dex : D:\Temp\com.jwoeste.test.maven-proguard\target\classes.dex
[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ maven-proguard ---
[INFO] Building jar: D:\Temp\com.jwoeste.test.maven-proguard\target\maven-proguard-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- android-maven-plugin:4.0.0:apk (default-apk) @ maven-proguard ---
[INFO] Generating release apk.
[INFO] Adding native libraries : [D:\Temp\com.jwoeste.test.maven-proguard\target\ndk-libs]
[INFO]
[INFO] --- android-maven-plugin:4.0.0:internal-pre-integration-test (default-internal-pre-integration-test) @ maven-proguard ---
[INFO] No InstrumentationRunner found - skipping tests
[INFO]
[INFO] --- android-maven-plugin:4.0.0:internal-integration-test (default-internal-integration-test) @ maven-proguard ---
[INFO] No InstrumentationRunner found - skipping tests
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ maven-proguard ---
[INFO] Installing D:\Temp\com.jwoeste.test.maven-proguard\target\maven-proguard-1.0.0-SNAPSHOT.apk to D:\maven-local-repository\com\jwoeste\test\maven-proguard\
1.0.0-SNAPSHOT\maven-proguard-1.0.0-SNAPSHOT.apk
[INFO] Installing D:\Temp\com.jwoeste.test.maven-proguard\pom.xml to D:\maven-local-repository\com\jwoeste\test\maven-proguard\1.0.0-SNAPSHOT\maven-proguard-1.0
.0-SNAPSHOT.pom
[INFO] Installing D:\Temp\com.jwoeste.test.maven-proguard\target\maven-proguard-1.0.0-SNAPSHOT.jar to D:\maven-local-repository\com\jwoeste\test\maven-proguard\
1.0.0-SNAPSHOT\maven-proguard-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.565 s
[INFO] Finished at: 2016-01-10T14:11:00+10:00
[INFO] Final Memory: 24M/442M
[INFO] ------------------------------------------------------------------------

D:\Temp\com.jwoeste.test.maven-proguard>
```

**Comment by Vall0n** [comment]
Hi,

no Problem and thanks for your effort! 
But that's strange. Anyway, the only differences i can see are the following:

I've used maven with Version 3.2.3
And my java path.contains also parentheses

**Comment by Vall0n** [comment]
Hi,

I've just retest it with a Java Path that contains only spaces and that worked fine. 
But Than again i've changed the java path to contain parentheses. As a result i got the failed build during the proguard goal with the same error:

```
[INFO] proguard.ParseException: Expecting class path separator ';' before '1.7.0_21\jre\lib\rt.jar' in line 5 of file 'C:\Users\jwoeste\intellij\idea_source_wor
kspace\com.jwoeste.test.maven-proguard\target\proguard-maven-proguard\temp_config.cfg',
[INFO]   included from argument number 1
[INFO]  at proguard.ConfigurationParser.parseClassPathArgument(ConfigurationParser.java:316)
[INFO]  at proguard.ConfigurationParser.parse(ConfigurationParser.java:130)
[INFO]  at proguard.ProGuard.main(ProGuard.java:484)
```

 So can you reopen this issue or should I create a new one?

**Comment by william-ferguson-au** [comment]
OK, I've reopened but I'm not sure that AMP can do much about it.
The Plexus CommandLine class is what is invoking Proguard. You would need to get that fixed.

It is probably a Windowsism.

**Comment by Vall0n** [comment]
Ok, but if you use this path with AMP in Version 3.8.2 it works. 
Did the Version 3.8.2 also use the Plexus CommandLine class?

**Comment by william-ferguson-au** [comment]
No it didn't.
I believe the CommandLine was introduced to add consistency across all command line execution.

**Comment by Vall0n** [comment]
OK, then it's propably the PLEXUS command line class that causes the issue.

**Comment by Vall0n** [comment]
The Problem is the proguard.jar, which gets the temp_config.cfg as an argument. The temp_config.cfg contains the injars, libraryjars and outjars. So the PLEXUS CommandLine writes the jar paths in the file without quotes. So the proguard.jar fails to parse the content because of the path with parenthesis and without quotes. The strange thing is, that this is fine with spaces.

Test it with libraryjars in temp_config.cfg like this:

```
.
.
-libraryjars
"C:\Program Files (x86)\Java\jdk1.7.0_21\jre\lib\rt.jar"  // path is fine with quotes
-libraryjars
C:\Ja va\jdk1.7.0_21\jre\lib\jsse.jar // path is fine no quotes but also no parenthesis
-libraryjars
C:\Program Files (x86)\Java\jdk1.7.0_21\jre\lib\jce.jar  // this will cause the error
-libraryjars
.
.
```

Running following commad with the temp_config.cfg above:

```
"C:\Program Files (x86)\Java\jdk1.7.0_21\jre\bin\java" -Xmx512M -jar C:\Users\jdoe\AppData\Local\Android\sdk\tools\proguard\lib\proguard.jar @"C:\Users\jdoe\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\target\proguard-maven-proguard\temp_config.cfg"
```

Leads to follwoing error:
```
proguard.ParseException: Expecting class path separator ';' before '\Java\jdk1.7.0_21\jre\lib\jce.jar' in line 9 of file 'C:\Users\jwoeste\intellij\idea_source_workspace\com.jwoeste.test.maven-proguard\target\proguard-maven-proguard\temp_config.cfg',
  included from argument number 1
        at proguard.ConfigurationParser.parseClassPathArgument(ConfigurationParser.java:316)
        at proguard.ConfigurationParser.parse(ConfigurationParser.java:130)
        at proguard.ProGuard.main(ProGuard.java:484)
```

So, I think the PLEXUS CommadLine class is just fine. 
So either the proguard.jar needs to handle paths with parenthesis and no quotes in the temp_config.cfg or all paths need to be surounded by quotes when written to the temp_config.cfg file.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
