### ISSUE TITLE
Wrong package

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-maven-plugin#646]
Class should move to simpligility.

https://github.com/simpligility/android-maven-plugin/blob/master/src/main/java/com/jayway/maven/plugins/android/resource/XpathAppendingTransformer.java#L2

**Comment by mosabua** [comment]
Wanna fix this @kedzie ?

**Comment by kedzie** [comment]
Sure move it where. To the simp package?

**Comment by mosabua** [comment]
Yep..

**Comment by kedzie** [comment]
I'm doing this now.. forgot about it.

**Comment by kedzie** [comment]
Pushed PR #676

**Comment by mosabua** [comment]
Will go live with 4.3.1
