### ISSUE TITLE
Projects fail when run on Java 6

### ISSUE THREAD

**Issue by secondsun** [simpligility/android-maven-plugin#647]
TL;DR: This bug :https://bugs.openjdk.java.net/browse/JDK-6440786 hits here:https://github.com/simpligility/android-maven-plugin/blob/master/src/main/java/com/simpligility/maven/plugins/android/phase_prebuild/ClasspathModifierLifecycleParticipant.java#L294

To test:  Build a project which consumes AAR dependencies on JDK 6.

Possible fix : Close the FileOutPutStream instead of the ZipOutputStream.

**Comment by william-ferguson-au** [comment]
But how does that play if using the Sun JDK?

Closing the ZipOutputStream is the correct thing to do as it allows the
ZipOutputStream to close off any zip related resources. I understand that
doing so trips a bug in OpenJDK-6, but it seem to me the solution is to
move to OpenJdk-7 not to hack a library that is doing the correct thing.

**Comment by secondsun** [comment]
This is with the Sun/Oracle JDK.

**Comment by william-ferguson-au** [comment]
OK, the bug you referenced is for OpenJdk not the Sun JDK.

**Comment by secondsun** [comment]
I suppose it is more accurate to say I've tested both.  openJDK on Travis-CI and Sun JDK in a Docker image and gotten the same result each time.

The Snoracle bug tracker doesn't mention this issue however.

**Comment by william-ferguson-au** [comment]
Well if you can fashion a pull request that works on both and also on JDK7+
then go for it.
ᐧ

**Comment by mosabua** [comment]
Agreed... but if we have to choose we will go with Java 7. Java 6 is EOL for a long time now and Java 7 is since April. I would rather get the build and usage to work with Java 8 rather than worry about Java 6 at this stage..

**Comment by secondsun** [comment]
@mosabua That is all I needed to hear.  AeroGear Android will be dropping Java 6 support.  Our Travis-CI build times thank you.

**Comment by mosabua** [comment]
Does the Android SDK still support Java 6? If not.. we should drop it to imho.

**Comment by mosabua** [comment]
Seem JDK 7 at this stage... https://developer.android.com/sdk/index.html#Requirements

**Comment by mosabua** [comment]
So @simpligility/android-maven-plugins-core-committers do we move to Java 7 for the project?

**Comment by Shusshu** [comment]
Java 1.7 try-with-resources is only supported on 4.4+ API 19
I think we can drop support for Java 6 but not enforce a min of Java 7 we can still keep the min Java 6.

**Comment by mosabua** [comment]
The API stuff is for running on a device though right... which is different from what Java version AMP uses at build time. 

Do people still use Java 6 to build Android apps? I would hope not .. but really dont know.

**Comment by Shusshu** [comment]
Yes it's different, I should not mix both things ;)

Maybe a CI server which still use java 6 but I wouldn't know why

**Comment by william-ferguson-au** [comment]
+1 to dropping j6 at build time

**Comment by WonderCsabo** [comment]
I also suggest to move to JDK 7. Nobody should use JDK 6 anymore. It is safe to convert the plugin source code. 

I really cannot understand how the Java version of the Android projects come here. That is totally unrelated. Am I missing sg?

**Comment by spatula75** [comment]
FWIW, the front page of the project still says it works with JDK 6, so I had expected JDK 6 to keep working after we updated our plugin to 4.3 (from 3.8).  Wish I'd seen this issue an hour ago!  I'm also fine with moving to building with JDK 7, but the documentation should be updated to indicate that 7 is required.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
