### ISSUE TITLE
How add libgdx.so? 

### ISSUE THREAD

**Issue by teren4m** [simpligility/android-maven-plugin#653]
<plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>${android-maven-plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <attachSources>true</attachSources>
                    <androidManifestFile>${project.basedir}/AndroidManifest.xml</androidManifestFile>
                    <assetsDirectory>${project.basedir}/assets</assetsDirectory>
                    <resourceDirectory>${project.basedir}/res</resourceDirectory>
                    <androidManifestFile>${project.basedir}/AndroidManifest.xml</androidManifestFile>
                    <nativeLibrariesDirectory>${project.basedir}/libs</nativeLibrariesDirectory>
                    <aidlSourceDirectory>${project.basedir}/aidl</aidlSourceDirectory>
                    <sdk>
                        <platform>${platform.sdk.version}</platform>
                    </sdk>
                </configuration>
            </plugin>

Project have in folder libs -> armeabi -> libgdx.so
In old version 3.8.0 worked well. Now I have exeption    PathClassLoader[DexPathList[[zip file "/data/app/com.playtech.ngm.nativeclient.customisation-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libgdx.so"

**Comment by johanlindquist** [comment]
Which version are you using right now?  Was the included text meant to be XML?  Could you provide more information?

Thanks

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
