### ISSUE TITLE
Resource references not resolved

### ISSUE THREAD

**Issue by RomainPiel** [simpligility/android-maven-plugin#654]
I'm trying to integrate a maven based project with IntelliJ (and Android Studio) and I'm having issues with references between resources (although it's building just fine). Known issue?
I tried with one of the sample and I'm seeing the same issue:
<img width="604" alt="screen shot 2015-07-10 at 10 29 43" src="https://cloud.githubusercontent.com/assets/464320/8616085/3c7e9692-26f0-11e5-8d89-91dea90a21c1.png">

**Comment by william-ferguson-au** [comment]
Sounds like you have a misconfiguration in your IntelliJ module.->structure->Resources directory.

**Comment by RomainPiel** [comment]
No I checked that and it's definitely pointing to the right folder
<img width="668" alt="screen shot 2015-07-10 at 13 47 46" src="https://cloud.githubusercontent.com/assets/464320/8618897/469df180-270a-11e5-9c88-ec609e92a214.png">

**Comment by william-ferguson-au** [comment]
Well, this is an Intelli issue. If it's building alright via Maven the the plugin is working.
