### ISSUE TITLE
APK Test projects fail on the site plugin

### ISSUE THREAD

**Issue by spyhunter99** [simpligility/android-maven-plugin#655]
when calling "mvn site" and utilizing the maven site plugin, it looks like the android-maven-plugin is rebuilding all apk packages. This has unfortunate side effect when used with the maven javadoc plugin and appears to causes the site plugin to loop forever. I'm not 100% sure the root cause is, but it appears to be related to APK projects and those two plugins.

**Comment by mosabua** [comment]
Do you have a simple example project or can you replicate the problem with one of the examples from the plugin codebase?

**Comment by spyhunter99** [comment]
on it. i'll post back (eventually), probably with a pull request

**Comment by mosabua** [comment]
Btw... from what I know rebuilding everything is part of how the site plugin works even on normal projects so you have to keep that in mind. 

Also let us know command you run in detail? Really only mvn site?

**Comment by spyhunter99** [comment]
yup, just mvn site. i'll whip up an example and confirm it can be replicated (and not just something whacky with my setup)

**Comment by spyhunter99** [comment]
i just replicated my setup with libraryprojects-parent and it builds the site, although it looks like each project gets built several times. It does fail with the libraryprojects-tests (which is a different issue). 

My particular project is 80+ sub modules thus the site phase takes a while to run (over 90 minutes). I had mistake this as an infinite loop, where as it was really just a time consuming process.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
