### ISSUE TITLE
Maven can't find source or javadoc jars based on AAR or APK modules

### ISSUE THREAD

**Issue by spyhunter99** [simpligility/android-maven-plugin#656]
I have a "distribution" module which basically takes all of the JAR,AAR and APK binaries, javadoc jars, and source jars and then feeds them into a maven assembly plugin to zip them all up and a tidy distribution zip.

The maven-source-plugin and maven-javadoc-plugin does generate the artifacts and installs them to the local maven repo. The "distribution" module's pom references them using 

`   <type>APK</type><classifier>javadoc</classifier>`

However, it can't reference them. I'm not entirely sure what's going on here. Maybe the javadoc and sources plugin needs to be altered or perhaps it's something within the maven-android plugin. Looking for any pointers to get me going here.

**Comment by mosabua** [comment]
html,body{font-size:12px;background-color:#fff;color:#333;font-family:sans-serif,Arial,Verdana,"Trebuchet MS";line-height:1.4;}Have you tried lower case type apk ? 



spyhunter99 wrote on 2015-07-20 11:33:


I have a "distribution" module which basically takes all of the JAR,AAR and APK binaries, javadoc jars, and source jars and then feeds them into a maven assembly plugin to zip them all up and a tidy distribution zip.

The maven-source-plugin and maven-javadoc-plugin does generate the artifacts and installs them to the local maven repo. The "distribution" module's pom references them using

<type>APK</type><classifier>javadoc</classifier>

However, it can't reference them. I'm not entirely sure what's going on here. Maybe the javadoc and sources plugin needs to be altered or perhaps it's something within the maven-android plugin. Looking for any pointers to get me going here.

**Comment by spyhunter99** [comment]
Oh sorry, it should have been lower case :)

To clarify, I am using lower case. Not sure what's going on

**Comment by mosabua** [comment]
Can you confirm that the artifact is in the local repo including the apk javadoc one?

**Comment by mosabua** [comment]
Also ... aren't you building up your assembly with an assembly.xml or so definition?

**Comment by spyhunter99** [comment]
Here's what I have, excluding the lastUpdated files

myproject-1.0.0-SHAPSHOT.apk
myproject-1.0.0-SHAPSHOT.jar
myproject-1.0.0-SHAPSHOT.pom
myproject-1.0.0-SHAPSHOT-javadoc.jar
myproject-1.0.0-SHAPSHOT-sources.jar

**Comment by mosabua** [comment]
That looks correct. And how are you referencing thme for your assembly?

**Comment by spyhunter99** [comment]
The distribution module's pom looks like (not syntactically correct, but
you'll get the point)

<groupId>${project.parent.groupId}
<artifactId>myapp
<version>${project.parent.version}
<type>apk
<classifier>sources

I've also tried it without the type, no change

**Comment by mosabua** [comment]
Try hardcoding the values and maybe instead of using the pom to get the assembly defined used a assembly descriptor.

**Comment by spyhunter99** [comment]
ahh!

ok for the pom, remove the type (apk, aar) flags and leave the classifier

in the maven assembly file, for source, use jar as the packaging field. For javadocs, omit the packaging field

thanks for the help

**Comment by spyhunter99** [comment]
correction, also use jar for packaging for javadocs

**Comment by mosabua** [comment]
Yes... missed that. The javadoc and source artifacts should have packaging/type jar in their dependency declaration. You can also add the jar itself in addition to the apk potentially.
