### ISSUE TITLE
Manifest.mf or BuildConfig injection?

### ISSUE THREAD

**Issue by spyhunter99** [simpligility/android-maven-plugin#658]
Is there a way to inject content into the APK's signed META-INF/manifest.mf (prior to signing)?  I want to inject content that's available as a maven property at build time to make it easier to track build configs, profiles, git branches, etc. I have  maven plugin that works great for everything except APKs. In /target of the APK file, there is a JAR containing the injected stuff, but that doesn't transfer into the APK's manifest file

Related question, is there a way to inject into the generated BuildConfig class? It's fairly easy with gradle, and if it's easy with gradle must be even easier in maven

**Comment by spyhunter99** [comment]
I figured it out. Here's an example. 

	<plugin>
	    <groupId>com.simpligility.maven.plugins</groupId>
	    <artifactId>android-maven-plugin</artifactId>
	    <configuration>
	        <sdk>
	            <platform>19</platform>
	        </sdk>
			 <buildConfigConstants>
				 <buildConfigConstants>
					 <name>test</name>
					 <value>zxc</value>
					 <type>String</type>
				 </buildConfigConstants>
			 </buildConfigConstants>
	    </configuration>
	</plugin>

**Comment by mosabua** [comment]
Want to submit a pull requests that documents that somewhere on the site?

**Comment by spyhunter99** [comment]
sure thing

**Comment by mosabua** [comment]
Just look at src/site/asciidoc and site.xml

**Comment by spyhunter99** [comment]
Oh i was going to alter one of the same projects. Your choice

**Comment by mosabua** [comment]
Thats good too but we need some documentation that points to wards the example. Either a separate small how to or just an addition to the examples page.

**Comment by spyhunter99** [comment]
Ok no problem. You guys rock by the way. Down with gradle

**Comment by mosabua** [comment]
We only rock thanks to the help of people like you @spyhunter99 

cc @simpligility/android-maven-plugins-core-committers

**Comment by spyhunter99** [comment]
do you know maven lifecycle phase the BuildConfig generation happens at? I'm having a minor with the git version plugin (you'll see)

**Comment by spyhunter99** [comment]
nm i got it
