### ISSUE TITLE
Duplicate files packaging error impacts Android integration testing

### ISSUE THREAD

**Issue by andrew-bowley** [simpligility/android-maven-plugin#660]
The apk goal is failing during packaging while attempting to remove duplicates. There are 4 jar files all with LICENSE.txt in the root location - 3 hamcrest v1.3 jars and junit-4.11.jar. The target unpacked-embedded-jars folder ends up with these files:

duplicate-resources.jar
hamcrest-core-1.3.jar
hamcrest-integration-1.3.jar
hamcrest-library-1.3.jar
junit-4.11.jar

Two are unreadable (hamcrest-integration-1.3.jar and junit-4.11.jar) and I assume associated with two ocurrances of this error:

*Cannot removing duplicates : duplicate entry: LICENSE.txt*

 A workaround is to remove the offending files with a zip editor. However, it is not acceptable to ask users to do this. This is also a significant issue because it impacts Android integration testing when using the AndroidJunitTestRunner and Espresso.

To reproduce this error, add the following dependency (available from SDK extras/android/m2repository):

 \<groupId\>com.android.support.test.espresso\</groupId\>
 \<artifactId\>espresso-core\</artifactId\>
  \<version\>2.2\</version\>
 \<packaging\>aar\</packaging\>

**Comment by andrew-bowley** [comment]
I have investigated the code and found the error is occurring in method removeDuplicatesFromJar at line 830 of class ApkMojo in package com.simpligility.maven.plugins.android.phase09package:

*duplicateZos.putNextEntry( entry );*

The error is genuine in that the ZipEntry "entry" is a duplicate. The previous line failed to correctly detect a duplicate because the logic is reversed:

*!duplicatesAdded.add( entry.getName() )*

API: HashSet.add() returns true if this set did not already contain the specified element.

Please correct indicated statement at line 828 by removing the exclamation mark in front of "duplicatessAdded".

**Comment by william-ferguson-au** [comment]
Want to provide a pull request?

**Comment by andrew-bowley** [comment]
OK. It will be my first time, so it will be interesting.

**Comment by william-ferguson-au** [comment]
There's always a first time :)

**Comment by andrew-bowley** [comment]
Pull request submitted: https://github.com/simpligility/android-maven-plugin/pull/661

**Comment by william-ferguson-au** [comment]
PR merged - thanks Andrew
