### ISSUE TITLE
publish-listing goal fails when more than 1 languages exist

### ISSUE THREAD

**Issue by athkalia** [simpligility/android-maven-plugin#662]
Hello,

I have app screenshots and descriptions etc in the directories as described in the goals page on your site http://simpligility.github.io/android-maven-plugin/playstore-publisher.html, for both Greek and English (US). When I run the publish-listing goal with both directories existing in the project it only updates the first one  (Greek) then fails with the following message:

```
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.2.0:publish-listing (default-cli) on project application: Problem in the listing content: 410 Gone
[ERROR] {
[ERROR] "code" : 410,
[ERROR] "errors" : [ {
[ERROR] "domain" : "androidpublisher",
[ERROR] "message" : "This edit has already been successfully committed, please create a new Edit.",
[ERROR] "reason" : "editAlreadyCommitted"
[ERROR] } ],
[ERROR] "message" : "This edit has already been successfully committed, please create a new Edit."
[ERROR] }
```

I can tell though that there is nothing wrong in the directories hierarchy etc, because when I delete the whole greek folder and I run the same goal only with the english directory existing  then the english language screenshots and descriptions get uploaded just fine and the build succeeds.

**Comment by mosabua** [comment]
Pull request for fix merged. Will go and be released with 4.3.1
