### ISSUE TITLE
Plugin execution not covered by lifecycle configuration: com.simpligility.maven.plugins:android-maven-plugin:4.3.0:

### ISSUE THREAD

**Issue by skauss** [simpligility/android-maven-plugin#663]
Dear android-maven-plugin developer,
I try to migrate my project from 
 - com.jayway.maven.plugins.android.generation2 - android-maven-plugin - Version 3.9.0-rc.2
to
 - com.simpligility.maven.plugins - android-maven-plugin - Version 4.3.0

I have many a many module project (6 modules). I switched to from apklib to aar .
In case I build my project now with maven I get a running apk out  ;-)
In case I use eclipse I get the Error message 
Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: com.simpligility.maven.plugins:android-maven-plugin:4.3.0:emma (execution: default-emma, phase: process-classes)	pom.xml	/CountryOneAPK	line 33	Maven Project Build Lifecycle Mapping Problem

Parent pom.xml
	<build>
		<pluginManagement>
			<plugins>
	<plugin>
				
					<groupId>com.simpligility.maven.plugins</groupId>
					<artifactId>android-maven-plugin</artifactId>
					<version>${android-maven-plugin.version}</version>
					<executions>
						<execution>
							<id>alignApk</id>
							<phase>install</phase>
							<goals>
								<goal>zipalign</goal>
							</goals>
						</execution>
					</executions>

					<configuration>
<androidManifestFile>${project.basedir}/AndroidManifest.xml</androidManifestFile>
						<resourceDirectory>${project.basedir}/res</resourceDirectory>
						<assetsDirectory>${project.basedir}/assets</assetsDirectory>
		.....
Module to create the APK

 <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>${android-maven-plugin.version}</version>
                
                <configuration>
                    <sdk>
                        <platform>18</platform>
                    </sdk>
                    
                    <androidManifestFile>${project.basedir}/AndroidManifest.xml</androidManifestFile>
				    <assetsDirectory>${project.basedir}/assets</assetsDirectory>
				    <resourceDirectory>${project.basedir}/res</resourceDirectory>
                </configuration>
                <extensions>true</extensions>
            </plugin>			

Eclipse now get me the lifecyle Error.

Any idea who to get eclipse ready to build the APK ?

Regards
Stephan

Sorry I didn't know how to past XML part's into this editor

**Comment by skauss** [comment]
Hi,
I found a solution.

https://github.com/simpligility/android-maven-plugin/issues/592

Answer :
  Not Maven, but the Maven Eclipse plugin (m2e) shows you this error. 
  If you are not using emma, you can just ignore the execution by using the quick fix.

Regards
Stephan

**Comment by tchoulihan** [comment]
I just ran into this error.

I finally fixed it in eclipse by marking the emma goal as *experimental*. 

By default, every pom in the test folder has errors unless you do this.
