### ISSUE TITLE
duplicate manifest.mf

### ISSUE THREAD

**Issue by mars3142** [simpligility/android-maven-plugin#665]
I've got a big problem. I want to build an APK with a AAR-library (using normal JAR dependencies). 

The AAR is build perfect with the JAR (not Android specific code, so it is used in normal Java project -> server side), but the APK wants to include the JAR-files as well. This is the expected behavior, because it needs all class files.

But then I received following error message at the end

**[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:apk (default-apk) on project com.example.app: Duplicated file: MANIFEST.MF, found in archive ~/.m2/repository/com/example/shared/1.0.0-SNAPSHOT/com.example.shared-1.0.0-SNAPSHOT.jar and ~/.m2/repository/com/example/server/1.0.0-SNAPSHOT/com.example.server-1.0.0-SNAPSHOT.jar: Duplicate files at the same path inside the APK -> [Help 1]**

I'm also include

```
<configuration>
    <extractDuplicates>true</extractDuplicates>
</configuration>
```

but this does not remove double manifest.mf files. It only prints

**[ERROR] Cannot removing duplicates : duplicate entry: MANIFEST.MF**

**Comment by spyhunter99** [comment]
I'm confused here...

You have a two projects (let's call it A and B)
B depends on A
B is an APK
A is an AAR

Is that correct?

I have this same type of configuration and haven't ran into this.

FYI, an AAR requires an AndroidManifest (it can be nearly empty, but must be present) and can (not required) include additional resources, assets, images, etc, plus class files. Does your AAR have a manifest? Also, if the AAR has no android specific stuff in it, just make it a jar packaging.

**Comment by mars3142** [comment]
I have 3 projects (A, B and C)

A -> JAR
B -> AAR (depends on A)
C -> APK (depends on B)

Have I to repack the Project A into an AAR to work with it? That would be bad, because in the same maven run should be built the server project.

**Comment by j0bro** [comment]
I can also reproduce it. My project depends on several jetty JARs and all contain an about.html file which triggers the same error message:
[ERROR] Cannot removing duplicates: about.html

Of course, the extractDuplicates configuration setting is set to 'true'.

**Comment by aminabs** [comment]
Hey,
I'm having the same problem with jetty jars. Any progress?

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
