### ISSUE TITLE
android apk doesn't contains unobfuscated resource

### ISSUE THREAD

**Issue by ymenager** [simpligility/android-maven-plugin#667]
I've got an android app being compiled with maven, and I've enable proguard for the production build.

```
<project >
    ...
    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            ...
            <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>${android.plugin.version}</version>
                <extensions>true</extensions>
            </plugin>
            ...
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.simpligility.maven.plugins</groupId>
                    <artifactId>android-maven-plugin</artifactId>
                    <version>${android.plugin.version}</version>
                    <configuration>
                        <sdk>
                            <platform>${android.sdk}</platform>
                        </sdk>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <profiles>
        <profile>
            <id>prod</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.simpligility.maven.plugins</groupId>
                        <artifactId>android-maven-plugin</artifactId>
                        <configuration>
                            <release>true</release>
                            <proguard>
                                <skip>false</skip>
                            </proguard>
                        </configuration>
                        <executions>
                            <execution>
                                <id>update-manifest</id>
                                <goals>
                                    <goal>manifest-update</goal>
                                </goals>
                                <configuration>
                                    <manifest>
                                        <versionName>${project.version}</versionName>
                                        <versionCode>${project.codeVersion}</versionCode>
                                        <debuggable>false</debuggable>
                                    </manifest>
                                </configuration>
                            </execution>
                            <execution>
                                <id>alignApk</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>zipalign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

In my proguard cfg, I've set it so that a resource file has it's content obfuscated using:

```
-adaptresourcefilecontents ormlite_config.txt
```

That resource file is located under src/main/resources/ormlite_config.txt

After running the build, I can see that the myapp_obfuscated.jar file has the right content (all class names have been changed to their obfuscated value). 

HOWEVER, the apk still has the old unobfuscated value :( which naturally breaks the app completely.

**Comment by ymenager** [comment]
Definitely a bug.... I've managed to reproduce this by taking one of the examples (morse code app), and I'm getting the same thing. 

It's here if you want to have a look: 

https://github.com/ymenager/sandbox

Just run the unpack.sh (change JAVA_HOME to point to a jdk 6-7) and it'll extract both the obfuscated jar and the apk (in which test.properties will differ since the jar one will be obfuscated, and the apk one will still be the old one)

**Comment by ymenager** [comment]
The more I look at the code, the more I get the impression that it just doesn't support obfuscated resources (which is really bad because any application that has a resource that includes a class name will break, which is not that uncommon a use case).... Could any of the devs confirm if that's the case ?

**Comment by william-ferguson-au** [comment]
I wasn't aware that you could obfuscate resources.
I have never had a need. I can't imagine why any class that needs to be configured in a resource file would need to be obfuscated. If it does, why did you put it in a resource file to begin with?

**Comment by mosabua** [comment]
Does the normal Android SDK even support that? I am not aware of such a feature.

**Comment by ymenager** [comment]
It's actually not such a rare use case.

For example any library using ServiceLoader: https://docs.oracle.com/javase/tutorial/ext/basics/spi.html

Or (my case) anyone using ORMLite's ( see http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_4.html#Config-Optimization )

There's also the case of libraries that might keep some kind of resource file in a file named as a class (so ie com.bla.MyClass would load data from com.bla.MyClass.properties), which would require proguard's -adaptresourcefilenames

Regarding if android SDK supports it, actually I just tried yesterday as a gradle build, and it doesn't seem to work either :( :( :(

But I really think it would be a really important feature to support because both of those use cases above are really not that rare. It also shouldn't be too difficult to implement, the obfuscated resources are in the _obfuscated.jar file.... All that's needed is to use those rather than the original ones as it currently does for .class files)

**Comment by william-ferguson-au** [comment]
Actually I think it **IS** that rare.
This is the first request we have had for it in 5 years.

I use ServiceLoader and ORMs in Android myself. SeviceLoader and ORM classes are perfect examples of the classes that you specifically DON'T want to obfuscate.

**Comment by ymenager** [comment]
Hmm... I suspect most people who hit that problem solve it the "easy" way, which is to set -keep on the affected classes.

Can't really do that myself because I'm developing a security application, so maximum obfuscation required :(

I wouldn't mind doing a fix myself but I'm afraid it'll end up being a "hack" due to my lack of familiarity in the codebase.

Is there any "proper" way to retrieve the obfuscated jar (if it exists) in ApkMojo in order to use the resources there rather than the normal ones ?

**Comment by mosabua** [comment]
We are just using the Android SDK proguard integration and nothing special beyond that. We rely on it working in the SDK. 

In your case I would consider looking at dexguard, which is the Android specific, commercial extension of Proguard from the same authors. I dont know anything about it beyond that though.

https://www.guardsquare.com/dexguard

Also dont be perceived by what obfuscation can get you. Its not that hard to reverse the obfuscation ... check out some of the hacking session about Android from past C3 conference (https://events.ccc.de/) or droidcon or others.

**Comment by william-ferguson-au** [comment]
I'm closing this because I don't think it's an issue.
It's just the was Proguard is.

**Comment by RobRendell** [comment]
Proguard supports this with the -adaptresourcefilecontents directive, as the OP mentioned.  So it's not "just the [way] Proguard is".  Very annoying that this wasn't considered a real issue.
