### ISSUE TITLE
Allow using "test source directory" for integration tests, instead of requiring a new maven project/module

### ISSUE THREAD

**Issue by mitchhentges** [simpligility/android-maven-plugin#669]
Perhaps I'm missing some documentation, but I can't seem to have my tests in the same project, different source directory.

When doing a gradle project, you throw your main app code in `src/main/java` and put your test sources in `src/androidTest/java`. When `gradle connectedAndroidTest` is run, it builds two apks: once of them just contains the app, the other contains the app and all test sources (this second one is installed on the device and tested)

With `android-maven-plugin`, I'm finding that by test sources are never included in any compiled apk, and that I have to create a "test project" - another maven project or module. This _works_, but it's less convenient

**Comment by Shusshu** [comment]
maven use `src/test/java` directory

**Comment by mitchhentges** [comment]
Right. Even if I put the sources in there, they aren't included in a built apk

**Comment by mitchhentges** [comment]
This actually is a little more sinister.
When you put your tests in `src/test/java`, the tests appear to run, but are executed on the host machine - **not the tablet**.
This means that any android-specific tests are going to fail, because all the android methods are stubs.

**Comment by Shusshu** [comment]
That's a known behaviour

There are solutions but I'm unable to list them for you now.

**Comment by mosabua** [comment]
The Android Maven Plugin does not work with tests in src/test/java since the Maven Surefire Plugin uses those. It might be worth looking into support something like src/androidTest/java and then run the tests somehow via the Android Maven Plugin. Care to investigate and send a pull requests @mitchhentges ? 

Otherwise the typical integration tests are done in a separate project as usual and as visible in the example projects...

**Comment by Shusshu** [comment]
I think I have placed tests in src/test/java in a project... forgot which kind of tests and I don't have the project anymore.

But usually I do a separate module for ui tests

**Comment by mitchhentges** [comment]
I'll look into it, but I'm not entirely sure how Maven plugins "do". I'll check it out, though

**Comment by mitchhentges** [comment]
How should we allow configuring this? I'm thinking:
```
//default
<plugins>
	<plugin>
		<groupId>com.simpligility.maven.plugins</groupId>
		<artifactId>android-maven-plugin</artifactId>
		<configuration>
			<!-- Whether to compile local android tests into apk and instrument them -->
			<useProjectAndroidTests>true</useProjectAndroidTests>
			<!-- Where "java", "res", "resources" and "AndroidManifest.xml" is for the test apk -->
			<androidTestDirectory>src/androidTest</androidTestDirectory>
		</configuration>
	</plugin>
</plugins>


//alternate config
<plugins>
	<plugin>
		<groupId>com.simpligility.maven.plugins</groupId>
		<artifactId>android-maven-plugin</artifactId>
		<configuration>
			<useProjectAndroidTests>true</useProjectAndroidTests>
			<androidTestDirectory>src/xtreme-tests</androidTestDirectory>
		</configuration>
	</plugin>
</plugins>
```

**Comment by mitchhentges** [comment]
Hmm, it would be smarter to tie it into the `<test>` group. Defaults:
`
<test>
	<skip>false</skip>
	<includeMainSources>false</includeMainSources>
	<testSourcesDirectory>src/androidTest</testSourcesDirectory>
</test>
`

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
