### ISSUE TITLE
Plugin building on AMP: java.lang.ClassCastException: ...Maven31DependencyGraphBuilder

### ISSUE THREAD

**Issue by dzan** [simpligility/android-maven-plugin#672]
Hi,

I have a plugin replacing a step of the Android build process (it adds a Mojo class similar to the ProguardMojo class and adapts the components.xml file in order to be called). The plugin is dependent on the AMP of course, it's just an 'extension'.

As long as this plugin is the only one used everything works perfectly. When an Android project has one module using the default AMP and another one using my plugin the build crashes with:

```
[ERROR] Internal error: java.lang.ClassCastException: org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder cannot be cast to org.apache.maven.shared.dependency.graph.DependencyGraphBuilder -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ClassCastException: org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder cannot be cast to org.apache.maven.shared.dependency.graph.DependencyGraphBuilder
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:861)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassCastException: org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder cannot be cast to org.apache.maven.shared.dependency.graph.DependencyGraphBuilder
        at org.apache.maven.shared.dependency.graph.internal.DefaultDependencyGraphBuilder.buildDependencyGraph(DefaultDependencyGraphBuilder.java:86)
        at com.simpligility.maven.plugins.android.common.DependencyResolver.getProjectDependenciesFor(DependencyResolver.java:49)
        at com.simpligility.maven.plugins.android.phase_prebuild.ClasspathModifierLifecycleParticipant.afterProjectsRead(ClasspathModifierLifecycleParticipant.java:136)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
```

I tried a bunch of things and really can not find the issue. 
- Made sure the versions of the plugin dependencies are equal between the two builds.
- Tried a couple of maven versions.
- Replaced my code with the ProguardMojo.java file which resulted in the same issue, so it's probably not my code but rather some of the xml files?
- Went over previous similar issues ([here](https://github.com/simpligility/android-maven-plugin/issues/492) and [here](https://github.com/simpligility/android-maven-plugin/issues/377)).

I was wondering if anyone here has had similar issues or has any idea on how to fix this?

**Comment by william-ferguson-au** [comment]
It sounds like you have a conflict between 2 incompatible versions of the
DependencyGraphBuilder.
Its signature changed about 6 months ago and I would suggest that your
plugin may be using a version that is at odds with the one AMP uses.


[image: photo]
*William Ferguson*
Founder and CEO, XandarMob
m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>

**Comment by dzan** [comment]
@william-ferguson-au I figured it would be something like that so I made sure all the plugin/maven-api dependency versions were equal by comparing the pom.xml files and the output of the maven debug log. I'm pretty sure they are identical.

Also, I don't add any new imports of that class. I have one class extending AMP's AbstractAndroidMojo, which does import DependencyGraphBuilder, so it should use the same classes AMP does right?

From what I found the DependencyGraphBuilder is part of the 'maven-dependency-tree' artifact. This one is forced to 2.2 in AMP's pom.xml at one location and not forced at another. My pom.xml doesn't even mention it, I just have a dependency on AMP.

One strange thing, there is a special simpligility version of it according to Maven Central (http://search.maven.org/#search|ga|1|maven-dependency-tree), but based on AMP's pom.xml this is not the one used?

Thanks you for the quick reply!

**Comment by william-ferguson-au** [comment]
The `com.simpligility.org.apache.maven.shared` version sounds like the one that we needed to cut while waiting for 2.2 to be released.

Dig deeper. Try commenting things out until it works to find out the clash. Maybe the version of Maven is pulling it an old dep-tree version. What versions of Maven have your tried?

**Comment by dzan** [comment]
I tried the 2.2.x and 3.0.x, 3.2.x and now am running the snapshot built myself.

When checking what is being used by building with --debug the versions seem fine. You mean commenting out parts in the pom.xml files? I'm just kind of out ideas on how to debug this.

**Comment by william-ferguson-au** [comment]
Maven-3.3.3 is the latest
And yes, commenting out parts of the POM.

**Comment by dzan** [comment]
I reduced my pom.xml to the bare minimal and still run into the issue;

````
<?xml version="1.0" encoding="UTF-8"?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test.myplugin.maven</groupId>
    <artifactId>myplugin-maven-plugin</artifactId>
    <version>5.5.00</version>

    <prerequisites>
        <maven>3.0.4</maven>
    </prerequisites>

    <dependencies>
        <dependency>
            <groupId>com.simpligility.maven.plugins</groupId>
            <artifactId>android-maven-plugin</artifactId>
            <version>4.3.0</version>
        </dependency>
    </dependencies>
</project>
````

Using  _mvn clean dependency:resolve-plugins_ to check the versions:

* [output of a run with my plugin](http://paste.ubuntu.com/12054514/)
* [a run with the default AMP](http://paste.ubuntu.com/12054515/)

This shows no real difference (except from the maven-jar-plugin dependency in AMP).

**Comment by william-ferguson-au** [comment]
Wait, why do you have a dependency on AMP?
It is not designed as a library to be included.

**Comment by william-ferguson-au** [comment]
From your paste bins:

AMP has a dependency on `maven-dependency-tree-2.2.jar`
maven-dependency-plugin has a dependency on `maven-dependency-tree-1.2.jar`

I think you'll find that is the conflict.

You are also using AMP-4.1.0 which is REALLY old.
4.3.0 is current and 4.3.1-SNAPSHOT is trunk.

**Comment by dzan** [comment]
@william-ferguson-au Sorry, those maven-dependency-tree references were a left-over of one of my attempts (copying all dependencies to a separate folder to inspect them, I didn't realize at first this didn't work on dependencies of plugins)

Without the maven-dependency-tree plugin the problem persists and the dependency-tree-1.2.jar is gone.

I tried different versions of AMP, current trunk including. The reason for the dependency is because that is how my plugin works... plexus/components.xml delegates everything to the simpligity mojo's, I just add one.

**Comment by dzan** [comment]
I think the issue here could be the following;

My plugin inherits from AMP's AbstractAndroidMojo which imports the DependencyGraphBuilder. In a project where both AMP and my plugin are used they are started in separate VM's so even tough the classes are identical they can't be cast into each other?

**Comment by william-ferguson-au** [comment]
They won't be started in separate VMs but they could be started in separate classloaders.

You are almost certainly getting tripped up because of your dependency on AMP in your plugin **AND** using AMP in the project at the same time. Don't do this.

Instead create a fork of AMP and include your own Mojo.
**OR** create a plugin that doesn't depend on AMP.

You still haven't provided a good reason why you have a dependency on AMP.

**Comment by priand** [comment]
I have a similar issue. I wanted to update to project to generate a aar instead of a jar. I added the following to my POM:
```
    <packaging>aar</packaging>
    ...
    <build>
        <plugins>
      		<plugin>
        		<groupId>com.simpligility.maven.plugins</groupId>
        		<artifactId>android-maven-plugin</artifactId>
        		<version>4.5.0</version>        		
       		</plugin>  
```
But I'm getting the same class cast exception. I got the error with maven 3.0.5, 3.1.1 and 3.6.0

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
