### ISSUE TITLE
Test fails, can't fix it on my machine because Build Tools Rev 22.0.0 no longer downloadable

### ISSUE THREAD

**Issue by mitchhentges** [simpligility/android-maven-plugin#674]
The test:

```
    @Test
    public void validPlatformsAndApiLevelsWithDiffBuildTools1() {
        // Remember to add further platforms to .travis.yml if you add more platforms here, otherwise ci build fails
        final AndroidSdk sdk = new AndroidSdk( new File( sdkTestSupport.getEnv_ANDROID_HOME() ), "19", "22" );
        Assert.assertTrue( sdk.getAaptPath() != null && !sdk.getAaptPath().equals( "" ) );
    }
```

I'm not quite sure the purpose of this test, especially considering that `validPlatformsAndApiLevelsWithDiffBuildTools2()` is right below it. At any rate, it's a nuisance.

`@Ignore` for the test is [even appearing in PRs](https://github.com/simpligility/android-maven-plugin/pull/659/files#diff-f1ac05f3c8113a4ffa03789edcb7c56aR117)!

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
