### ISSUE TITLE
Add/Modify meta-data tags 

### ISSUE THREAD

**Issue by sebigansca** [simpligility/android-maven-plugin#677]
Hi, 
Is there any plan to implement the add or update of the meta-data tags from application or activity level? 
Thanks

**Comment by mosabua** [comment]
I am not sure I understand what you mean. Is this some sort of build time thing. From the description it sounds something about runtime behaviour which has nothing to do with the Android Maven Plugin.

**Comment by sebigansca** [comment]
The meta-data tag can be used to add "custom" properties to application or activity. 
My use-case is that I need to set such a property based on the maven profile selected. 

However I'm digging into manifest-merger goal, that seems to do the trick by importing from a library this property. 

But I have another problem, I cannot set the sharedUsedId with this goal, it was possible with manifest-update goal. 

So if I may ask is there a plan to add the option to set sharedUserId with manifest-merger goal?

Thanks a lot for your answer

**Comment by mosabua** [comment]
There is no plan .. but we would be more than happy to take a pull request that implements the feature from you ;-)

**Comment by sebigansca** [comment]
ok :) 

Will do, probably next week.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
