### ISSUE TITLE
aar generation issue with classes.jar

### ISSUE THREAD

**Issue by developernotes** [simpligility/android-maven-plugin#680]
Hi,

We are working on creating an aar package for [SQLCipher for Android](https://github.com/sqlcipher/android-database-sqlcipher) using the android-maven-plugin.  

Following a build, our output looks like this before packaged into the aar:
``` 
libs/
├── armeabi
│   ├── libdatabase_sqlcipher.so
│   ├── libsqlcipher_android.so
│   └── libstlport_shared.so
├── armeabi-v7a
│   ├── libdatabase_sqlcipher.so
│   ├── libsqlcipher_android.so
│   └── libstlport_shared.so
├── sqlcipher-javadoc.jar
├── sqlcipher.jar
└── x86
    ├── libdatabase_sqlcipher.so
    ├── libsqlcipher_android.so
    └── libstlport_shared.so
```
Once we create an aar using android-maven-plugin, we are seeing an issue where the exploded aar contains a classes.jar which is mainly empty, while our sqlcipher.jar exists within the jni folder.  An example of the aar can be found [here](https://oss.sonatype.org/content/groups/staging/net/zetetic/android-database-sqlcipher/3.3.1/android-database-sqlcipher-3.3.1.aar), the pom.xml looks like [this](https://oss.sonatype.org/content/groups/staging/net/zetetic/android-database-sqlcipher/3.3.1/android-database-sqlcipher-3.3.1.pom) we have updated to the latest groupId using 4.3.0 with the same results.  The issue is the sqlcipher.jar file is not referenced when within the jni folder.

I believe sqlcipher.jar should be renamed to classes.jar and placed at the top level within the aar, is there a way to tell android-maven-plugin to do this?  Or can you offer an alternative resolution to get this working?  Thanks!

**Comment by developernotes** [comment]
For posterity, I should clarify that we have added the following changed to the above linked pom.xml file for project settings:
```
<androidManifestFile>AndroidManifest.xml</androidManifestFile>
<resourceDirectory>res</resourceDirectory>
<assetsDirectory>assets</assetsDirectory>
<nativeLibrariesDirectory>libs</nativeLibrariesDirectory>
```

**Comment by william-ferguson-au** [comment]
What is causing sqlcipher.jar and sqlcipher-javadoc.jar to be generated within target\libs?

**Comment by developernotes** [comment]
The entire project is orchestrated via our [Makefile](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/Makefile), the Java component is built via our call to [ant release](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/Makefile#L54).  Is there a preferred directory android-maven-plugin is looking for this output in?  Thanks!

**Comment by william-ferguson-au** [comment]
I'll defer to the AMP guys that do lots of NDK builds. But generally speaking AMP will perform all of steps necessary (including C compilation) and would package your classes up into a classes.jar that would be at the root of your AAR not within the libs folder.

Since you are doing everything via Make and Ant I'm not sure what you are using AMP for.
Alternatively, why are you using Make and Ant?

**Comment by developernotes** [comment]
Hi @william-ferguson-au 

>Since you are doing everything via Make and Ant I'm not sure what you are using AMP for.

We are simply looking to publish our library as an aar file on Maven Central.  AMP looked like an optimal route, however maybe that is not the case.  The usage of Make is really just to have a common interface to orchestrate ant, ndk-build and shell scripts for the compilation process.

**Comment by developernotes** [comment]
@william-ferguson-au 

I just noticed you asked above about sqlcipher.jar being generated within target/libs, it isn't - the libs directory is at the root of the project.

**Comment by developernotes** [comment]
I've addressed this issue by setting `out.dir=target` within the project.properties.  The class files generated from the `ant release` command was previously being output to the bin directory.  Adjusting the out.dir to the target directory allows AMP to locate the precompiled class files.  Thanks!
