### ISSUE TITLE
Default bindings

### ISSUE THREAD

**Issue by Miksu82** [simpligility/android-maven-plugin#681]
Hi,

Is there documentation available about plugin bindings for different packagings. I mean something like this http://maven.apache.org/ref/3.3.3/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging but for apk and aar pacakging?

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
