### ISSUE TITLE
Data Binding

### ISSUE THREAD

**Issue by kedzie** [simpligility/android-maven-plugin#683]
The new [Gradle maven plugin](https://android.googlesource.com/platform/tools/base/) supports class generation to support [Data Binding](http://developer.android.com/tools/data-binding/guide.html).  We should do the same for the maven plugin..

**Comment by kedzie** [comment]
@mosabua  what do you think of this?  Is there already an effort underway?

**Comment by mosabua** [comment]
Hm ... is it just a dependency or is there more to it?

**Comment by kedzie** [comment]
There is code generation involved.. I am digging through the gradle plugin source code now to see if we need to copy & paste code from the gradle plugin.. or if it is *(hopefully)* localized in the data binding dependency...

**Comment by kedzie** [comment]
the dataBinder dependency is available from the jcenter repository https://bintray.com/android/android-tools/com.android.databinding.dataBinder/view

**Comment by kedzie** [comment]
If you look at the source for the dataBinder dependency, it looks like it has the code generation stuff in there, in the form of a gradle plugin.. I would appreciate if you helped out in researching this stuff

**Comment by mosabua** [comment]
It might be in the gradle or in the android tools library. I am not going to be able to look at this for a while though. Have to catch up with PRs and making a new release first at this stage. Maybe ask on the mailing list to help on a common/shared investigation.

**Comment by kedzie** [comment]
@mosabua made a lot of progress.  I have it working but it has some hacks to it needs some work.  Main issue is that the layout files are modified as part of the build.  So I

* enabled resource filtering to copy my android resources to temporary build folder ```/target/filtered-res```
* added comment in each layout file pointing back to original ```<!-- From: file:${project.basedir}/src/main/res/layout/fragment_main.xml -->``` (this is required by the layout processor)

So I need to write some code to automate this.. copy the resources to temporary build folder and insert the comments.  Then let the layouts get processed, then have the rest of the plugin use the modified resources instead of originals..

Any thoughts?

**Comment by wilem82** [comment]
Are there any plans to add this feature?

**Comment by mosabua** [comment]
Not sure .. the plugin pretty much relies on community contributions at this stage but if this is ready I can potentially look into merging and releasing

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
