### ISSUE TITLE
BuildConfig configuration not accepted by Android Studio

### ISSUE THREAD

**Issue by Thorbear** [simpligility/android-maven-plugin#684]
With some Googling I managed to find an accepted [pull request](https://github.com/simpligility/android-maven-plugin/pull/218) and some [documentation](https://docs.google.com/document/d/1ggvF7ZV1tTiTqKNlQ-e07z6kbzctytOylk_ySPGDcz0/edit) for a feature that doesn't seem to exist in the official documentation, custom BuildConfig variables.

However when I add this to my pom, Android Studio complains that `Element buildConfigConstants is not allowed here`. The project seems to build just fine, and the variables are successfully added to BuildConfig. Android Studio doesn't complain like this about any of the other configuration elements.

Are these elements perhaps missing from some validation-file that Android Studio (and presumably other IDEs) uses to check if the pom is valid?

Issue encountered using plugin version 4.3.0 and Android Studio 1.4

**Comment by Shusshu** [comment]
It's probably because Android Studio is built for Gradle and you need to specify buildConfigConstants  in your gradle file.
it might have found a custom var in the BuildConfig class.

You should use IntelliJ as Android Studio does not support maven

**Comment by Thorbear** [comment]
Opening the same pom in IntelliJ IDEA 14.0.3 Community Edition gives the same result.

**Comment by Shusshu** [comment]
Interesting, maybe because the IntelliJ team just merge google's code for android....
You should probably open a ticket on the intellij tracker

**Comment by Shusshu** [comment]
Or something is wrong with our BuildConfig.... could you compare a gradle generated one (with a buildConfigConstants )?

**Comment by Thorbear** [comment]
Apparently this is fixed by #723
