### ISSUE TITLE
svg to png support 

### ISSUE THREAD

**Issue by Shusshu** [simpligility/android-maven-plugin#687]
Bring the nice svg to png feature introduced in the android gradle plugin 1.4.0-beta2

```
Vector drawable support for generating PNGs at build time. 
PNGs are generated for every vector drawable found in a resource directory that does not specify an API version (or specifies a version lower than 21).
This only happens if minSdk is below 21.
Densities to use can be set using the new "generatedDensities" property in defaultConfig or per-flavor.
```

Using the android library

Note:
I don't have time right now but if someone starts the research and get stuck I can help out.

**Comment by lyubomyr-shaydariv** [comment]
Have you probably already seen [fr.avianey.androidsvgdrawable:maven-plugin](https://github.com/avianey/androidsvgdrawable-plugin)? It seems to do exactly what you suggested, but does not provide a `minSdk` support alternative.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
