### ISSUE TITLE
Enable specifying android build tools version

### ISSUE THREAD

**Issue by mssavai** [simpligility/android-maven-plugin#697]
When building android apps with Maven it always uses the latest Build-Tools available. Some apps are dependent on older Build-Tools versions. The suggested improvement here is to provide a way to specify a default version of the Build-Tools, which would be used instead of latest version. If no Build-Tools version is specified, it defaults to latest version.

**Comment by mosabua** [comment]
Sounds good. Want to submit a pull request?

**Comment by mssavai** [comment]
Sorry, looks like it's already fixed in [this commit](https://github.com/simpligility/android-maven-plugin/commit/a52d218964b0fa75db751954b15e316f5b0d3aa4). 

Closing this issue.

**Comment by Shusshu** [comment]
Yep ;)
