### ISSUE TITLE
Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources (default-generate-sources) on project android: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources failed: Error reading E:\android测试项目\zxing-master\android\E\:\android_ecplise\Eclipse(64位)+sdk\android_sdk_5.0.1\tools\source.properties -> [Help 1]

### ISSUE THREAD

**Issue by agoodcoolman** [simpligility/android-maven-plugin#700]
run as maven,it's report the error info

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Android Barcode Scanner app 4.7.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (validate) @ android ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ android ---
[INFO] 
[INFO] --- android-maven-plugin:4.3.0:generate-sources (default-generate-sources) @ android ---
[INFO] Manifest copied from E:\android测试项目\zxing-master\android\AndroidManifest.xml to E:\android测试项目\zxing-master\android\target\AndroidManifest.xml
[INFO] Extracting libs
[INFO] Generating R file for com.google.zxing:android:apk:4.7.5
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.170 s
[INFO] Finished at: 2015-12-06T22:22:22+08:00
[INFO] Final Memory: 26M/267M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources (default-generate-sources) on project android: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources failed: Error reading E:\android测试项目\zxing-master\android\E\:\android_ecplise\Eclipse(64位)+sdk\android_sdk_5.0.1\tools\source.properties -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

the path is error ,how to config it ?

**Comment by mosabua** [comment]
Looks like there is some sort of invalid path configured. Could you move the project to a simple path with no unicode folder names in it? 

Also why is it extracting from an apk? From what I know the zxing android library is available as jar (and maybe as aar now).

**Comment by agoodcoolman** [comment]
my config:E:\android_ecplise\Eclipse(64位)+sdk\android_sdk_5.0.1\tools\source.properties

but it has error prifix:E:\android测试项目\zxing-master\android\

**Comment by mosabua** [comment]
Can you try this with a simpler path and reopen if it still is reproducible?
