### ISSUE TITLE
Missing skip paramater

### ISSUE THREAD

**Issue by salmonb** [simpligility/android-maven-plugin#701]
Can't find a way to skip the plugin execution (that would be usefull when working on multiple modules project with members who don't work on the android module and have no android sdk installed).

Using the following doesn't work:
```xml
...
    <artifactId>myartifact</artifactId>
    <packaging>apk</packaging>
...
    <profiles>
        <profile>
            <id>android</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.simpligility.maven.plugins</groupId>
                        <artifactId>android-maven-plugin</artifactId>
                        <version>4.3.0</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```
because maven complains about not recognizing the apk packaging. The plugin needs therefore to be out of the profile to be downloaded even on non android developers machines and let maven know about the apk packaging so it can parse the pom without error.

So it would be nice to have the following working:
```xml
...
    <artifactId>myartifact</artifactId>
    <packaging>apk</packaging>
... 
    <properties>
        <skip-plugin>true</skip-plugin>
    </properties>
    <profiles>
        <profile>
            <id>android</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <skip-plugin>false</skip-plugin>
            </properties>
        </profile>
    </profiles>
    <build>
        <plugins>
           <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>4.3.0</version>
                <skip>${skip-plugin}</skip>
            </plugin>
        </plugins>
    </build>
```

But the skip parameter doesn't exist. Would it be possible to add it to the plugin?

**Comment by mosabua** [comment]
You would have to implement a skip parameter for each plugin goal. Some of them already have them. Also your use case does not make sense. If you want people to skip a whole module .. just make a profile that does not contain the android module.
