### ISSUE TITLE
Proguard rules of transitives dependencies are not retrieved 

### ISSUE THREAD

**Issue by nbeuret** [simpligility/android-maven-plugin#704]
I've noticed that proguard configuration files of transitive AAR are not passed to the proguard command like it's done for direct dependencies.

When checking how it is implemented, we can easily understand and validate this behavior : 
```
    for ( Artifact artifact : getDirectDependencyArtifacts() )
    {
        if ( AAR.equals( artifact.getType() ) )
        {
            File unpackedLibFolder = getUnpackedLibFolder( artifact );
            File proguardFile = new File( unpackedLibFolder, "proguard.txt" );
            if ( proguardFile.exists() )
            {
                proguardCommands.add( "@" + proguardFile.getAbsolutePath() );
            }
        }
    }
```

As a workaround, we can add the transitives dependencies as direct dependencies of the main project. 

My question is : 
Is it the desired behavior or a missing feature ?

For me it would be the second option. If you can confirm I'll try to create a pull request in the next weeks with a fix. 

Thanks !

**Comment by william-ferguson-au** [comment]
I didn't implement the original AAR Proguard inclusion but I suspect it is a missing feature.

**Comment by william-ferguson-au** [comment]
@nbeuret here is the link to the original commit that introduced Proguard merging.
https://github.com/simpligility/android-maven-plugin/commit/c760f90f933e778840d94ac2a3fa78f4be88f22d
