### ISSUE TITLE
The ArcheType for version 4.x

### ISSUE THREAD

**Issue by walkwolf** [simpligility/android-maven-plugin#707]
android-maven-plugin 4.3.0
eclipse luna
os: mac 10.11.2
-------
1.Open eclipse .
2.create maven project , catalog : android
then i got
 de.akquinet.android.archetypes  android-quickstart 1.1.0
and release and test 1.1.0  from http://repo1.maven.org/maven2  

3.Select one of above,and modified below
android-plugin-version 4.3.0

4.Open the pom.xml in the created project

Then i got
<plugin>
					<groupId>com.jayway.maven.plugins.android.generation2</groupId>
					<artifactId>android-maven-plugin</artifactId>

Where can I get the latest cagalog file？

**Comment by william-ferguson-au** [comment]
I think you are asking where you can get the latest Maven archetype catalog used by the maven-archetype-plugin. Please read the following http://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html

Note that the catalog has nothing to do with the android-maven-plugin.
And the archetype that you selected, is also not maintained by the committers of the android-maven-plugin

**Comment by mosabua** [comment]
The archetype has probably not been updated. We do not manage it as part of the plugin. Use one of our example projects instead. @walkwolf
