### ISSUE TITLE
Dependency hierarchy not working

### ISSUE THREAD

**Issue by BlueRiverInteractive** [simpligility/android-maven-plugin#710]
Consider the following dependency hierarchy (Each project depends on the next higher project):

(4) AAR project (available via public repository)
(3) Maven AAR project: Doesn't have any code, just depends on (4).
(2) Maven AAR project: Wrapper code around the (3) project. (The code of (4) is not on the classpath but should be! I only get (4) on the classpath if I add a direct dependency.)
(1) Gradle Android project in IntellijI DEA: The app project. (Should have everything on the classpath ((2), (3) and (4)). But I get nothing. Is it not possible to depend on Maven AAR projects from Gradle?)

Also is it possible to use the retrolambda plugin together with the android-maven-plugin AAR?

**Comment by lyubomyr-shaydariv** [comment]
> Also is it possible to use the retrolambda plugin together with the android-maven-plugin AAR?

[This](https://github.com/simpligility/android-maven-plugin/blob/master/src/site/asciidoc/instrumentation.adoc) might help you.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
