### ISSUE TITLE
AAR Dependency Classes.jar cannot be found

### ISSUE THREAD

**Issue by Stuey86** [simpligility/android-maven-plugin#713]
Moving to 4.4.1 causes this issue on our Project. Our Apk Project needs to be multidexed.

shared-library-android (aar) is a dependency of module-1 (aar) & module-2 (aar)
my-android-app (apk) has a dependency on module-1 & module-2

[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.1:dex (default-dex) on project my-app: Failed to execute mainDexClasses: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd '/Users/Stu/Projects/my-android/my-android-app' && '/usr/local/Cellar/android-sdk/24.4.1/build-tools/23.0.2/mainDexClasses' '--output' '/Users/Stu/Projects/my-android/my-android-app/target/mainDexClasses.txt' '"/Users/Stu/Projects/my-android/my-android-app/target/unpacked-libs/csmc_shared-library-android_1.2.0-SNAPSHOT/classes.jar:

INFO] Error: Can't read [/Users/Stu/Projects/my-android/my-android-app/target/unpacked-libs/csmc_shared-library-android_1.2.0-SNAPSHOT/classes.jar... (Same Error for all Dependencies including Android Support Libs)

The classes.jar does exist (no corruption that i can find) when i inspect the target folder after the build has failed

**Comment by Stuey86** [comment]
Seems Issue only happens on Mac
Same Project & Versions builds correctly on Windows but not on Mac.
Maven - 3.3.3
JDK - 1.7.0_79

**Comment by william-ferguson-au** [comment]
So 2 questions:
1) Does /Users/***/my-android/my-android-app/target/unpacked-libs/csmc_shared-library-android_1.2.0-SNAPSHOT/classes.jar exist?

2) What is the '***' part of that path? That looks weird.

**Comment by Stuey86** [comment]
Updated the description. *** was a work related directory. replaced it now. Yes the Classes.jar exists and does not seem to be corrupted. Can open it and the correct .class files are there. Thanks

**Comment by william-ferguson-au** [comment]
OK, I'll have to bow out as I don't have an environment in which I can replicate this.

**Comment by mosabua** [comment]
Might be fixed with 4.4.3 .. please let me know

**Comment by Stuey86** [comment]
Thanks! Will only be able to check next week.

**Comment by Stuey86** [comment]
Hi @mosabua - The reverses happens now. It breaks on Windows machines now but Works on Mac and Other Linux systems. Possibly same issue as https://github.com/simpligility/android-maven-plugin/issues/740

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
