### ISSUE TITLE
Multidex not working

### ISSUE THREAD

**Issue by hameno** [simpligility/android-maven-plugin#716]
I'm getting the following error when enabled mutlidex:

```
[INFO] --- android-maven-plugin:4.4.1:dex (default-dex) @ autobild ---
[INFO]       You should check if you need to specify additional program jars.
[INFO] A fatal error occured: Wrong classpath: File ""/var/lib/jenkins/workspace/app1/app1/target/app1-0.52-SNAPSHOT-android_obfuscated.jar"" not found
```

Why are there duplicated quotes?

EDIT: This is on linux (Ubuntu 14.04) with 
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.1
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"

**Comment by hameno** [comment]
I've fixed it with this commit:
https://github.com/sprylab/android-maven-plugin/commit/e4e70b7d9ac5ac3067a03c378e6bf79fecd18590

**Comment by mosabua** [comment]
The duplicated quotes needed to be necessary for Windows from what I remember... anyway.. your solution is better. Want to submit a PR for it?

**Comment by mosabua** [comment]
Otherwise I can just commit the change..

**Comment by hameno** [comment]
Won't be able to do a PR until next week, so maybe just commit it directly :)

**Comment by mosabua** [comment]
Sounds good.

**Comment by fichestrati** [comment]
We have the same problem. Can you integrate this fixe ? 
thank you ;)

**Comment by mosabua** [comment]
Committed with https://github.com/simpligility/android-maven-plugin/commit/24499f20e5d7061e2e686c873f9f4edb8f0f7bd8

**Comment by mosabua** [comment]
Will be released with 4.4.3

**Comment by mosabua** [comment]
4.4.3 is released now.

**Comment by Thorbear** [comment]
Does this mean that Windows support is dropped? If the "fix" simply removed code that existed to make it work on Windows.
