### ISSUE TITLE
how with my error when app run on android 4.4

### ISSUE THREAD

**Issue by jack20my** [simpligility/android-maven-plugin#717]
I combiled app with mvn and com.simpligility.maven.plugins .Combile is success and it run on android 5.0 is well.But when on android 4.4 it throw a exeption.The exeption is 
02-24 16:50:56.444 W/dalvikvm( 6090): threadid=1: thread exiting with uncaught exception (group=0x41d73d58)
02-24 16:50:56.444 E/AndroidRuntime( 6090): FATAL EXCEPTION: main
02-24 16:50:56.444 E/AndroidRuntime( 6090): Process: com.alliance.party, PID: 6090
02-24 16:50:56.444 E/AndroidRuntime( 6090): java.lang.RuntimeException: Unable to instantiate application com.alliance.party.PSApp: java.lang.ClassNotFoundException: Didn't find class "com.alliance.party.PSApp" on path: DexPathList[[zip file "/data/app/com.alliance.party-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.alliance.party-1, /vendor/lib, /system/lib]]
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:509)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4352)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.os.Looper.loop(Looper.java:136)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.app.ActivityThread.main(ActivityThread.java:5052)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at dalvik.system.NativeStart.main(Native Method)
02-24 16:50:56.444 E/AndroidRuntime( 6090): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alliance.party.PSApp" on path: DexPathList[[zip file "/data/app/com.alliance.party-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.alliance.party-1, /vendor/lib, /system/lib]]
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
02-24 16:50:56.444 E/AndroidRuntime( 6090): 	... 11 more

my pom setting like this:
                       <plugin>
				
				<groupId>com.simpligility.maven.plugins</groupId>
				<artifactId>android-maven-plugin</artifactId>
				<version>4.4.1</version>
				<extensions>true</extensions>
				<configuration>
					<extractDuplicates>true</extractDuplicates>

					
					<sdk>
						<platform>${android.platform}</platform>
					</sdk>
					<sign>
						<debug>${project.build.sign.debug}</debug>
					</sign>
					<release>${project.build.release}</release>
					<run>
						<debug>${project.build.debug}</debug>
					</run>
					<runDebug>${project.build.runDebug}</runDebug>

					
					<androidManifestFile>${basedir}/AndroidManifest.xml</androidManifestFile>
					<assetsDirectory>${basedir}/assets</assetsDirectory>
					<nativeLibrariesDirectory>${basedir}/libs</nativeLibrariesDirectory>
					<resourceDirectory>${basedir}/res</resourceDirectory>
					<failonduplicatepackages>false</failonduplicatepackages>
					
					
					
					<dex>
						
						<multi-dex>true</multi-dex>
						<minimal-main-dex>false</minimal-main-dex>
						<dex-arguments>--set-max-idx-number=51000</dex-arguments>
						
						<main-dex-list>${basedir}/MainDexList.txt</main-dex-list>
					</dex>
				</configuration>
			</plugin>

# What's wrong with my code.
Sorry for my poor English.Thanks very much !

**Comment by mosabua** [comment]
If the app works on 5.0 but not on 4.4 I am not sure it is related to building the application. In any case .. we can not reproduce the problem with this minimal description and stack trace. Please provide more information and maybe an example project.

http://simpligility.github.io/android-maven-plugin/report-issue.html

**Comment by jack20my** [comment]
Thank you mosabua!
I had fixed the issue by update the com.simpligility.maven.plugins version and change android sdk version.
The successful android version is 19 for plugins 4.4.1.
Thank you very much!
