### ISSUE TITLE
Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by mynameislichengeng** [simpligility/android-maven-plugin#719]
Plugin execution not covered by lifecycle configuration: com.simpligility.maven.plugins:android-maven-plugin:4.1.1:generate-sources (execution: default-generate-sources, phase: generate-sources)

**Comment by mosabua** [comment]
Not enough detail here to do anything. See http://simpligility.github.io/android-maven-plugin/report-issue.html
