### ISSUE TITLE
Test report is generated in the wrong format and Jenkins doesn't show test failures

### ISSUE THREAD

**Issue by evgenynacu** [simpligility/android-maven-plugin#720]
Generated report should be in surefire format (xsd can be found here: https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd)

Plugin generates report in slightly different format, so Jenkins doesn't recognize it and doesn't show test failures.

I had to use [xUnit Jenkins Plugin](https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin) and specified xsl for converting plugin xml report to surefire xml report.
Here is xsl:

```xml
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:template match="//testsuite">
        <testsuite name="{@name}" tests="{@tests}" errors="{@errors}" failures="{@errors}" skipped="{@ignored}" time="{@time}">
            <xsl:for-each select="testcase">
                <testcase classname="{@classname}" name="{@name}" time="{@time}">
                    <xsl:for-each select="./error">
                        <xsl:copy-of select="."/>
                    </xsl:for-each>
                </testcase>
            </xsl:for-each>
        </testsuite>
    </xsl:template>
</xsl:stylesheet>
```

**Comment by mosabua** [comment]
I have had this fully working in the past so I am not sure what the detailed issue is. Can you provide a bit more details what specifically is wrong and maybe even a pull request that fixes the issue?

**Comment by evgenynacu** [comment]
@mosabua Yes, I had this working a year or more ago too, but it seems Jenkins changed parsing of test reports (in the new project installed newest version of Jenkins)
Will check their xml schema and get back.

**Comment by evgenynacu** [comment]
Finally found some time to dig about this problem. 
Jenkins couldn't find reports because of changed groupId of android-maven-plugin. I added pull request to jenkins maven plugin: [https://github.com/jenkinsci/maven-plugin/pull/73]
There are some hardcoded plugin names and group ids in the file [https://github.com/evgenynacu/maven-plugin/blob/081b4a3816e825a97a2c1972810f174e974bd0d9/src/main/java/hudson/maven/reporters/TestMojo.java]

Jenkins team recently made it possible to support custom reports directory for different plugins.
To let jenkins know when and where find reports user should specify maven property [https://wiki.jenkins-ci.org/display/JENKINS/Building+a+maven2+project#Buildingamaven2project-Example]

So I successfully added support for android-maven-plugin reports using -Djenkins.default-internal-integration-test.reportsDirectory=target/surefire-reports in the jenkins job configuration (or any can add property directly to pom.xml)

I think you can add this to documentation (so people know how to make jenkins show test failures)

Also, I was looking at AndroidTestRunListener. It had some boilerplate code. I improved it using jaxb and added a test for xsd validation of generated reports. Also, stacktrace wasn't shown in the previous version. Currently, it's shown.
Submitted pull request to you: [https://github.com/simpligility/android-maven-plugin/pull/734]

**Comment by mosabua** [comment]
Merged PR
