### ISSUE TITLE
Strange buildConfigConstants parameter

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#722]
I just found the [`buildConfigConstants`](https://github.com/simpligility/android-maven-plugin/blob/74044942cc35f4e60f80f8d8c42a1c4ec4698363/src/test/projects/buildConfigInjection/pom.xml#L79) parameter, which is very strange to me:

1. Why plural form in the inner elements? I guess it is only the problem of the example.
2. IntelliJ marks the `buildConfigConstants` section in red, like it is missing from the plugin declaration.
3. It is not in the [generated doc](http://simpligility.github.io/android-maven-plugin/generate-sources-mojo.html), either.

Maybe because it is [`read-only`](https://github.com/simpligility/android-maven-plugin/blob/74044942cc35f4e60f80f8d8c42a1c4ec4698363/src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java#L227)? Why is that? @mosabua some hints?

**Comment by william-ferguson-au** [comment]
I had just noticed the same thing. You beat to raising the issue @WonderCsabo :-)

I can't see a reason for it to be `read-only`. I assume this is why it isn't in the generated docs.

The naming  in that test is incorrect. We use
```
					<buildConfigConstants>
						<buildConfigConstant>
							<name>VERSION_NAME</name>
							<type>String</type>
							<value>${project.version}</value>
						</buildConfigConstant>
					</buildConfigConstants>

```
and it works. So not sure how the test is passing.

**Comment by WonderCsabo** [comment]
Hey
