### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#726]
```sh
$ echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
Valid ABIs: no ABIs.
Error: Invalid --abi armeabi-v7a for the selected target.
```

I am not sure what is the problem. The image is installed in the Android dependencies. The same command works fine when i execute it on my locale machine.

**Comment by mosabua** [comment]
Maintain a working build with travis and android is a PITA imho. I am considering taking the running of the IT tests out to be honest and just do that when running builds..

**Comment by WonderCsabo** [comment]
@mosabua never give up. 😏

**Comment by mosabua** [comment]
Its working now thanks to your efforts @WonderCsabo
