### ISSUE TITLE
4.4.2 is not available on maven central

### ISSUE THREAD

**Issue by william-ferguson-au** [simpligility/android-maven-plugin#729]
Nor has https://simpligility.github.io/android-maven-plugin/project-summary.html been updated

But it is showing as released on 25-MAY-2016 in the changelog https://github.com/simpligility/android-maven-plugin/blob/master/src/site/asciidoc/changelog.adoc

**Comment by mosabua** [comment]
I did not get around to finishing it on that day. But its out now. Still pending better announcement blog post .. but ready to use.
