### ISSUE TITLE
Error: Can't read [...] (No such file or directory)

### ISSUE THREAD

**Issue by zhenkhokh** [simpligility/android-maven-plugin#730]
Having error when try 
`mvn android:dex`

all directory in [...] is readable despite have
`[INFO] Error: Can't read [/home/zheka/workspace/GetStartAndroid/gmapExample/target/classes:/home/zheka/.m2/repository/org/easytesting/fest-assert-core/2.0M8/fest-assert-core-2.0M8.jar:/home/zheka/.m2/repository/org/easytesting/fest-util/1.2.3/fest-util-1.2.3.jar:/home/zheka/workspace/GetStartAndroid/gmapExample/target/unpacked-libs/cas_appcompat-v7_21.0.0/classes.jar:/home/zheka/workspace/GetStartAndroid/gmapExample/target/unpacked-libs/cgag_play-services_6.5.87/classes.jar:/home/zheka/.m2/repository/com/almende/eve/eve-bundle-android-ws/3.1.1/eve-bundle-android-ws-3.1.1.jar:/home/zheka/.m2/repository/com/android/support/support-annotations/21.0.0/support-annotations-21.0.0.jar:/home/zheka/.m2/repository/com/squareup/fest-android/1.0.0/fest-android-1.0.0.jar:/home/zheka/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/zheka/.m2/repository/com/android/support/support-v4/21.0.0/support-v4-21.0.0.jar:/home/zheka/.m2/repository/junit/junit/4.11/junit-4.11.jar] (No such file or directory)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.730 s
[INFO] Finished at: 2016-06-08T10:11:52+04:00
[INFO] Final Memory: 22M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.2:dex (default-cli) on project TestAndroid: Failed to execute mainDexClasses: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd '/home/zheka/workspace/GetStartAndroid/gmapExample' && '/home/zheka/Android/Sdk/build-tools/23.0.3/mainDexClasses' '--output' '/home/zheka/workspace/GetStartAndroid/gmapExample/target/mainDexClasses.txt' '"/home/zheka/workspace/GetStartAndroid/gmapExample/target/classes:/home/zheka/.m2/repository/org/easytesting/fest-assert-core/2.0M8/fest-assert-core-2.0M8.jar:/home/zheka/.m2/repository/org/easytesting/fest-util/1.2.3/fest-util-1.2.3.jar:/home/zheka/workspace/GetStartAndroid/gmapExample/target/unpacked-libs/cas_appcompat-v7_21.0.0/classes.jar:/home/zheka/workspace/GetStartAndroid/gmapExample/target/unpacked-libs/cgag_play-services_6.5.87/classes.jar:/home/zheka/.m2/repository/com/almende/eve/eve-bundle-android-ws/3.1.1/eve-bundle-android-ws-3.1.1.jar:/home/zheka/.m2/repository/com/android/support/support-annotations/21.0.0/support-annotations-21.0.0.jar:/home/zheka/.m2/repository/com/squareup/fest-android/1.0.0/fest-android-1.0.0.jar:/home/zheka/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/zheka/.m2/repository/com/android/support/support-v4/21.0.0/support-v4-21.0.0.jar:/home/zheka/.m2/repository/junit/junit/4.11/junit-4.11.jar"', Result = 10 -> [Help 1]
`

I try manual execute the last command without quotes ("") like this

`/bin/sh -c cd '/home/zheka/workspace/GetStartAndroid/gmapExample' && '/home/zheka/Android/Sdk/build-tools/23.0.3/mainDexClasses' '--output' '/home/zheka/workspace/GetStartAndroid/gmapExample/target/mainDexClasses.txt' '/home/zheka/workspace/GetStartAndroid/gmapExample/target/classes:/home/zheka/.m2/repository/org/easytesting/fest-assert-core/2.0M8/fest-assert-core-2.0M8.jar:/home/zheka/.m2/repository/org/easytesting/fest-util/1.2.3/fest-util-1.2.3.jar:/home/zheka/workspace/GetStartAndroid/gmapExample/target/unpacked-libs/cas_appcompat-v7_21.0.0/classes.jar:/home/zheka/workspace/GetStartAndroid/gmapExample/target/unpacked-libs/cgag_play-services_6.5.87/classes.jar:/home/zheka/.m2/repository/com/almende/eve/eve-bundle-android-ws/3.1.1/eve-bundle-android-ws-3.1.1.jar:/home/zheka/.m2/repository/com/android/support/support-annotations/21.0.0/support-annotations-21.0.0.jar:/home/zheka/.m2/repository/com/squareup/fest-android/1.0.0/fest-android-1.0.0.jar:/home/zheka/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/zheka/.m2/repository/com/android/support/support-v4/21.0.0/support-v4-21.0.0.jar:/home/zheka/.m2/repository/junit/junit/4.11/junit-4.11.jar'
`

and such error is fixing. 

Is there any way to do that's command in a proper way in Linux? I compared with other group com.jayway.maven.plugins.android.generation2 and there is other command but work at Linux fine.

**Comment by mosabua** [comment]
I can not really tell fom is going on from this error message. You should also NOT run mvn android:dex as such,. Instead you should rely on the lifecycle bindings of the plugin and run e.g. mvn package.

We will have to get an example project that shows the problem as well as more information about your environment. Please see  http://simpligility.github.io/android-maven-plugin/report-issue.html for more info

For now I will close this issue. Reopen once you have more information for us.
