### ISSUE TITLE
AAR dependendy causes strange res/ folder inclusion

### ISSUE THREAD

**Issue by floyd1982** [simpligility/android-maven-plugin#732]
Hi,

I got two problems here I don't understand, which seem to belong together:

(1)
ProjectA (apk) depends on ProjectB (aar). In the resulting ProjectA.apk file the resources (res/) from ProjectB are twice in there. One time "merged" with the resources from ProjectA (inside the res/ folder as I would expect it), and a second time in the root of the .apk file, which I don't understand why.

(2)
A kind of similar problem: As soon as my resource folder from ProjectA is NOT literally src/main/res/ but e.g. src/main/resources, all resources from ProjectA are also lying in the root of the .apk file AND in the res/ folder where I would expect them only.

I would be very glad if you could help me out or clear up a misunderstanding.
If these are two unrelated problems I can of course create a second issue for that.

Thanks very much in avdance for help!

Kind regards,
Stefan

**Comment by mosabua** [comment]
src/main/resources is for Java resources, src/main/res is the default location for android related resources.. they are treated differently. I am not sure where you are using what so without some example I cant make more sense of this. Just in general.. you are mostly like wanting to use src/main/res mostly..

**Comment by floyd1982** [comment]
Hey, thanks for the fast reply!

Oh I see.... I thought everything is fine when I configure it this way, but it isn't so?

<configuration>
   <resourceDirectory>src/main/resources/</resourceDirectory>
</configuration>

**Comment by mosabua** [comment]
No ... thats a bad idea since it mixes up the java resources and their processing via the java related maven plugins with the processing done via the android maven plugin.. I would stick to the defaults to be hoenst.. thats easiest

**Comment by floyd1982** [comment]
Okay, this helps a lot, thank you very much!

Would it be good to document this? The existence of the <resourceDirectory> tag brought me to the idea that I can use it without further problems...

**Comment by mosabua** [comment]
Might be a good idea. Want to send a pull request for the relevant javadocs or a new separate page?

**Comment by floyd1982** [comment]
It would have helped me here:
https://simpligility.github.io/android-maven-plugin/generate-sources-mojo.html#resourceDirectory

A sentence like: "Avoid other default directories like "src/main/resources/" as this could provoke conflicts with other goals."

**Comment by mosabua** [comment]
Fixed
