### ISSUE TITLE
renameManifestPackage not working as expected

### ISSUE THREAD

**Issue by pschaad** [simpligility/android-maven-plugin#736]
I encountered the following problem:
The app I implemented includes another project as a dependency (of type aar). Both projects share the same parent pom. The dependency includes resources, which the app is using. To access the resources within the library project, the resource id is fetched by calling `context.getResources().getIdentifier(resourceKey, resourceType, packageName)`. I get the package name by calling `getPackageName()`    on the given `context` object. 
Before changing the package names of the projects by using

    <renameManifestPackage>com.example.newpackagename</renameManifestPackage> 
accessing the library resources worked fine. But after renaming the package name of the app I get a `android.content.res.Resources$NotFoundException` because the `getIdentifier()` call still expects the old package name of the app and calling `getPackageName()` returns the new one (as expected).

**Comment by mosabua** [comment]
Well .. it did rename the manifest package right? it just did not rename all resources and everything inside. Imho that would be beyond the scope of this configuration.

**Comment by pschaad** [comment]
Thank you for your fast respond! Yes, the manifest package was renamed successfully. I expected it to also rename the resources since they can be accessed by providing the package name, but I can see that this can be viewed as out of scope for this configuration.
