### ISSUE TITLE
Created dummy classes.jar before clean

### ISSUE THREAD

**Issue by jlimek** [simpligility/android-maven-plugin#737]
when I run  `mvn clean deploy` gets

> Failed to execute goal on project XXX: Could not resolve dependencies for project XXX: Could not find artifact com.google.firebase:firebase-core:jar:9.0.2 at specified path /var/lib/jenkins/workspace/XXX/lib/target/unpacked-libs/cgf_firebase-core_9.0.2/classes.jar -> [Help 1]

In the logs I see:

> [DEBUG] Adding to classpath : /var/lib/jenkins/workspace/XXX/lib/target/unpacked-libs/cgf_firebase-core_9.0.2/classes.jar 
> [DEBUG] Created dummy classes.jar exist=true

before:

> [INFO] Deleting file /var/lib/jenkins/workspace/XXX/lib/target/unpacked-libs/cgf_firebase-core_9.0.2/classes.jar
> [INFO] Deleting directory /var/lib/jenkins/workspace/XXX/lib/target/unpacked-libs/cgf_firebase-core_9.0.2

When I delete manually target dir and run  `mvn deploy` then works well.
firebase-core is AAR without classes.jar 

Plugin version: 4.4.3

**Comment by mosabua** [comment]
Could you share an example pom or project to replicate the problem?

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
