### ISSUE TITLE
Import dependency with no classes.jar

### ISSUE THREAD

**Issue by kemmo** [simpligility/android-maven-plugin#740]
Hi, 

I'm trying to import the following dependency into my android project:
`<dependency>`
`<groupId>io.pristine</groupId>`
`<artifactId>libjingle</artifactId>`
`<version>11139</version>`
`<type>aar</type>`
`</dependency>`

The problem is that dependency **does not contain** any classes.jar. All other dependencies I have contains it.
When I try to compile my project, it fails because the plugin does not find the _classes.jar_ file.

The error is the following:
`[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.3:generate-sources (default-generate-sources) on project XXXX: Error generating BuildConfig: XXXX/XXXX/target/unpacked-libs/ip_libjingle_11139/classes.jar (No such file or directory) -> [Help 1]`

The version of the plugin I'm using is 4.4.3
Is there a way to avoid looking for that classes.jar?

Thanks!

**Comment by Stuey86** [comment]
Possiblly same issue as https://github.com/simpligility/android-maven-plugin/issues/713

**Comment by kemmo** [comment]
@Stuey86 I think it is not the same issue. I've already try to compile it with an ubuntu machine (native, not a VM in OSX) with same results.

Also, the #713 says "Can't read classes.jar", but what I get is a FileNotFoundException because classes.jar is not inside the aar package.

Thanks.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
