### ISSUE TITLE
which repository can I get android-maven-plugin?

### ISSUE THREAD

**Issue by scenus** [simpligility/android-maven-plugin#741]
I'm not sure if here is a correct place to ask this question, anyway,
maven central repository only contains android-maven-plugin up to version 4.0.0-rc.2
https://mvnrepository.com/artifact/com.jayway.maven.plugins.android.generation2/android-maven-plugin

where can I get newest version 4.4.3?

**Comment by mosabua** [comment]
The URL you are linking is NOT the Central Repository and the GAV coordinate you are using is wrong. The plugin is available via the default Central Repository built into Maven. 

E.g. check 

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.simpligility.maven.plugins%22%20AND%20a%3A%22android-maven-plugin%22

and

https://repo1.maven.org/maven2/com/simpligility/maven/plugins/android-maven-plugin/
