### ISSUE TITLE
how to add explicit configuration overrides for files or folders ?

### ISSUE THREAD

**Issue by scenus** [simpligility/android-maven-plugin#742]
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.3:generate-sources (default-generate-sources) on project xxxxx:
[ERROR]
[ERROR] Found files or folders in non-standard locations in the project!
[ERROR] ....This might be a side-effect of a migration to Android Maven Plugin 4+.
[ERROR] ....Please observe the warnings for specific files and folders above.
[ERROR] ....Ideally you should restructure your project.
[ERROR] ....Alternatively add explicit configuration overrides for files or folders.
[ERROR] ....Finally you could set failOnNonStandardStructure to false, potentially resulting in other failures.

I searched android-maven-plugin project home but I could not find documentation on how to add explicit configuration overrides for files or folders,
how may I do that ?

**Comment by mosabua** [comment]
E.g. here https://github.com/simpligility/android-maven-plugin/blob/master/src/main/java/com/simpligility/maven/plugins/android/AbstractAndroidMojo.java#L188

What do you specifically want to override? Also .. I would suggest to use the standard location where possible since thats better tested.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
