### ISSUE TITLE
Support apksigner

### ISSUE THREAD

**Issue by Shusshu** [simpligility/android-maven-plugin#747]
https://developer.android.com/studio/releases/build-tools.html

Added apksigner, an APK signing tool to replace jarsigner. By default, apksigner signs APKs using the conventional JAR signing scheme (used by jarsigner) and the APK Signature Scheme v2 introduced in Android 7.0 (API level 24). Any modification to an APK signed with APK Signature Scheme v2 invalidates its signature. Thus, APK post-processing, such as zipalign, must be performed before apksigner is invoked, not after. Invoking zipalign before apksigner works fine because apksigner preserves APK alignment and compression (unlike jarsigner).

**Comment by mosabua** [comment]
closing as we are not taking care of feature requests for now.
