### ISSUE TITLE
ResourceClassGenerator always generates final fields

### ISSUE THREAD

**Issue by hameno** [simpligility/android-maven-plugin#756]
It seems that the old version of SymbolWriter from the android builder always writes the fields as final fields. 
Updated to 2.2.3 the SymbolWriter class allows to specify whether to use ```final``` fields.

This should probably be fixed for aar libraries as their tests currently fail with robolectric 3.2.1 (see https://github.com/robolectric/robolectric/issues/2847)

**Comment by hameno** [comment]
Tried updating to the newer 2.2.3 but I don't know how to fix ManifestMergerMojo, since that class seems to depend heavily on classes which are gone in 2.2.3

**Comment by Shusshu** [comment]
I can help you with that class. Do you have a branch with the ongoing changes?

**Comment by hameno** [comment]
Not yet, my "fix" was to always call the SymbolWriter in a way that does not use final fields, but that would be wrong. I'm not sure how I can detect if the generation is run during test lifecycle (and inside an aar library).

**Comment by hameno** [comment]
Pushed my minimal changes: https://github.com/sprylab/android-maven-plugin/tree/final_ids

**Comment by hameno** [comment]
I've created a WIP PR: #757

**Comment by Schlud** [comment]
Hi guys. 
First of all thank you for your great work!
 
I've noticed that you are currently working on [PR:#757](https://github.com/simpligility/android-maven-plugin/pull/757)
Do you now, if there is a pre-release version available for getting and testing the fixed state?

Thanks

**Comment by Shusshu** [comment]
You can build it locally and try it out. It would be good to know how it works for your use cases

**Comment by hameno** [comment]
Fixed with #757
