### ISSUE TITLE
Use of sun.misc.BASE64Encoder prevents the plugin to run on Java 9

### ISSUE THREAD

**Issue by henri-tremblay** [simpligility/android-maven-plugin#759]
We get the following error (on plugin version 4.4.3)

> A required class was missing while executing com.simpligility.maven.plugins:android-maven-plugin:4.4.3:apk: sun/misc/BASE64Encoder

After digging a bit, it is coming from sdklib (`ApkBuilder->SignedJarBuilder`). I also tried against your current master and had the same issue.

**Comment by henri-tremblay** [comment]
I also reported an Android bug: https://issuetracker.google.com/issues/62471410

**Comment by mosabua** [comment]
Until the Android SDK itself supports Java 9 we wont be able to do anything anyway. Please reopen when that happens.

**Comment by Hanmac** [comment]
@mosabua the google issue says
> SignedJarBuilder is deprecated (has been for a long time: 2013). You need to move away from it.
So is there an alternative?

@henri-tremblay you said:
> Right now, android-maven-plugin 4.5.0 isn't failing on this error anymore. So I will consider this solved.

But #792 shows that this is still the case?

**Comment by allentiak** [comment]
@mosabua said:
> Until the Android SDK itself supports Java 9 we wont be able to do anything anyway. Please reopen when that happens.

Maybe now is the time to reopen this?

**Comment by Hanmac** [comment]
i did a bit of digging ... it seems they fixed that somewhere a few (9) years ago:
https://android.googlesource.com/platform/tools/build/+/480ed761ecf78336e0445f90b6d0797dde80ee67%5E%21/#F1
it was also renamed before/again.
https://android.googlesource.com/platform/tools/build/+/refs/heads/master/builder/src/main/java/com/android/builder/signing/SignedJarBuilder.java

now the part would be to try to find an sdklib with that change inside

it also got moved later from tools/build into tools/base
https://android.googlesource.com/platform/tools/base/+/44ec68cd14d3eb74137a941299861c64215f301b

https://android.googlesource.com/platform/tools/base/+/refs/heads/master/build-system/builder/src/main/java/com/android/builder/signing/SignedJarBuilder.java

**Comment by allentiak** [comment]
Hannac said:
> I did a bit of digging
[...]

@Hanmac I'm a little bit lost here...
Would you be so kind to elaborate on the implications of this comment, please?

**Comment by Hanmac** [comment]
they said that the old SignedJarBuilder was deprecated

i tried to found what the alternative would be. 

i only found this: https://github.com/pixnet/android-platform-tools-base/blob/master/sdklib/src/main/java/com/android/sdklib/internal/build/SignedJarBuilder.java
probably a fork on github, saying `Use Android-Builder instead`

so i was locking for AndroidBuilder, but the only sources i found where still using some kind of SignedJarBuilder.
but i checked the code of them on the linked tools pages so see that they were updated some time in the past.

now i'm looking at what package of sdklib would have that update.
