### ISSUE TITLE
ApkMojo doesn't include META-INF resources from dependent jars

### ISSUE THREAD

**Issue by william-ferguson-au** [simpligility/android-maven-plugin#764]
ApkMojo uses `ApkBuilder#addResourcesFromJar` from com.android.tools.sdklib:25.3.0. That method call explicitly ignores any jar entries in the META-INF folder. This means that libraries that rely on metadata contained in the META-INF folder (such as the ServiceLoader mechanism) will not work.

See https://issuetracker.google.com/issues/65531847

The only work around I can see, is to unpack the contents of META-INF for each dependent jar and invoke `ApkBuilder#addFile` for each of them.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
