### ISSUE TITLE
ARR reference can not be referenced in the encoding!

### ISSUE THREAD

**Issue by MickeyMi** [simpligility/android-maven-plugin#767]
Hello there! I import the com.android.support:design compiler can generate APK and installation, but can not be cited in the coding!

<dependency>
			<groupId>com.android.support</groupId>
			<artifactId>design</artifactId>
			<version>25.3.1</version>
			<type>aar</type>
</dependency>
![_20171206173223](https://user-images.githubusercontent.com/31444844/33654576-82d5412e-daab-11e7-9eaf-b9a56000f946.png)

**Comment by MickeyMi** [comment]
![_20171206173223](https://user-images.githubusercontent.com/31444844/33654553-7133fbd6-daab-11e7-90e7-32bc8a4dddc8.png)

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
