### ISSUE TITLE
AAR Failure to collect dependencies

### ISSUE THREAD

**Issue by jsalerno** [simpligility/android-maven-plugin#770]
I have an aar dependency which cannot be processed with plugin version 4.5.0.

The error is consistently 'Failed to collect dependencies'.
This occurs whether I specify the dependency type as aar or pom.
Here is the dependency declaration in my pom.xml:
```
<dependency>
	<groupId>com.google.firebase</groupId>
	<artifactId>firebase-core</artifactId>
	<version>11.0.4</version>
	<type>pom</type>
</dependency>
```
The error is : `Could not resolve dependencies for project myapp:apk:0.0.1-SNAPSHOT: Failed to collect dependencies at com.google.firebase:firebase-core:pom:11.0.4 -> com.google.firebase:firebase-analytics:aar:[11.0.4]: No versions available for com.google.firebase:firebase-analytics:aar:[11.0.4] within specified range -> [Help 1]`

All of the necessary dependencies are in my local repo (installed via maven-android-sdk-deployer)
The plugin config includes
```<includeLibsJarsFromAar>true</includeLibsJarsFromAar>```
and I have the consume-aar goal specified:
```
<plugin>
	<groupId>org.eclipse.m2e</groupId>
	<artifactId>lifecycle-mapping</artifactId>
	<version>1.0.0</version>
	<configuration>
		<lifecycleMappingMetadata>
			<pluginExecutions>
				<pluginExecution>
					<pluginExecutionFilter>
						<groupId>
							com.simpligility.maven.plugins
						</groupId>
						<artifactId>
							android-maven-plugin
						</artifactId>
						<versionRange>
							[4.5.0,)
						</versionRange>
						<goals>
							<goal>consume-aar</goal>
						</goals>
					</pluginExecutionFilter>
					<action>
						<ignore></ignore>
					</action>
				</pluginExecution>
			</pluginExecutions>
		</lifecycleMappingMetadata>
	</configuration>
</plugin>
```

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
