### ISSUE TITLE
Program type already present: com.android.volley.BuildConfig	

### ISSUE THREAD

**Issue by paramesh401** [simpligility/android-maven-plugin#772]
Program type already present: com.android.volley.BuildConfig
Message{kind=ERROR, text=Program type already present: com.android.volley.BuildConfig, sources=[Unknown source file], tool name=Optional.of(D8)}

this is the error I'm getting in android studio .Please help me resolve this erroe, thanks in advance

**Comment by datpt10** [comment]
In general that kind of error implies that there are two copies of Volley somewhere in your build path. Did you remove the .jar from your local libs folder when you added the dependency on 1.1.0? Does ./gradlew dependencies show anything unexpected?

I got the answer from the author of Volley. Hope it helps too.

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
