### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by Vorta1** [simpligility/android-maven-plugin#775]
Hello,

is it possible to set the plugin configuration to obtain a reproducible build of apks / apklibs? 

As far as I can see everything packaged within the builds artefacts is fine except for the build generated files that are added in, which so far appear to be the META-INF folder and AndroidMainifest.xml file, because their meta data has the date-time created/modified of the file set to the date-time of the maven build.

This causes the resulting md5sum of the apk / apklib artefact to change each build when no changes were made - the build itself causes the diff.

Jar artefacts by default also suffer from the same issue - but there is another maven plugin which resolves the above problem, the [reproducible-build-maven-plugin](https://zlika.github.io/reproducible-build-maven-plugin/) where the strip-jar goal appears to set the files within the jar to the same date-time each build so the checksums are reproducible.

Does the android-maven-plugin already have configuration options for this? Any help is appreciated.

With thanks,

Pete.

**Comment by mosabua** [comment]
Sorry... this is not supported. A new build will at least update timestamp metadata.
