### ISSUE TITLE
Release 4.6.0

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-maven-plugin#786]
Need to get through all the PRs, do some local testing, upgrade parent and probably fix up site build. 

Probably also update usage / tests around Android SDK requirements. 

Then cut new release

**Comment by mosabua** [comment]
Had to update my local env quite a bit. Normal build now passes again at least. For integration tests to pass I had to disable four tests for now.

**Comment by mosabua** [comment]
I think I should cut a 4.6.0-RC1 release at this stage just to get it out there and work with the Netbeans folks and whoever else can help with the cleanup. 

Wdyt @simpligility/android-maven-plugins-core-committers

**Comment by cfiehe** [comment]
Because the d8 integration was already merged, but does not work properly, I would not recommend a release even a release candidate with this issue. Consider to merge my pull request beforehand. It is fully backward compatible. The d8 integration can be improved in following development cycles.

**Comment by mosabua** [comment]
Released 4.6.0 now. Should be on Central soon. There is more clean up and such to do after.. but at least a release is out. Looking forward to PRs with fixes.

**Comment by william-ferguson-au** [comment]
Well done Manfred

**Comment by mosabua** [comment]
Thanks.. I still have lots of clean up to do .. at least figure out the test failures (set some to Ignore) and maybe remove some cruft. . but hopefully I get some feedback and contrib from actual users. I am not really active on the Android dev side these days..

**Comment by mosabua** [comment]
But I am also happy to cut more releases ..

**Comment by cfiehe** [comment]
That is good news.

Thank you very much for the release and for merging my pull request.

**Comment by dukescript** [comment]
Great news. Thanks!

**Comment by mosabua** [comment]
Announced on mailing list and twitter. 

https://www.simpligility.com/2019/05/android-maven-plugin-4-6-0-released/
