### ISSUE TITLE
Support Request: JAR application needs code packaged in AAR

### ISSUE THREAD

**Issue by mouyang** [simpligility/android-maven-plugin#790]
I have a JAR application that wants to use Facebook Graph API; this code for this only available in Facebook Android SDK which is packaged as an AAR and uses com.android.support:support-annotations and  com.android.support:support-core-utils.  It would be nice if classes in an AAR were accessible within a JAR like any other JAR but it seems like this plugin has taken measures so that AAR are only only within the Android ecosystem: 
https://stackoverflow.com/questions/37903371/#comment63861438_38141575, https://github.com/simpligility/android-maven-plugin/pull/413, https://github.com/simpligility/android-maven-plugin/issues/620.

It doesn't seem like it is a simple matter of reverting the pull request #413.  Is my next course of action to ask request Facebook to remove the dependency on those Android support AARs?  I'm sure there are other Java libraries that will meet my needs, but I would like to use Facebook SDK implementation if I can help it.

**Comment by william-ferguson-au** [comment]
To be blunt, an AAR packaging is specifically for the Android ecosystem. If
Facebook have published their SDK as an AAR and especially since they have
declared a dependency on 2 other Android packages it sounds like you don't
want to use that Facebook library for your pure Java app. It is likely to
fail spectacularly.

**Comment by mosabua** [comment]
I agree with @william-ferguson-au .. using an AAR in a normal Java application is a disaster in the making. There is no tooling for dealing with AAR files outside the Android ecosystem.

**Comment by mouyang** [comment]
Thank you for clearing it up.  I will take this up with the library Facebook SDK team.

**Comment by malachid** [comment]
On their site, they do list some Java-specific ones; albeit under the 3rd
party section.

https://developers.facebook.com/docs/apis-and-sdks/

**Comment by mouyang** [comment]
Yeah I wanted avoid 3rd party and strong types if I could help it.  But I fully understand and support your team's perspective and went forward with it.  Thanks for talking it out with me.
